// Generated from Base Camp 1.9.10 (BaseCamp.UI: EverestDataHelper.GetEverestKeys_*).
// Main legend of every key whose printing differs from the US layout, by LED
// index. Only the keycap text is used from Mountain's tables. Mountain's index
// errors are corrected here:
//  - German, Italian, Nordic and Spanish index three keys on the F1/F11/F12
//    LEDs (9, 99, 108): moved to the LEDs of the keys they print (1, 100, 109);
//  - the ANSI tables (Hebrew, Korean) list `]` as 111, but its LED is 110.
enum LayoutLegends {
    static let overrides: [KeyboardLayout: [Int: String]] = [
        .french: [
            1: "²",
            4: "MAJ",
            11: "A",
            12: "Q",
            13: "<",
            20: "Z",
            22: "W",
            41: "Barre d'espace",
            76: ",",
            85: ";",
            93: "M",
            94: ":",
            100: ")",
            101: "^",
            102: "ù",
            103: "!",
            110: "$",
            111: "*",
            121: "MAJ",
        ],
        .german: [
            1: "^",
            13: "<",
            22: "Y",
            41: "Spatiebalk",
            56: "Z",
            88: "ENTF",
            93: "Ö",
            96: "EINFG",
            97: "Ende",
            100: "ß",
            101: "Ü",
            102: "Ä",
            103: "-",
            105: "POS1",
            106: "BILD ⏷",
            109: "´",
            110: "+",
            111: "#",
            114: "Rollen",
            115: "BILD ⏶",
            117: "DRUCK S-ABF",
            123: "Pause UNTBR",
        ],
        .italian: [
            1: "\\",
            13: "<",
            41: "Barra spaziatrice",
            93: "ò",
            100: "?",
            101: "è",
            102: "à",
            103: "-",
            109: "ì",
            110: "+",
            111: "ù",
        ],
        .nordic: [
            1: "§",
            13: "<",
            41: "Mellomrom",
            93: "Ø",
            100: "+",
            101: "Å",
            102: "Æ",
            103: "-",
            109: "\\",
            110: "¨",
            111: "'",
        ],
        .spanish: [
            1: "º",
            3: "BLOCQ MAYÚS",
            4: "MAYÚS",
            13: "<",
            41: "Barra espaciadora",
            88: "Supr",
            93: "Ñ",
            97: "Fin",
            100: "'",
            101: "`",
            102: "´",
            103: "-",
            105: "Inicio",
            106: "Av Pág",
            109: "¡",
            110: "+",
            111: "Ç",
            114: "Bloq Despl",
            115: "Re Pág",
            117: "Impr Pant",
            121: "MAYÚS",
            123: "Pausa Inter",
        ],
        .portuguese: [
            1: "\\",
            13: "<",
            29: "€",
            93: "ç",
            100: "'",
            101: "+",
            102: "º",
            103: "-",
            109: "«",
            111: "~",
        ],
        .hebrew: [
            1: ";",
            11: "/",
            12: "ש",
            20: "'",
            21: "ד",
            22: "ז",
            29: "ק",
            30: "ג",
            31: "ס",
            38: "ר",
            39: "כ",
            40: "ב",
            47: "א",
            48: "ע",
            49: "ה",
            56: "ט",
            57: "י",
            58: "נ",
            65: "ו",
            66: "ח",
            67: "מ",
            74: "ן",
            75: "ל",
            76: "צ",
            83: "ם",
            84: "ך",
            85: "ת",
            92: "פ",
            93: "ף",
            94: "ץ",
            101: "]",
            102: ",",
            103: ".",
            110: "[",
        ],
        .korean: [
            11: "ㅂ",
            12: "ㅁ",
            20: "ㅈ",
            21: "ㄴ",
            22: "ㅋ",
            29: "ㄷ",
            30: "ㅇ",
            31: "ㅌ",
            38: "ㄱ",
            39: "ㄹ",
            40: "ㅊ",
            47: "ㅅ",
            48: "ㅎ",
            49: "ㅍ",
            56: "ㅛ",
            57: "ㅗ",
            58: "ㅠ",
            65: "ㅕ",
            66: "ㅓ",
            67: "ㅜ",
            68: "한/엉",
            74: "ㅑ",
            75: "ㅏ",
            76: "ㅡ",
            83: "ㅐ",
            84: "ㅣ",
            92: "ㅔ",
            95: "한자",
            119: "￦",
        ],
    ]
}
