// Interface strings — en. Generated from the spec once, now edited by hand.
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let en: [String: String] = [
        // MARK: action
        "action.app": "Application",
        "action.keypress": "Shortcut",
        "action.none": "None",
        "action.open": "File",
        "action.shell": "Command",
        "action.text": "Text",
        "action.textToType": "Text to type",
        "action.url": "Link",

        // MARK: app
        "app.closeWindow": "Close window",
        "app.copy": "Copy",
        "app.cut": "Cut",
        "app.edit": "Edit",
        "app.hide": "Hide Everest",
        "app.paste": "Paste",
        "app.quit": "Quit Everest",
        "app.selectAll": "Select All",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS actions and typed shortcuts need the Accessibility permission (Settings → Privacy & Security).",
        "buttons.actionRan": "%1$@ action executed.",
        "buttons.appHint": "Opens the app or brings it to the front",
        "buttons.clearLeftovers": "Erase leftover actions",
        "buttons.daemonStopped": "The daemon is stopped",
        "buttons.daemonStoppedNote": "Actions only run while it is listening to the D1–D4 keys.",
        "buttons.factoryValues": "Factory settings",
        "buttons.factoryValuesHelp": "Restores the original picture and action of %1$@",
        "buttons.flashMemory": "Keyboard memory",
        "buttons.flashMemoryNote": "Base Camp may leave actions in flash memory (e.g. D4 sending Escape)",
        "buttons.keyHeader": "KEY %1$@",
        "buttons.noAction": "No action — the key is ignored.",
        "buttons.noApp": "No app chosen",
        "buttons.pickPresetAppImage": "Preset, app or image for %1$@",
        "buttons.presetsAndIcon": "Presets and icon…",

        // MARK: clock
        "clock.analog": "Analogue",
        "clock.digital": "Digital",
        "clock.sync": "Sync",

        // MARK: colormode
        "colormode.dual": "Two colours",
        "colormode.quad": "4 colours",
        "colormode.rainbow": "Rainbow",
        "colormode.single": "One colour",
        "colormode.withBackground": "Key + background",

        // MARK: common
        "common.active": "Active",
        "common.add": "New",
        "common.choose": "Choose…",
        "common.close": "Close",
        "common.configure": "Configure",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.name": "Name",
        "common.other": "Other…",
        "common.refresh": "Refresh",
        "common.remove": "Remove",
        "common.start": "Start",
        "common.stop": "Stop",
        "common.test": "Test",

        // MARK: daemon
        "daemon.keysActive": "D1–D4 keys active",
        "daemon.stopped": "Daemon stopped",

        // MARK: device
        "device.blocked": "Firmware not supported",
        "device.connected": "Connected",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Disconnected",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Complete Everest Max",
        "device.keyboardMissing": "keyboard not available",
        "device.keyboardUnavailable": "Keyboard not available (not found, or firmware not supported).",
        "device.notConnected": "Not connected",
        "device.refresh.help": "Refresh the keyboard state",
        "device.withDock": "Keyboard + media dock",
        "device.withNumpad": "Keyboard + numpad",

        // MARK: displays
        "displays.change": "Change…",
        "displays.chooseImage": "Choose an image…",
        "displays.dial.subtitle": "Round 240 × 204 screen on the media dock",
        "displays.display": "Display",
        "displays.factoryIcon": "Factory icon",
        "displays.factoryLogo": "Factory logo",
        "displays.imageCropped": "The image is cropped to 240 × 204.",
        "displays.imagesResized": "Images are resized to 72 × 72.",
        "displays.keys.subtitle": "Four 72 × 72 screens above the numpad",
        "displays.keys.title": "Display keys",
        "displays.logoRestored": "Mountain logo restored on the dial.",
        "displays.metricsNote": "CPU, GPU, RAM, disk, network and volume show the values sent by the daemon (System page).",

        // MARK: factory
        "factory.activityMonitor": "Activity Monitor",
        "factory.sleep": "Sleep",

        // MARK: firmware
        "firmware.block.body": "Everest has only been tested with firmware %1$@. To avoid any risk of bricking your keyboard, it sends nothing to it until it runs that version: no lighting, no pictures, no actions.",
        "firmware.block.check": "Check again",
        "firmware.block.detected": "Detected firmware: %1$@",
        "firmware.block.how": "Mountain only offers the firmware update in its official Base Camp application for Windows. Plug the keyboard into a Windows PC, install Base Camp, update the firmware, then plug the keyboard back into this Mac: Everest detects it by itself.",
        "firmware.block.howTitle": "How to update the keyboard",
        "firmware.block.tested": "Tested firmware: %1$@",
        "firmware.block.title": "Firmware not supported",
        "firmware.block.unreadableBody": "Everest cannot check the keyboard's firmware version, so it does not touch it. Unplug and replug the keyboard, then try again.",
        "firmware.block.unreadableTitle": "Firmware unreadable",
        "firmware.block.why": "Everest does not update the firmware itself: it is the same kind of operation that can make a keyboard unusable, and it cannot be tested here.",
        "firmware.status.unreadable": "The keyboard did not report its firmware — it is left untouched.",
        "firmware.status.unsupported": "Firmware %1$@ is not supported (tested: %2$@) — the keyboard is left untouched.",

        // MARK: fx
        "fx.breathing": "Breathing",
        "fx.breathing.desc": "Gentle pulsing",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Falling drops",
        "fx.off": "Off",
        "fx.off.desc": "Everything is off",
        "fx.reactive": "Reactive",
        "fx.reactive.desc": "Lights up as you type",
        "fx.static": "Static",
        "fx.static.desc": "Fixed colour",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Spins around the centre",
        "fx.wave": "Wave",
        "fx.wave.desc": "Sweeps across the keyboard",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Ripple from the key",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Also apply the preset's action",
        "keyappearance.appHint": "The key opens the app, or brings it to the front if it is already open.",
        "keyappearance.apps": "Applications",
        "keyappearance.background": "Continue in the background",
        "keyappearance.busyOther": "A transfer is running on %1$@ — wait for it to finish before changing this key.",
        "keyappearance.chooseFile": "Choose a file…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Opens the app",
        "keyappearance.ownImage": "Your own image",
        "keyappearance.ownImageNote": "It is cropped to the centre and resized to 72 × 72. The key's action does not change.",
        "keyappearance.presets": "Presets",
        "keyappearance.searchApp": "Search for an app",
        "keyappearance.step.prepare": "Preparing",
        "keyappearance.step.send": "Sending",
        "keyappearance.subtitle": "Choose what the screen shows and what the key does",
        "keyappearance.title": "Key %1$@",
        "keyappearance.transferNote": "A transfer takes about 20 seconds: the keyboard prepares the slot (it erases the old picture itself), then receives the new one in 64-byte packets. Do not unplug the keyboard.",

        // MARK: keyboard
        "keyboard.activeBadge": "ACTIVE",
        "keyboard.ansiShape": "ANSI shape: wide Enter, \\ at the end of the top row",
        "keyboard.asPrinted": "as printed",
        "keyboard.automatic": "Automatic",
        "keyboard.chosen": "CHOSEN BY HAND",
        "keyboard.clearRemaps": "Clear remaps",
        "keyboard.detected": "DETECTED",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. Lasts until restart. For a remap stored in the keyboard: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO key",
        "keyboard.isoMuteNote": "If macOS treats the keyboard as ANSI, the key to the left of Z does nothing",
        "keyboard.isoMuteTitle": "ISO key not responding?",
        "keyboard.isoShape": "ISO shape: tall Enter, extra key to the left of W/Z",
        "keyboard.legend.at": "@ on the ' key",
        "keyboard.legend.backslash": "\\ | left of Z",
        "keyboard.legend.quote": "\" on ⇧2",
        "keyboard.legend.rightOfSemicolon": "right of ;",
        "keyboard.macLayout": "macOS layout",
        "keyboard.macLayoutNote": "So that macOS types what is printed on the keys",
        "keyboard.noMacLayout": "No macOS layout matching “%1$@” is installed: add it in System Settings → Keyboard → Input Sources.",
        "keyboard.remapApplied": "ISO remap applied (until restart).",
        "keyboard.remapIso": "Remap the ISO key",
        "keyboard.remapsCleared": "hidutil remaps cleared.",
        "keyboard.reportsLayout": "The keyboard reports “%1$@”. Go back to automatic if this choice is no longer needed.",
        "keyboard.switchedTo": "Layout switched to %1$@.",
        "keyboard.title": "Physical keyboard",
        "keyboard.titleNote": "Read from the keyboard, like Base Camp: the drawing, keys and effects adapt to it",
        "keyboard.unknown": "unknown",
        "keyboard.use": "Use %1$@",
        "keyboard.verifiedNote1": "The shape and lighting of each key follow the keyboard's grid; only the UK layout has been verified on a real keyboard.",
        "keyboard.verifiedNote2": "The legends come from Base Camp's tables and the shape follows the LED grid; only the UK layout has been verified on a real keyboard.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "dial transfer interrupted — use “Unblock the keyboard” (System page) or replug it",
        "keyboardError.dialRefused": "the dial refused the transfer (nothing was written)",
        "keyboardError.interrupted": "transfer interrupted — use “Unblock the keyboard” (System page) or replug it",
        "keyboardError.refused": "the keyboard refused the transfer (nothing was written) — try again; if it persists, use “Unblock the keyboard” (System page)",
        "keyboardError.selectTarget": "the keyboard does not respond to the key selection — use “Unblock the keyboard” (System page) or replug it",

        // MARK: layout
        "layout.french": "French (AZERTY)",
        "layout.german": "German (QWERTZ)",
        "layout.hebrew": "Hebrew",
        "layout.italian": "Italian",
        "layout.korean": "Korean",
        "layout.nordic": "Nordic",
        "layout.portuguese": "Portuguese",
        "layout.spanish": "Spanish",
        "layout.uk": "United Kingdom (ISO)",
        "layout.us": "US (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Add a colour",
        "lighting.allHues": "All hues, generated by the keyboard.",
        "lighting.backgroundColour": "Background",
        "lighting.brightness": "Brightness",
        "lighting.byKeyboard": "Run by the keyboard — keeps going without the app",
        "lighting.byMac": "Rendered by the Mac — keep the app open",
        "lighting.clearAll": "Clear all",
        "lighting.clockwise": "Clockwise",
        "lighting.colors": "Colours",
        "lighting.colour": "Colour",
        "lighting.colour1": "Colour 1",
        "lighting.colour2": "Colour 2",
        "lighting.colourCount.one": "%1$@ colour",
        "lighting.colourCount.other": "%1$@ colours",
        "lighting.counterclockwise": "Anticlockwise",
        "lighting.direction": "Direction",
        "lighting.editEllipsis": "Edit…",
        "lighting.fast": "Fast",
        "lighting.flameNote": "Fixed flame ramp, from ember to white.",
        "lighting.freeze": "Freeze into the keyboard",
        "lighting.freezeNote": "Sends the current frame to the Custom slot and saves it: it stays without the app.",
        "lighting.keyColour": "Key",
        "lighting.ledsBlack": "All LEDs are black while the effect runs.",
        "lighting.macNote": "Rendered key by key at 30 frames/s, with your palette",
        "lighting.normal": "Normal",
        "lighting.offNote": "The backlight and side strips are off. Pick another effect to turn them back on.",
        "lighting.officialEffects": "Official effects",
        "lighting.officialNote": "Base Camp's effects, sent exactly like the Windows app",
        "lighting.paintHint": "Click or drag over the keys of the keyboard above.",
        "lighting.paintKeys": "Paint key by key",
        "lighting.palette": "Palette",
        "lighting.paused": "Paused",
        "lighting.reapply": "Apply again",
        "lighting.rightClickHint": "Right-click a swatch to remove it.",
        "lighting.rotation": "Rotation direction",
        "lighting.runningOnKeyboard": "Running on the keyboard",
        "lighting.savedInProfile": "Saved in the keyboard's active profile",
        "lighting.slow": "Slow",
        "lighting.speed": "Speed",
        "lighting.title": "Lighting",

        // MARK: live
        "live.keyboard": "Keyboard · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · paused",
        "live.pause": "Pause",
        "live.start": "Start",

        // MARK: macfx
        "macfx.aurora": "Aurora",
        "macfx.equalizer": "Equalizer",
        "macfx.fire": "Fire",
        "macfx.gradient": "Gradient",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Digital rain",
        "macfx.ripples": "Ripples",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Solid colour",
        "macfx.spectrum": "Spectrum",
        "macfx.spiral": "Spiral",
        "macfx.stars": "Stars",
        "macfx.waves": "Waves",

        // MARK: menu
        "menu.allowAccessibility": "Allow Accessibility…",
        "menu.disconnected": "Keyboard disconnected",
        "menu.firmwareBlocked": "Firmware not supported — keyboard left alone",
        "menu.keyboardEffects": "Keyboard effects",
        "menu.launchAtLogin": "Launch at login",
        "menu.macEffects": "Mac effects",
        "menu.manageProfiles": "Manage profiles…",
        "menu.newProfile": "New profile",
        "menu.open": "Open Everest…",
        "menu.pauseEffect": "Pause the effect",
        "menu.profile": "Profile: %1$@",
        "menu.resumeEffect": "Resume the effect",

        // MARK: metric
        "metric.disk": "DISK",
        "metric.network": "NETWORK",
        "metric.volume": "VOLUME",

        // MARK: mode
        "mode.clock": "Clock",
        "mode.disk": "Disk",
        "mode.image": "Image",
        "mode.network": "Network",
        "mode.volume": "Volume",

        // MARK: overview
        "overview.actionsActive": "Actions active",
        "overview.changeLighting": "Change lighting",
        "overview.dialSubtitle": "Round screen of the media dock",
        "overview.keyboardEffect": "Keyboard effect",
        "overview.macEffect": "Effect rendered by the Mac",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Ember",
        "palette.forest": "Forest",
        "palette.ice": "Ice",
        "palette.neon": "Neon",
        "palette.ocean": "Ocean",
        "palette.sunset": "Sunset",
        "palette.vapor": "Vapor",

        // MARK: preset
        "preset.bolt": "Lightning",
        "preset.calendar": "Calendar",
        "preset.captureScreen": "Capture screen",
        "preset.captureZone": "Capture area",
        "preset.category.apps": "Apps",
        "preset.category.decor": "Icon only",
        "preset.category.media": "Media",
        "preset.coffee": "Coffee",
        "preset.flame": "Flame",
        "preset.game": "Controller",
        "preset.heart": "Heart",
        "preset.home": "Home",
        "preset.lock": "Lock",
        "preset.music": "Music",
        "preset.mute": "Mute",
        "preset.next": "Next",
        "preset.playpause": "Play / Pause",
        "preset.previous": "Previous",
        "preset.sleepDisplay": "Turn off the display",
        "preset.star": "Star",
        "preset.volumeDown": "Volume −",
        "preset.volumeUp": "Volume +",

        // MARK: profile
        "profile.defaultName": "Profile %1$@",
        "profile.main": "Main",

        // MARK: profiles
        "profiles.addApp": "Add an app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Automatic switching",
        "profiles.autoSwitchHint": "Works while the app is open or the daemon is running. A profile chosen by hand on the dial is not replaced as long as you stay in an app with no profile.",
        "profiles.autoSwitchNote": "The keyboard switches to an app's profile when it is in front",
        "profiles.deleteHelp": "Delete this profile from the app",
        "profiles.dialMode": "Dial: %1$@",
        "profiles.dialOnActivate": "Dial on activation",
        "profiles.dialUnchanged": "Dial unchanged",
        "profiles.dontChange": "Don't change",
        "profiles.enable": "Enable",
        "profiles.freeSlots": "%1$@ free slot(s)",
        "profiles.hardwareNote": "The keyboard keeps five profiles in memory (the dial's Profile menu). Each has its own lighting, remaps and D1–D4 pictures; the app adds the key actions, the dial mode and the linked apps. The DisplayPad's twelve keys are saved in each profile too.",
        "profiles.header": "PROFILE %1$@",
        "profiles.iconAndColour": "Icon and colour",
        "profiles.keyboardLighting": "Keyboard lighting",
        "profiles.keyboardProfiles": "KEYBOARD PROFILES",
        "profiles.keysNote": "The D1–D4 keys and lighting are set on their own pages while this profile is active: they are saved in this profile.",
        "profiles.lightingFirmware": "Lighting: %1$@",
        "profiles.lightingMac": "Mac lighting: %1$@",
        "profiles.linkedApps": "Linked apps",
        "profiles.manage": "Manage…",
        "profiles.namePlaceholder": "Coding, Music…",
        "profiles.noLinkedApp": "No linked app",
        "profiles.otherwise": "Otherwise, go back to",
        "profiles.slot": "Slot %1$@",
        "profiles.slotOf": "Profile %1$@ of %2$@",

        // MARK: reset
        "reset.title": "Reset",

        // MARK: section
        "section.buttons.subtitle": "A macOS action on each of the four display keys",
        "section.buttons.title": "Keys D1–D4",
        "section.displays.subtitle": "The dial's round screen and the numpad's display keys",
        "section.displays.title": "Displays",
        "section.keyboard.subtitle": "Detected keyboard layout and the matching macOS layout",
        "section.keyboard.title": "Layout",
        "section.lighting.subtitle": "Official keyboard effects and dynamic effects rendered by the Mac",
        "section.overview.subtitle": "Your Everest Max at a glance",
        "section.overview.title": "Overview",
        "section.profiles.subtitle": "Five profiles stored in the keyboard, each with its own keys, lighting and apps",
        "section.profiles.title": "Profiles",
        "section.system.subtitle": "Button daemon, monitoring and troubleshooting",
        "section.system.title": "System",

        // MARK: settings
        "settings.language.automatic": "Automatic (system language)",
        "settings.language.note": "Language of the interface, the menu bar menu and messages.",
        "settings.language.title": "Language",

        // MARK: status
        "status.animationPaused": "Animation paused — the keyboard keeps the last frame.",
        "status.appIconUnreadable": "Could not read the app's icon.",
        "status.appNoId": "This app has no identifier: it cannot be linked.",
        "status.changeFailed": "Could not change it: %1$@",
        "status.cleaning": "Cleaning up",
        "status.clockSynced": "Clock synced with the Mac.",
        "status.configSaved": "Settings saved.",
        "status.daemonOff": "D1–D4 keys turned off.",
        "status.daemonOn": "D1–D4 keys active.",
        "status.daemonStartFailed": "Could not start the daemon: %1$@",
        "status.dialImageSent": "Image sent to the dial.",
        "status.dialMode": "Dial: %1$@.",
        "status.displayLabel": "Display",
        "status.effectApplied": "%1$@ applied and saved in the profile.",
        "status.effectRunningKeyboard": "Effect “%1$@” is running on the keyboard.",
        "status.factoryIconRestored": "Factory icon restored on %1$@.",
        "status.frozen": "Frame frozen and saved to the keyboard's “Custom” slot.",
        "status.iconDrawFailed": "Could not draw the icon.",
        "status.iconSent": "Icon sent to %1$@ in %2$@ s.",
        "status.keyboardConnected": "Keyboard connected.",
        "status.keyboardGone": "Keyboard disconnected — the effect will resume when it is plugged back in.",
        "status.layoutAuto": "Layout: automatic detection.",
        "status.layoutForced": "Layout forced: %1$@.",
        "status.leftoversCleared": "Leftover actions erased from the keyboard's memory.",
        "status.loginApproval": "To be approved in System Settings → General → Login Items.",
        "status.previewOnly": "Keyboard not found — the preview is still available.",
        "status.profileActivated": "Profile “%1$@” activated.",
        "status.profileActivatedFrontApp": "Profile “%1$@” activated (app in front).",
        "status.profileFromKeyboard": "Profile “%1$@” active (chosen on the keyboard).",
        "status.profileRemoved": "Profile removed from the app (the keyboard keeps its settings in slot %1$@).",
        "status.ready": "Ready",
        "status.recovering": "Recovery",
        "status.recoverySent": "Recovery sequence sent.",
        "status.saving": "Saving",
        "status.sendingImage": "Sending the image…",
        "status.uploadBusy": "A transfer is running on %1$@ — wait a few seconds.",
        "status.uploadBusyAlready": "A transfer is already running on %1$@ — wait a few seconds.",
        "status.uploadFailed": "Transfer failed: %1$@",
        "status.uploadFailedKey": "%1$@: transfer failed — %2$@",
        "status.uploadStarted": "%1$@: sending the image to the keyboard…",

        // MARK: system
        "system.askAgain": "Ask again",
        "system.autoDaemon": "Turn on the D1–D4 keys automatically",
        "system.autoDaemonNote": "The daemon starts with the app, reconnects by itself when the keyboard is plugged back in, and restarts if it stops.",
        "system.autostartHint": "Automatic start at login: ./install-daemon.sh from your Terminal.",
        "system.background": "Everest works in the background, from the menu bar",
        "system.daemonSubtitle": "Runs the D1–D4 actions and pushes values to the dial",
        "system.daemonTitle": "Keys daemon",
        "system.keepRunning": "Keep Everest running when I close the window",
        "system.keepRunningNote": "The D1–D4 keys, profiles and effects keep working; the icon stays in the menu bar. To quit: icon menu or ⌘Q.",
        "system.keyboardCard": "Keyboard",
        "system.keyboardCardNote": "State reported by the firmware",
        "system.launchAtLogin": "Launch Everest at login",
        "system.launchAtLoginNote": "Starts quietly in the menu bar, without opening the window.",
        "system.launchedFrom": "Everest is running from %1$@. For a reliable start, copy it to /Applications (./make-app.sh --install): an external volume is not always mounted at login.",
        "system.lightProfile": "Light profile",
        "system.listening": "Listening",
        "system.metricsEvery": "The daemon sends the values every 0.5 s while it runs.",
        "system.modules": "Modules",
        "system.monitoring": "Monitoring",
        "system.monitoringNote": "System values shown on the dial",
        "system.noAccessibility": "Everest does not have the Accessibility permission",
        "system.noAccessibilityNote": "Without it, “shortcut” and “text” actions do nothing (app, command and link actions still work). If Everest is already ticked in the list, the entry is stale: select it, remove it with “−”, then add it again with “+” (Everest.app), and restart the daemon.",
        "system.openSettings": "Open Settings",
        "system.sendMetrics": "Send CPU, GPU, RAM, disk, network and volume",
        "system.stoppedState": "Stopped",
        "system.unlock": "Unblock the keyboard",
        "system.unlockNote": "“Unblock” sends the SDK reset if an image transfer was interrupted. If that is not enough, unplug and replug the keyboard: nothing is lost.",

        // MARK: upload
        "upload.phase.connect": "Connecting to the keyboard",
        "upload.phase.done": "Done",
        "upload.phase.finish": "Finishing",
        "upload.phase.prepare": "The keyboard is preparing the slot",
        "upload.phase.send": "Sending the image",

        "status.configReloaded": "Settings were changed outside the app and have been reloaded.",

        // MARK: pad
        "night.displays": "Also put the Mac's screens to sleep",
        "night.displaysNote": "Screens only, not the Mac. If macOS asks for the password when the display turns off (Lock Screen settings), the session is locked overnight.",
        "action.night": "Night mode",
        "night.note": "Turns the keyboard lights and the DisplayPad off and mutes the sound; press again to bring everything back as it was.",
        "night.active": "Night mode on",
        "action.profile": "Profile",
        "profileAction.next": "Next profile",
        "profileAction.previous": "Previous profile",
        "profiles.newCopyPad": "New, with the DisplayPad keys of « %1$@ »",
        "codexbar.ok": "CodexBar data: OK",
        "codexbar.denied": "Everest can't read CodexBar's data",
        "codexbar.deniedNote": "macOS protects other apps' data. Add Everest to Full Disk Access, then quit and reopen Everest.",
        "codexbar.openSettings": "Open settings",
        "live.week": "week",
        "keyappearance.liveCodexBar": "Claude and Codex show your usage limits as CodexBar last read them (it refreshes them every few minutes): one key for the 5-hour window, one for the week.",
        "pad.status.swapped": "%1$@ and %2$@ swapped.",
        "keyappearance.live": "Live",
        "keyappearance.liveAction": "Also open the matching app",
        "keyappearance.liveNote": "Redrawn whenever the value changes (at most once a second) while the pad is plugged in. The key keeps its action.",
        "pad.keysActive": "P1–P12 keys active",
        "pad.overview.keys": "%1$@ of 12 keys set",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "DisplayPad firmware %1$@ is not supported",
        "pad.unsupportedNote": "Everest only writes to firmware 8, the version it was tested with, and leaves this pad alone.",
        "pad.noAnswer": "DisplayPad not responding",
        "pad.noAnswerNote": "It is plugged in but does not answer: wait a few seconds, or plug it straight into the Mac.",
        "section.displaypad.subtitle": "Twelve screen keys, each with a picture and a macOS action",
        "pad.connected": "DisplayPad connected",
        "pad.connectedNote": "Pictures are sent within a second of any change; the pad keeps them until it is unplugged.",
        "pad.notConnected": "DisplayPad not connected",
        "pad.notConnectedNote": "Plug it straight into the Mac: on some USB hubs its screen stays black.",
        "pad.brightness": "Brightness",
        "pad.keys": "Keys",
        "pad.keysNote": "Click a key to edit it, or drag it onto another to swap them. Pictures and actions are saved in the profile « %1$@ ».",
        "pad.clearKey": "Clear",
        "pad.clearKeyHelp": "Removes the picture and the action of %1$@",
        "pad.noImage": "No picture",
        "pad.ownImageNote": "It is cropped to the centre and resized to 102 × 102. The key's action does not change.",
        "pad.daemonStoppedNote": "The DisplayPad keys only work while it is running.",
        "pad.status.sent": "%1$@: sent to the DisplayPad.",
        "pad.status.savedOffline": "%1$@: saved — shown when the DisplayPad is plugged in.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
