// Interface strings — es. Generated from the spec once, now edited by hand.
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let es: [String: String] = [
        // MARK: action
        "action.app": "Aplicación",
        "action.keypress": "Atajo",
        "action.none": "Ninguna",
        "action.open": "Archivo",
        "action.shell": "Comando",
        "action.text": "Texto",
        "action.textToType": "Texto que escribir",
        "action.url": "Enlace",

        // MARK: app
        "app.closeWindow": "Cerrar ventana",
        "app.copy": "Copiar",
        "app.cut": "Cortar",
        "app.edit": "Edición",
        "app.hide": "Ocultar Everest",
        "app.paste": "Pegar",
        "app.quit": "Salir de Everest",
        "app.selectAll": "Seleccionar todo",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "Las acciones de macOS y los atajos tecleados requieren el permiso de Accesibilidad (Ajustes → Privacidad y seguridad).",
        "buttons.actionRan": "Acción de %1$@ ejecutada.",
        "buttons.appHint": "Abre la app o la trae al frente",
        "buttons.clearLeftovers": "Borrar acciones residuales",
        "buttons.daemonStopped": "El daemon está detenido",
        "buttons.daemonStoppedNote": "Las acciones solo se ejecutan mientras escucha las teclas D1–D4.",
        "buttons.factoryValues": "Valores de fábrica",
        "buttons.factoryValuesHelp": "Restablece la imagen y la acción originales de %1$@",
        "buttons.flashMemory": "Memoria del teclado",
        "buttons.flashMemoryNote": "Base Camp puede dejar acciones en la memoria flash (p. ej. D4 enviando Esc)",
        "buttons.keyHeader": "TECLA %1$@",
        "buttons.noAction": "Sin acción: se ignora la tecla.",
        "buttons.noApp": "Ninguna app elegida",
        "buttons.pickPresetAppImage": "Preajuste, app o imagen para %1$@",
        "buttons.presetsAndIcon": "Preajustes e icono…",

        // MARK: clock
        "clock.analog": "Analógico",
        "clock.digital": "Digital",
        "clock.sync": "Sincronizar",

        // MARK: colormode
        "colormode.dual": "Dos colores",
        "colormode.quad": "4 colores",
        "colormode.rainbow": "Arcoíris",
        "colormode.single": "Un color",
        "colormode.withBackground": "Tecla + fondo",

        // MARK: common
        "common.active": "Activo",
        "common.add": "Nuevo",
        "common.choose": "Elegir…",
        "common.close": "Cerrar",
        "common.configure": "Configurar",
        "common.delete": "Eliminar",
        "common.edit": "Modificar",
        "common.name": "Nombre",
        "common.other": "Otra…",
        "common.refresh": "Actualizar",
        "common.remove": "Quitar",
        "common.start": "Iniciar",
        "common.stop": "Detener",
        "common.test": "Probar",

        // MARK: daemon
        "daemon.keysActive": "Teclas D1–D4 activas",
        "daemon.stopped": "Daemon detenido",

        // MARK: device
        "device.blocked": "Firmware no compatible",
        "device.connected": "Conectado",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Desconectado",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Everest Max completo",
        "device.keyboardMissing": "teclado no disponible",
        "device.keyboardUnavailable": "Teclado no disponible (no se encuentra o su firmware no es compatible).",
        "device.notConnected": "No conectado",
        "device.refresh.help": "Actualizar el estado del teclado",
        "device.withDock": "Teclado + dock multimedia",
        "device.withNumpad": "Teclado + teclado numérico",

        // MARK: displays
        "displays.change": "Cambiar…",
        "displays.chooseImage": "Elegir una imagen…",
        "displays.dial.subtitle": "Pantalla redonda de 240 × 204 del dock multimedia",
        "displays.display": "Visualización",
        "displays.factoryIcon": "Icono de fábrica",
        "displays.factoryLogo": "Logo de fábrica",
        "displays.imageCropped": "La imagen se recorta a 240 × 204.",
        "displays.imagesResized": "Las imágenes se redimensionan a 72 × 72.",
        "displays.keys.subtitle": "Cuatro pantallas de 72 × 72 sobre el teclado numérico",
        "displays.keys.title": "Teclas con pantalla",
        "displays.logoRestored": "Logo de Mountain restaurado en el dial.",
        "displays.metricsNote": "CPU, GPU, RAM, disco, red y volumen muestran los valores enviados por el daemon (página Sistema).",

        // MARK: factory
        "factory.activityMonitor": "Monitor de Actividad",
        "factory.sleep": "Suspender",

        // MARK: firmware
        "firmware.block.body": "Everest solo se ha probado con el firmware %1$@. Para no arriesgarse a inutilizar tu teclado, no le envía nada mientras no tenga esa versión: ni iluminación, ni imágenes, ni acciones.",
        "firmware.block.check": "Comprobar de nuevo",
        "firmware.block.detected": "Firmware detectado: %1$@",
        "firmware.block.how": "Mountain solo ofrece la actualización del firmware en su aplicación oficial Base Camp para Windows. Conecta el teclado a un PC con Windows, instala Base Camp, actualiza el firmware y vuelve a conectar el teclado a este Mac: Everest lo detecta solo.",
        "firmware.block.howTitle": "Cómo actualizar el teclado",
        "firmware.block.tested": "Firmware probado: %1$@",
        "firmware.block.title": "Firmware no compatible",
        "firmware.block.unreadableBody": "Everest no puede comprobar la versión del firmware del teclado, así que no lo toca. Desenchufa y vuelve a enchufar el teclado y vuelve a intentarlo.",
        "firmware.block.unreadableTitle": "Firmware ilegible",
        "firmware.block.why": "Everest no actualiza el firmware por sí mismo: es el mismo tipo de operación que puede inutilizar un teclado y no se puede probar aquí.",
        "firmware.status.unreadable": "El teclado no indicó su firmware: no se modifica.",
        "firmware.status.unsupported": "Firmware %1$@ no compatible (probado: %2$@): el teclado no se modifica.",

        // MARK: fx
        "fx.breathing": "Respiración",
        "fx.breathing.desc": "Pulso suave",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Gotas que caen",
        "fx.off": "Apagado",
        "fx.off.desc": "Todo apagado",
        "fx.reactive": "Reactivo",
        "fx.reactive.desc": "Se enciende al teclear",
        "fx.static": "Estático",
        "fx.static.desc": "Color fijo",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Gira alrededor del centro",
        "fx.wave": "Onda",
        "fx.wave.desc": "Recorre el teclado",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Onda desde la tecla",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Aplicar también la acción del preajuste",
        "keyappearance.appHint": "La tecla abre la app, o la trae al frente si ya está abierta.",
        "keyappearance.apps": "Aplicaciones",
        "keyappearance.background": "Continuar en segundo plano",
        "keyappearance.busyOther": "Hay un envío en curso en %1$@: espera a que termine para modificar esta tecla.",
        "keyappearance.chooseFile": "Elegir un archivo…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Abre la app",
        "keyappearance.ownImage": "Tu propia imagen",
        "keyappearance.ownImageNote": "Se recorta por el centro y se redimensiona a 72 × 72. La acción de la tecla no cambia.",
        "keyappearance.presets": "Preajustes",
        "keyappearance.searchApp": "Buscar una app",
        "keyappearance.step.prepare": "Preparación",
        "keyappearance.step.send": "Envío",
        "keyappearance.subtitle": "Elige lo que muestra la pantalla y lo que hace la tecla",
        "keyappearance.title": "Tecla %1$@",
        "keyappearance.transferNote": "Un envío tarda unos 20 segundos: el teclado prepara la ranura (borra él mismo la imagen anterior) y luego recibe la nueva en paquetes de 64 bytes. No desenchufes el teclado.",

        // MARK: keyboard
        "keyboard.activeBadge": "ACTIVA",
        "keyboard.ansiShape": "Forma ANSI: Intro ancha, \\ al final de la fila superior",
        "keyboard.asPrinted": "como está impreso",
        "keyboard.automatic": "Automático",
        "keyboard.chosen": "ELEGIDA A MANO",
        "keyboard.clearRemaps": "Borrar remapeos",
        "keyboard.detected": "DETECTADA",
        "keyboard.hidutilNote": "hidutil: uso 0x64 → 0x31. Dura hasta el reinicio. Para un remapeo guardado en el teclado: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "tecla ISO",
        "keyboard.isoMuteNote": "Si macOS trata el teclado como ANSI, la tecla a la izquierda de Z no produce nada",
        "keyboard.isoMuteTitle": "¿La tecla ISO no responde?",
        "keyboard.isoShape": "Forma ISO: Intro alta, tecla extra a la izquierda de W/Z",
        "keyboard.legend.at": "@ en la tecla '",
        "keyboard.legend.backslash": "\\ | a la izquierda de Z",
        "keyboard.legend.quote": "\" en ⇧2",
        "keyboard.legend.rightOfSemicolon": "a la derecha de ;",
        "keyboard.macLayout": "Distribución de macOS",
        "keyboard.macLayoutNote": "Para que macOS escriba lo que está impreso en las teclas",
        "keyboard.noMacLayout": "No hay instalada ninguna distribución de macOS que corresponda a «%1$@»: añádela en Ajustes del Sistema → Teclado → Fuentes de entrada.",
        "keyboard.remapApplied": "Remapeo ISO aplicado (hasta el reinicio).",
        "keyboard.remapIso": "Remapear la tecla ISO",
        "keyboard.remapsCleared": "Remapeos de hidutil borrados.",
        "keyboard.reportsLayout": "El teclado indica «%1$@». Vuelve a automático si esta elección ya no es necesaria.",
        "keyboard.switchedTo": "Distribución cambiada a %1$@.",
        "keyboard.title": "Teclado físico",
        "keyboard.titleNote": "Leído del teclado, como Base Camp: el dibujo, las teclas y los efectos se adaptan a él",
        "keyboard.unknown": "desconocida",
        "keyboard.use": "Usar %1$@",
        "keyboard.verifiedNote1": "La forma y la iluminación de cada tecla siguen la cuadrícula del teclado; solo la distribución UK se ha verificado en un teclado real.",
        "keyboard.verifiedNote2": "Las leyendas vienen de las tablas de Base Camp y la forma sigue la cuadrícula de LED; solo la distribución UK se ha verificado en un teclado real.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "la transferencia al dial se interrumpió: usa «Desbloquear el teclado» (página Sistema) o vuelve a conectarlo",
        "keyboardError.dialRefused": "el dial rechazó el envío (no se escribió nada)",
        "keyboardError.interrupted": "transferencia interrumpida: usa «Desbloquear el teclado» (página Sistema) o vuelve a conectarlo",
        "keyboardError.refused": "el teclado rechazó el envío (no se escribió nada): vuelve a intentarlo; si persiste, usa «Desbloquear el teclado» (página Sistema)",
        "keyboardError.selectTarget": "el teclado no responde a la selección de teclas: usa «Desbloquear el teclado» (página Sistema) o vuelve a conectarlo",

        // MARK: layout
        "layout.french": "Francés (AZERTY)",
        "layout.german": "Alemán (QWERTZ)",
        "layout.hebrew": "Hebreo",
        "layout.italian": "Italiano",
        "layout.korean": "Coreano",
        "layout.nordic": "Nórdico",
        "layout.portuguese": "Portugués",
        "layout.spanish": "Español",
        "layout.uk": "Reino Unido (ISO)",
        "layout.us": "EE. UU. (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Añadir un color",
        "lighting.allHues": "Todos los tonos, generados por el teclado.",
        "lighting.backgroundColour": "Fondo",
        "lighting.brightness": "Brillo",
        "lighting.byKeyboard": "Lo ejecuta el teclado: continúa sin la app",
        "lighting.byMac": "Lo calcula el Mac: mantén la app abierta",
        "lighting.clearAll": "Borrar todo",
        "lighting.clockwise": "Horario",
        "lighting.colors": "Colores",
        "lighting.colour": "Color",
        "lighting.colour1": "Color 1",
        "lighting.colour2": "Color 2",
        "lighting.colourCount.one": "%1$@ color",
        "lighting.colourCount.other": "%1$@ colores",
        "lighting.counterclockwise": "Antihorario",
        "lighting.direction": "Dirección",
        "lighting.editEllipsis": "Modificar…",
        "lighting.fast": "Rápido",
        "lighting.flameNote": "Rampa de llama fija, de la brasa al blanco.",
        "lighting.freeze": "Fijar en el teclado",
        "lighting.freezeNote": "Envía el fotograma actual a la ranura Custom y lo guarda: se mantiene sin la app.",
        "lighting.keyColour": "Tecla",
        "lighting.ledsBlack": "Todos los LED están negros mientras el efecto se ejecuta.",
        "lighting.macNote": "Renderizados tecla por tecla a 30 fotogramas/s, con tu paleta",
        "lighting.normal": "Normal",
        "lighting.offNote": "La retroiluminación y las bandas laterales están apagadas. Elige otro efecto para volver a encenderlas.",
        "lighting.officialEffects": "Efectos oficiales",
        "lighting.officialNote": "Los efectos de Base Camp, enviados exactamente igual que la app de Windows",
        "lighting.paintHint": "Haz clic o arrastra sobre las teclas del teclado de arriba.",
        "lighting.paintKeys": "Pintar tecla por tecla",
        "lighting.palette": "Paleta",
        "lighting.paused": "En pausa",
        "lighting.reapply": "Volver a aplicar",
        "lighting.rightClickHint": "Clic derecho en una muestra para eliminarla.",
        "lighting.rotation": "Sentido de giro",
        "lighting.runningOnKeyboard": "En curso en el teclado",
        "lighting.savedInProfile": "Guardado en el perfil activo del teclado",
        "lighting.slow": "Lento",
        "lighting.speed": "Velocidad",
        "lighting.title": "Iluminación",

        // MARK: live
        "live.keyboard": "Teclado · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · en pausa",
        "live.pause": "Pausa",
        "live.start": "Iniciar",

        // MARK: macfx
        "macfx.aurora": "Aurora",
        "macfx.equalizer": "Ecualizador",
        "macfx.fire": "Fuego",
        "macfx.gradient": "Degradado",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Lluvia digital",
        "macfx.ripples": "Ondas",
        "macfx.scanner": "Escáner",
        "macfx.solid": "Color liso",
        "macfx.spectrum": "Espectro",
        "macfx.spiral": "Espiral",
        "macfx.stars": "Estrellas",
        "macfx.waves": "Olas",

        // MARK: menu
        "menu.allowAccessibility": "Permitir accesibilidad…",
        "menu.disconnected": "Teclado desconectado",
        "menu.firmwareBlocked": "Firmware no compatible: teclado ignorado",
        "menu.keyboardEffects": "Efectos del teclado",
        "menu.launchAtLogin": "Abrir al iniciar sesión",
        "menu.macEffects": "Efectos del Mac",
        "menu.manageProfiles": "Gestionar perfiles…",
        "menu.newProfile": "Nuevo perfil",
        "menu.open": "Abrir Everest…",
        "menu.pauseEffect": "Pausar el efecto",
        "menu.profile": "Perfil: %1$@",
        "menu.resumeEffect": "Reanudar el efecto",

        // MARK: metric
        "metric.disk": "DISCO",
        "metric.network": "RED",
        "metric.volume": "VOLUMEN",

        // MARK: mode
        "mode.clock": "Reloj",
        "mode.disk": "Disco",
        "mode.image": "Imagen",
        "mode.network": "Red",
        "mode.volume": "Volumen",

        // MARK: overview
        "overview.actionsActive": "Acciones activas",
        "overview.changeLighting": "Cambiar la iluminación",
        "overview.dialSubtitle": "Pantalla redonda del dock multimedia",
        "overview.keyboardEffect": "Efecto del teclado",
        "overview.macEffect": "Efecto calculado por el Mac",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Brasa",
        "palette.forest": "Bosque",
        "palette.ice": "Hielo",
        "palette.neon": "Neón",
        "palette.ocean": "Océano",
        "palette.sunset": "Atardecer",
        "palette.vapor": "Vapor",

        // MARK: preset
        "preset.bolt": "Rayo",
        "preset.calendar": "Calendario",
        "preset.captureScreen": "Captura de pantalla",
        "preset.captureZone": "Captura de zona",
        "preset.category.apps": "Apps",
        "preset.category.decor": "Solo icono",
        "preset.category.media": "Multimedia",
        "preset.coffee": "Café",
        "preset.flame": "Llama",
        "preset.game": "Mando",
        "preset.heart": "Corazón",
        "preset.home": "Casa",
        "preset.lock": "Bloquear",
        "preset.music": "Música",
        "preset.mute": "Silenciar",
        "preset.next": "Siguiente",
        "preset.playpause": "Reproducir / Pausa",
        "preset.previous": "Anterior",
        "preset.sleepDisplay": "Apagar la pantalla",
        "preset.star": "Estrella",
        "preset.volumeDown": "Volumen −",
        "preset.volumeUp": "Volumen +",

        // MARK: profile
        "profile.defaultName": "Perfil %1$@",
        "profile.main": "Principal",

        // MARK: profiles
        "profiles.addApp": "Añadir una app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Cambio automático",
        "profiles.autoSwitchHint": "Funciona mientras la app está abierta o el daemon se está ejecutando. Un perfil elegido a mano en el dial no se sustituye mientras permanezcas en una app sin perfil.",
        "profiles.autoSwitchNote": "El teclado cambia al perfil de una app cuando está en primer plano",
        "profiles.deleteHelp": "Eliminar este perfil de la app",
        "profiles.dialMode": "Dial: %1$@",
        "profiles.dialOnActivate": "Dial al activar",
        "profiles.dialUnchanged": "Dial sin cambios",
        "profiles.dontChange": "No cambiar",
        "profiles.enable": "Activar",
        "profiles.freeSlots": "%1$@ ranura(s) libre(s)",
        "profiles.hardwareNote": "El teclado guarda cinco perfiles en memoria (menú Profile del dial). Cada uno tiene su iluminación, sus remapeos y sus imágenes D1–D4; la app añade las acciones de las teclas, el modo del dial y las apps vinculadas.",
        "profiles.header": "PERFIL %1$@",
        "profiles.iconAndColour": "Icono y color",
        "profiles.keyboardLighting": "Iluminación del teclado",
        "profiles.keyboardProfiles": "PERFILES DEL TECLADO",
        "profiles.keysNote": "Las teclas D1–D4 y la iluminación se ajustan en sus páginas mientras este perfil está activo: se guardan en este perfil.",
        "profiles.lightingFirmware": "Iluminación: %1$@",
        "profiles.lightingMac": "Iluminación del Mac: %1$@",
        "profiles.linkedApps": "Apps vinculadas",
        "profiles.manage": "Gestionar…",
        "profiles.namePlaceholder": "Programación, Música…",
        "profiles.noLinkedApp": "Ninguna app vinculada",
        "profiles.otherwise": "Si no, volver a",
        "profiles.slot": "Ranura %1$@",
        "profiles.slotOfKeyboard": "Ranura %1$@ del teclado",

        // MARK: reset
        "reset.title": "Restablecimiento",

        // MARK: section
        "section.buttons.subtitle": "Una acción de macOS en cada una de las cuatro teclas con pantalla",
        "section.buttons.title": "Teclas D1–D4",
        "section.displays.subtitle": "Pantalla redonda del dial y teclas con pantalla del teclado numérico",
        "section.displays.title": "Pantallas",
        "section.keyboard.subtitle": "Distribución del teclado detectada y la distribución de macOS correspondiente",
        "section.keyboard.title": "Distribución",
        "section.lighting.subtitle": "Efectos oficiales del teclado y efectos dinámicos calculados por el Mac",
        "section.overview.subtitle": "Tu Everest Max de un vistazo",
        "section.overview.title": "Resumen",
        "section.profiles.subtitle": "Cinco perfiles en el teclado, cada uno con sus teclas, su iluminación y sus apps",
        "section.profiles.title": "Perfiles",
        "section.system.subtitle": "Daemon de los botones, monitorización y solución de problemas",
        "section.system.title": "Sistema",

        // MARK: settings
        "settings.language.automatic": "Automático (idioma del sistema)",
        "settings.language.note": "Idioma de la interfaz, del menú de la barra de menús y de los mensajes.",
        "settings.language.title": "Idioma",

        // MARK: status
        "status.animationPaused": "Animación en pausa: el teclado conserva el último fotograma.",
        "status.appIconUnreadable": "No se pudo leer el icono de la app.",
        "status.appNoId": "Esta app no tiene identificador: no se puede vincular.",
        "status.changeFailed": "No se pudo modificar: %1$@",
        "status.cleaning": "Limpieza",
        "status.clockSynced": "Reloj sincronizado con el Mac.",
        "status.configSaved": "Configuración guardada.",
        "status.daemonOff": "Teclas D1–D4 desactivadas.",
        "status.daemonOn": "Teclas D1–D4 activas.",
        "status.daemonStartFailed": "No se pudo iniciar el daemon: %1$@",
        "status.dialImageSent": "Imagen enviada al dial.",
        "status.dialMode": "Dial: %1$@.",
        "status.displayLabel": "Pantalla",
        "status.effectApplied": "%1$@ aplicado y guardado en el perfil.",
        "status.effectRunningKeyboard": "Efecto «%1$@» en curso en el teclado.",
        "status.factoryIconRestored": "Icono de fábrica restaurado en %1$@.",
        "status.frozen": "Imagen fijada y guardada en la ranura «Custom» del teclado.",
        "status.iconDrawFailed": "No se pudo dibujar el icono.",
        "status.iconSent": "Icono enviado a %1$@ en %2$@ s.",
        "status.keyboardConnected": "Teclado conectado.",
        "status.keyboardGone": "Teclado desconectado: el efecto se reanudará al volver a conectarlo.",
        "status.layoutAuto": "Distribución: detección automática.",
        "status.layoutForced": "Distribución forzada: %1$@.",
        "status.leftoversCleared": "Acciones residuales borradas de la memoria del teclado.",
        "status.loginApproval": "Debes autorizarlo en Ajustes del Sistema → General → Ítems de inicio.",
        "status.previewOnly": "Teclado no encontrado: la vista previa sigue disponible.",
        "status.profileActivated": "Perfil «%1$@» activado.",
        "status.profileActivatedFrontApp": "Perfil «%1$@» activado (app en primer plano).",
        "status.profileFromKeyboard": "Perfil «%1$@» activo (elegido en el teclado).",
        "status.profileRemoved": "Perfil eliminado de la app (el teclado conserva sus ajustes en la ranura %1$@).",
        "status.ready": "Listo",
        "status.recovering": "Recuperación",
        "status.recoverySent": "Secuencia de recuperación enviada.",
        "status.saving": "Guardando",
        "status.sendingImage": "Enviando la imagen…",
        "status.uploadBusy": "Hay un envío en curso en %1$@: espera unos segundos.",
        "status.uploadBusyAlready": "Ya hay un envío en curso en %1$@: espera unos segundos.",
        "status.uploadFailed": "Error al enviar: %1$@",
        "status.uploadFailedKey": "%1$@: error al enviar — %2$@",
        "status.uploadStarted": "%1$@: enviando la imagen al teclado…",

        // MARK: system
        "system.askAgain": "Volver a pedir",
        "system.autoDaemon": "Activar las teclas D1–D4 automáticamente",
        "system.autoDaemonNote": "El daemon arranca con la app, se reconecta solo cuando se vuelve a enchufar el teclado y se reinicia si se detiene.",
        "system.autostartHint": "Inicio automático al iniciar sesión: ./install-daemon.sh desde tu Terminal.",
        "system.background": "Everest trabaja en segundo plano, desde la barra de menús",
        "system.daemonSubtitle": "Ejecuta las acciones de D1–D4 y envía valores al dial",
        "system.daemonTitle": "Daemon de las teclas",
        "system.keepRunning": "Mantener Everest activo al cerrar la ventana",
        "system.keepRunningNote": "Las teclas D1–D4, los perfiles y los efectos siguen funcionando; el icono permanece en la barra de menús. Salir: menú del icono o ⌘Q.",
        "system.keyboardCard": "Teclado",
        "system.keyboardCardNote": "Estado informado por el firmware",
        "system.launchAtLogin": "Abrir Everest al iniciar sesión",
        "system.launchAtLoginNote": "Se inicia discretamente en la barra de menús, sin abrir la ventana.",
        "system.launchedFrom": "Everest se ejecuta desde %1$@. Para un inicio fiable, cópialo en /Applications (./make-app.sh --install): un volumen externo no siempre está montado al iniciar sesión.",
        "system.lightProfile": "Perfil de luz",
        "system.listening": "Escuchando",
        "system.metricsEvery": "El daemon envía los valores cada 0,5 s mientras se ejecuta.",
        "system.modules": "Módulos",
        "system.monitoring": "Monitorización",
        "system.monitoringNote": "Valores del sistema mostrados en el dial",
        "system.noAccessibility": "Everest no tiene el permiso de Accesibilidad",
        "system.noAccessibilityNote": "Sin él, las acciones «atajo» y «texto» no hacen nada (las de app, comando y enlace sí funcionan). Si Everest ya está marcado en la lista, la entrada está obsoleta: selecciónala, quítala con «−», vuelve a añadirla con «+» (Everest.app) y reinicia el daemon.",
        "system.openSettings": "Abrir ajustes",
        "system.sendMetrics": "Enviar CPU, GPU, RAM, disco, red y volumen",
        "system.stoppedState": "Detenido",
        "system.unlock": "Desbloquear el teclado",
        "system.unlockNote": "«Desbloquear» envía el restablecimiento del SDK si se interrumpió una transferencia de imagen. Si no basta, desenchufa y vuelve a enchufar el teclado: no se pierde nada.",

        // MARK: upload
        "upload.phase.connect": "Conectando con el teclado",
        "upload.phase.done": "Terminado",
        "upload.phase.finish": "Finalizando",
        "upload.phase.prepare": "El teclado prepara la ranura",
        "upload.phase.send": "Enviando la imagen",

        // MARK: pad
        "pad.keysActive": "Teclas P1–P12 activas",
        "pad.overview.keys": "%1$@ de 12 teclas configuradas",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "El firmware %1$@ del DisplayPad no es compatible",
        "pad.unsupportedNote": "Everest solo escribe en el firmware 8, la versión probada, y deja este pad en paz.",
        "pad.noAnswer": "El DisplayPad no responde",
        "pad.noAnswerNote": "Está conectado pero no responde: espera unos segundos o conéctalo directamente al Mac.",
        "section.displaypad.subtitle": "Doce teclas con pantalla, cada una con una imagen y una acción de macOS",
        "pad.connected": "DisplayPad conectado",
        "pad.connectedNote": "Las imágenes se envían en menos de un segundo tras cada cambio; el pad las conserva hasta que se desconecta.",
        "pad.notConnected": "DisplayPad no conectado",
        "pad.notConnectedNote": "Conéctalo directamente al Mac: con algunos hubs USB su pantalla se queda negra.",
        "pad.brightness": "Brillo",
        "pad.keys": "Teclas",
        "pad.keysNote": "Haz clic en una tecla para editarla. Imágenes y acciones se guardan en el perfil «%1$@».",
        "pad.clearKey": "Borrar",
        "pad.clearKeyHelp": "Quita la imagen y la acción de %1$@",
        "pad.noImage": "Sin imagen",
        "pad.ownImageNote": "Se recorta al centro y se redimensiona a 102 × 102. La acción de la tecla no cambia.",
        "pad.daemonStoppedNote": "Las teclas del DisplayPad solo funcionan mientras está en marcha.",
        "pad.status.sent": "%1$@: enviado al DisplayPad.",
        "pad.status.savedOffline": "%1$@: guardado — se mostrará cuando el DisplayPad esté conectado.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
