// Interface strings — sv. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let sv: [String: String] = [
        // MARK: action
        "action.app": "App",
        "action.keypress": "Kortkommando",
        "action.none": "Ingen",
        "action.open": "Fil",
        "action.shell": "Kommando",
        "action.text": "Text",
        "action.textToType": "Text att skriva",
        "action.url": "Länk",

        // MARK: app
        "app.closeWindow": "Stäng fönster",
        "app.copy": "Kopiera",
        "app.cut": "Klipp ut",
        "app.edit": "Redigera",
        "app.hide": "Dölj Everest",
        "app.paste": "Klistra in",
        "app.quit": "Avsluta Everest",
        "app.selectAll": "Markera allt",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS-åtgärder och skrivna kortkommandon kräver behörigheten Hjälpmedel (Inställningar → Integritet och säkerhet).",
        "buttons.actionRan": "Åtgärden för %1$@ kördes.",
        "buttons.appHint": "Öppnar appen eller tar fram den",
        "buttons.clearLeftovers": "Rensa kvarglömda åtgärder",
        "buttons.daemonStopped": "Daemonen är stoppad",
        "buttons.daemonStoppedNote": "Åtgärder körs bara medan den lyssnar på tangenterna D1–D4.",
        "buttons.factoryValues": "Fabriksinställningar",
        "buttons.factoryValuesHelp": "Återställer ursprunglig bild och åtgärd för %1$@",
        "buttons.flashMemory": "Tangentbordets minne",
        "buttons.flashMemoryNote": "Base Camp kan lämna åtgärder i flashminnet (t.ex. D4 som skickar Esc)",
        "buttons.keyHeader": "TANGENT %1$@",
        "buttons.noAction": "Ingen åtgärd — tangenten ignoreras.",
        "buttons.noApp": "Ingen app vald",
        "buttons.pickPresetAppImage": "Förinställning, app eller bild för %1$@",
        "buttons.presetsAndIcon": "Förinställningar och ikon…",

        // MARK: clock
        "clock.analog": "Analog",
        "clock.digital": "Digital",
        "clock.sync": "Synkronisera",

        // MARK: colormode
        "colormode.dual": "Två färger",
        "colormode.quad": "4 färger",
        "colormode.rainbow": "Regnbåge",
        "colormode.single": "En färg",
        "colormode.withBackground": "Tangent + bakgrund",

        // MARK: common
        "common.active": "Aktiv",
        "common.add": "Ny",
        "common.choose": "Välj…",
        "common.close": "Stäng",
        "common.configure": "Konfigurera",
        "common.delete": "Ta bort",
        "common.edit": "Redigera",
        "common.name": "Namn",
        "common.other": "Annan…",
        "common.refresh": "Uppdatera",
        "common.remove": "Ta bort",
        "common.start": "Starta",
        "common.stop": "Stoppa",
        "common.test": "Testa",

        // MARK: daemon
        "daemon.keysActive": "Tangenterna D1–D4 aktiva",
        "daemon.stopped": "Daemon stoppad",

        // MARK: device
        "device.blocked": "Firmware stöds inte",
        "device.connected": "Ansluten",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Frånkopplad",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Komplett Everest Max",
        "device.keyboardMissing": "tangentbordet är inte tillgängligt",
        "device.keyboardUnavailable": "Tangentbordet är inte tillgängligt (hittades inte, eller firmware som inte stöds).",
        "device.notConnected": "Inte ansluten",
        "device.refresh.help": "Uppdatera tangentbordets status",
        "device.withDock": "Tangentbord + mediadocka",
        "device.withNumpad": "Tangentbord + numeriskt tangentbord",

        // MARK: displays
        "displays.change": "Ändra…",
        "displays.chooseImage": "Välj en bild…",
        "displays.dial.subtitle": "Rund 240 × 204-skärm på mediadockan",
        "displays.display": "Visning",
        "displays.factoryIcon": "Fabriksikon",
        "displays.factoryLogo": "Fabrikslogotyp",
        "displays.imageCropped": "Bilden beskärs till 240 × 204.",
        "displays.imagesResized": "Bilder skalas om till 72 × 72.",
        "displays.keys.subtitle": "Fyra 72 × 72-skärmar ovanför det numeriska tangentbordet",
        "displays.keys.title": "Skärmtangenter",
        "displays.logoRestored": "Mountain-logotypen har återställts på ratten.",
        "displays.metricsNote": "CPU, GPU, RAM, disk, nätverk och volym visar värdena som daemonen skickar (sidan System).",

        // MARK: factory
        "factory.activityMonitor": "Aktivitetskontroll",
        "factory.sleep": "Vila",

        // MARK: firmware
        "firmware.block.body": "Everest har bara testats med firmware %1$@. För att undvika all risk att göra tangentbordet obrukbart skickar det ingenting till det förrän det kör den versionen: ingen belysning, inga bilder, inga åtgärder.",
        "firmware.block.check": "Kontrollera igen",
        "firmware.block.detected": "Upptäckt firmware: %1$@",
        "firmware.block.how": "Mountain erbjuder bara firmwareuppdateringen i sin officiella Base Camp-app för Windows. Anslut tangentbordet till en Windows-dator, installera Base Camp, uppdatera firmware och anslut sedan tangentbordet till den här Macen igen: Everest upptäcker det själv.",
        "firmware.block.howTitle": "Så uppdaterar du tangentbordet",
        "firmware.block.tested": "Testad firmware: %1$@",
        "firmware.block.title": "Firmware stöds inte",
        "firmware.block.unreadableBody": "Everest kan inte kontrollera tangentbordets firmwareversion och rör det därför inte. Koppla från och anslut tangentbordet igen och försök sedan på nytt.",
        "firmware.block.unreadableTitle": "Firmware kan inte läsas",
        "firmware.block.why": "Everest uppdaterar inte firmware själv: det är samma typ av åtgärd som kan göra ett tangentbord obrukbart, och den går inte att testa här.",
        "firmware.status.unreadable": "Tangentbordet rapporterade ingen firmware — det lämnas orört.",
        "firmware.status.unsupported": "Firmware %1$@ stöds inte (testad: %2$@) — tangentbordet lämnas orört.",

        // MARK: fx
        "fx.breathing": "Andning",
        "fx.breathing.desc": "Mjuk pulsering",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Fallande droppar",
        "fx.off": "Av",
        "fx.off.desc": "Allt är av",
        "fx.reactive": "Reaktiv",
        "fx.reactive.desc": "Tänds när du skriver",
        "fx.static": "Statisk",
        "fx.static.desc": "Fast färg",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Snurrar runt mitten",
        "fx.wave": "Våg",
        "fx.wave.desc": "Svepar över tangentbordet",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Krusning från tangenten",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Använd även förinställningens åtgärd",
        "keyappearance.appHint": "Tangenten öppnar appen, eller tar fram den om den redan är öppen.",
        "keyappearance.apps": "Appar",
        "keyappearance.background": "Fortsätt i bakgrunden",
        "keyappearance.busyOther": "En överföring pågår på %1$@ — vänta tills den är klar innan du ändrar den här tangenten.",
        "keyappearance.chooseFile": "Välj en fil…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Öppnar appen",
        "keyappearance.ownImage": "Din egen bild",
        "keyappearance.ownImageNote": "Den beskärs mitt i och skalas om till 72 × 72. Tangentens åtgärd ändras inte.",
        "keyappearance.presets": "Förinställningar",
        "keyappearance.searchApp": "Sök efter en app",
        "keyappearance.step.prepare": "Förbereder",
        "keyappearance.step.send": "Skickar",
        "keyappearance.subtitle": "Välj vad skärmen visar och vad tangenten gör",
        "keyappearance.title": "Tangent %1$@",
        "keyappearance.transferNote": "En överföring tar cirka 20 sekunder: tangentbordet förbereder platsen (det raderar själv den gamla bilden) och tar sedan emot den nya i paket om 64 byte. Koppla inte från tangentbordet.",

        // MARK: keyboard
        "keyboard.activeBadge": "AKTIV",
        "keyboard.ansiShape": "ANSI-form: bred Enter, \\ i slutet av översta raden",
        "keyboard.asPrinted": "som tryckt",
        "keyboard.automatic": "Automatisk",
        "keyboard.chosen": "VALD FÖR HAND",
        "keyboard.clearRemaps": "Rensa omkopplingar",
        "keyboard.detected": "UPPTÄCKT",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. Gäller till omstart. För en omkoppling som lagras i tangentbordet: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO-tangent",
        "keyboard.isoMuteNote": "Om macOS behandlar tangentbordet som ANSI gör tangenten till vänster om Z ingenting",
        "keyboard.isoMuteTitle": "Svarar inte ISO-tangenten?",
        "keyboard.isoShape": "ISO-form: hög Enter, extra tangent till vänster om Z",
        "keyboard.legend.at": "@ på tangenten '",
        "keyboard.legend.backslash": "\\ | till vänster om Z",
        "keyboard.legend.quote": "\" på ⇧2",
        "keyboard.legend.rightOfSemicolon": "till höger om ;",
        "keyboard.macLayout": "macOS-tangentbordslayout",
        "keyboard.macLayoutNote": "Så att macOS skriver det som är tryckt på tangenterna",
        "keyboard.noMacLayout": "Ingen macOS-layout som motsvarar ”%1$@” är installerad: lägg till den i Systeminställningar → Tangentbord → Inmatningskällor.",
        "keyboard.remapApplied": "ISO-omkoppling tillämpad (till omstart).",
        "keyboard.remapIso": "Koppla om ISO-tangenten",
        "keyboard.remapsCleared": "hidutil-omkopplingar rensade.",
        "keyboard.reportsLayout": "Tangentbordet anger ”%1$@”. Gå tillbaka till automatisk om valet inte längre behövs.",
        "keyboard.switchedTo": "Layouten ändrades till %1$@.",
        "keyboard.title": "Fysiskt tangentbord",
        "keyboard.titleNote": "Läses från tangentbordet, som i Base Camp: ritningen, tangenterna och effekterna anpassas efter det",
        "keyboard.unknown": "okänd",
        "keyboard.use": "Använd %1$@",
        "keyboard.verifiedNote1": "Varje tangents form och belysning följer tangentbordets rutnät; bara UK-layouten har verifierats på ett riktigt tangentbord.",
        "keyboard.verifiedNote2": "Tangenttexterna kommer från Base Camps tabeller och formen följer LED-rutnätet; bara UK-layouten har verifierats på ett riktigt tangentbord.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "överföringen till ratten avbröts — använd ”Lås upp tangentbordet” (sidan System) eller anslut det igen",
        "keyboardError.dialRefused": "ratten avvisade överföringen (inget skrevs)",
        "keyboardError.interrupted": "överföringen avbröts — använd ”Lås upp tangentbordet” (sidan System) eller anslut det igen",
        "keyboardError.refused": "tangentbordet avvisade överföringen (inget skrevs) — försök igen; om det fortsätter, använd ”Lås upp tangentbordet” (sidan System)",
        "keyboardError.selectTarget": "tangentbordet svarar inte på tangentvalet — använd ”Lås upp tangentbordet” (sidan System) eller anslut det igen",

        // MARK: layout
        "layout.french": "Franska (AZERTY)",
        "layout.german": "Tyska (QWERTZ)",
        "layout.hebrew": "Hebreiska",
        "layout.italian": "Italienska",
        "layout.korean": "Koreanska",
        "layout.nordic": "Nordisk",
        "layout.portuguese": "Portugisiska",
        "layout.spanish": "Spanska",
        "layout.uk": "Storbritannien (ISO)",
        "layout.us": "USA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Lägg till en färg",
        "lighting.allHues": "Alla nyanser, genererade av tangentbordet.",
        "lighting.backgroundColour": "Bakgrund",
        "lighting.brightness": "Ljusstyrka",
        "lighting.byKeyboard": "Körs av tangentbordet — fortsätter utan appen",
        "lighting.byMac": "Beräknas av Macen — håll appen öppen",
        "lighting.clearAll": "Rensa allt",
        "lighting.clockwise": "Medurs",
        "lighting.colors": "Färger",
        "lighting.colour": "Färg",
        "lighting.colour1": "Färg 1",
        "lighting.colour2": "Färg 2",
        "lighting.colourCount.one": "%1$@ färg",
        "lighting.colourCount.other": "%1$@ färger",
        "lighting.counterclockwise": "Moturs",
        "lighting.direction": "Riktning",
        "lighting.editEllipsis": "Redigera…",
        "lighting.fast": "Snabb",
        "lighting.flameNote": "Fast lågskala, från glöd till vitt.",
        "lighting.freeze": "Lås i tangentbordet",
        "lighting.freezeNote": "Skickar aktuell bild till Custom-platsen och sparar den: den finns kvar utan appen.",
        "lighting.keyColour": "Tangent",
        "lighting.ledsBlack": "Alla lysdioder är svarta medan effekten körs.",
        "lighting.macNote": "Beräknas tangent för tangent med 30 bilder/s, med din palett",
        "lighting.normal": "Normal",
        "lighting.offNote": "Bakgrundsbelysningen och sidolisterna är av. Välj en annan effekt för att tända dem igen.",
        "lighting.officialEffects": "Officiella effekter",
        "lighting.officialNote": "Base Camps effekter, skickade precis som Windows-appen gör",
        "lighting.paintHint": "Klicka eller dra över tangenterna på tangentbordet ovan.",
        "lighting.paintKeys": "Måla tangent för tangent",
        "lighting.palette": "Palette",
        "lighting.paused": "Pausad",
        "lighting.reapply": "Använd igen",
        "lighting.rightClickHint": "Högerklicka på en färgruta för att ta bort den.",
        "lighting.rotation": "Rotationsriktning",
        "lighting.runningOnKeyboard": "Körs på tangentbordet",
        "lighting.savedInProfile": "Sparad i tangentbordets aktiva profil",
        "lighting.slow": "Långsam",
        "lighting.speed": "Hastighet",
        "lighting.title": "Belysning",

        // MARK: live
        "live.keyboard": "Tangentbord · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · pausad",
        "live.pause": "Paus",
        "live.start": "Starta",

        // MARK: macfx
        "macfx.aurora": "Norrsken",
        "macfx.equalizer": "Equalizer",
        "macfx.fire": "Eld",
        "macfx.gradient": "Toning",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Digitalt regn",
        "macfx.ripples": "Krusningar",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Enfärgad",
        "macfx.spectrum": "Spektrum",
        "macfx.spiral": "Spiral",
        "macfx.stars": "Stjärnor",
        "macfx.waves": "Vågor",

        // MARK: menu
        "menu.allowAccessibility": "Tillåt Hjälpmedel…",
        "menu.disconnected": "Tangentbordet är frånkopplat",
        "menu.firmwareBlocked": "Firmware stöds inte — tangentbordet lämnas orört",
        "menu.keyboardEffects": "Tangentbordseffekter",
        "menu.launchAtLogin": "Starta vid inloggning",
        "menu.macEffects": "Mac-effekter",
        "menu.manageProfiles": "Hantera profiler…",
        "menu.newProfile": "Ny profil",
        "menu.open": "Öppna Everest…",
        "menu.pauseEffect": "Pausa effekten",
        "menu.profile": "Profil: %1$@",
        "menu.resumeEffect": "Återuppta effekten",

        // MARK: metric
        "metric.disk": "DISK",
        "metric.network": "NÄTVERK",
        "metric.volume": "VOLYM",

        // MARK: mode
        "mode.clock": "Klocka",
        "mode.disk": "Disk",
        "mode.image": "Bild",
        "mode.network": "Nätverk",
        "mode.volume": "Volym",

        // MARK: overview
        "overview.actionsActive": "Åtgärder aktiva",
        "overview.changeLighting": "Ändra belysning",
        "overview.dialSubtitle": "Mediadockans runda skärm",
        "overview.keyboardEffect": "Tangentbordseffekt",
        "overview.macEffect": "Effekt beräknad av Macen",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Glöd",
        "palette.forest": "Skog",
        "palette.ice": "Is",
        "palette.neon": "Neon",
        "palette.ocean": "Hav",
        "palette.sunset": "Solnedgång",
        "palette.vapor": "Dimma",

        // MARK: preset
        "preset.bolt": "Blixt",
        "preset.calendar": "Kalender",
        "preset.captureScreen": "Ta skärmbild",
        "preset.captureZone": "Ta bild av område",
        "preset.category.apps": "Appar",
        "preset.category.decor": "Endast ikon",
        "preset.category.media": "Media",
        "preset.coffee": "Kaffe",
        "preset.flame": "Låga",
        "preset.game": "Handkontroll",
        "preset.heart": "Hjärta",
        "preset.home": "Hem",
        "preset.lock": "Lås",
        "preset.music": "Musik",
        "preset.mute": "Ljud av",
        "preset.next": "Nästa",
        "preset.playpause": "Spela / Paus",
        "preset.previous": "Föregående",
        "preset.sleepDisplay": "Stäng av skärmen",
        "preset.star": "Stjärna",
        "preset.volumeDown": "Volym −",
        "preset.volumeUp": "Volym +",

        // MARK: profile
        "profile.defaultName": "Profil %1$@",
        "profile.main": "Huvud",

        // MARK: profiles
        "profiles.addApp": "Lägg till en app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Automatiskt byte",
        "profiles.autoSwitchHint": "Fungerar medan appen är öppen eller daemonen körs. En profil som valts för hand på ratten ersätts inte så länge du stannar i en app utan profil.",
        "profiles.autoSwitchNote": "Tangentbordet byter till en apps profil när appen ligger överst",
        "profiles.deleteHelp": "Ta bort den här profilen från appen",
        "profiles.dialMode": "Ratt: %1$@",
        "profiles.dialOnActivate": "Ratt vid aktivering",
        "profiles.dialUnchanged": "Ratten oförändrad",
        "profiles.dontChange": "Ändra inte",
        "profiles.enable": "Aktivera",
        "profiles.freeSlots": "%1$@ ledig(a) plats(er)",
        "profiles.hardwareNote": "Tangentbordet lagrar fem profiler i minnet (rattens Profile-meny). Var och en har egen belysning, egna omkopplingar och egna D1–D4-bilder; appen lägger till tangentåtgärderna, rattläget och de länkade apparna.",
        "profiles.header": "PROFIL %1$@",
        "profiles.iconAndColour": "Ikon och färg",
        "profiles.keyboardLighting": "Tangentbordsbelysning",
        "profiles.keyboardProfiles": "TANGENTBORDSPROFILER",
        "profiles.keysNote": "Tangenterna D1–D4 och belysningen ställs in på sina egna sidor medan den här profilen är aktiv: de sparas i den här profilen.",
        "profiles.lightingFirmware": "Belysning: %1$@",
        "profiles.lightingMac": "Mac-belysning: %1$@",
        "profiles.linkedApps": "Länkade appar",
        "profiles.manage": "Hantera…",
        "profiles.namePlaceholder": "Kodning, Musik…",
        "profiles.noLinkedApp": "Ingen länkad app",
        "profiles.otherwise": "Annars, gå tillbaka till",
        "profiles.slot": "Plats %1$@",
        "profiles.slotOfKeyboard": "Tangentbordsplats %1$@",

        // MARK: reset
        "reset.title": "Återställ",

        // MARK: section
        "section.buttons.subtitle": "En macOS-åtgärd på var och en av de fyra skärmtangenterna",
        "section.buttons.title": "Tangenterna D1–D4",
        "section.displays.subtitle": "Rattens runda skärm och det numeriska tangentbordets skärmtangenter",
        "section.displays.title": "Skärmar",
        "section.keyboard.subtitle": "Upptäckt tangentbordslayout och motsvarande macOS-layout",
        "section.keyboard.title": "Layout",
        "section.lighting.subtitle": "Officiella tangentbordseffekter och dynamiska effekter beräknade av Macen",
        "section.overview.subtitle": "Din Everest Max i korthet",
        "section.overview.title": "Översikt",
        "section.profiles.subtitle": "Fem profiler lagrade i tangentbordet, var och en med egna tangenter, belysning och appar",
        "section.profiles.title": "Profiler",
        "section.system.subtitle": "Tangentdaemon, övervakning och felsökning",
        "section.system.title": "System",

        // MARK: settings
        "settings.language.automatic": "Automatiskt (systemspråk)",
        "settings.language.note": "Språk för gränssnittet, menyradsmenyn och meddelanden.",
        "settings.language.title": "Språk",

        // MARK: status
        "status.animationPaused": "Animationen pausad — tangentbordet behåller den senaste bilden.",
        "status.appIconUnreadable": "Det gick inte att läsa appens ikon.",
        "status.appNoId": "Appen har ingen identifierare: den kan inte länkas.",
        "status.changeFailed": "Det gick inte att ändra: %1$@",
        "status.cleaning": "Rensar",
        "status.clockSynced": "Klockan synkroniserad med Macen.",
        "status.configSaved": "Inställningarna sparades.",
        "status.daemonOff": "Tangenterna D1–D4 avstängda.",
        "status.daemonOn": "Tangenterna D1–D4 aktiva.",
        "status.daemonStartFailed": "Det gick inte att starta daemonen: %1$@",
        "status.dialImageSent": "Bilden skickades till ratten.",
        "status.dialMode": "Ratt: %1$@.",
        "status.displayLabel": "Skärm",
        "status.effectApplied": "%1$@ tillämpades och sparades i profilen.",
        "status.effectRunningKeyboard": "Effekten ”%1$@” körs på tangentbordet.",
        "status.factoryIconRestored": "Fabriksikonen återställdes på %1$@.",
        "status.frozen": "Bilden låstes och sparades i tangentbordets ”Custom”-plats.",
        "status.iconDrawFailed": "Det gick inte att rita ikonen.",
        "status.iconSent": "Ikonen skickades till %1$@ på %2$@ s.",
        "status.keyboardConnected": "Tangentbordet anslutet.",
        "status.keyboardGone": "Tangentbordet frånkopplat — effekten återupptas när det ansluts igen.",
        "status.layoutAuto": "Layout: automatisk identifiering.",
        "status.layoutForced": "Layout framtvingad: %1$@.",
        "status.leftoversCleared": "Kvarglömda åtgärder raderades från tangentbordets minne.",
        "status.loginApproval": "Måste godkännas i Systeminställningar → Allmänt → Inloggningsobjekt.",
        "status.previewOnly": "Tangentbordet hittades inte — förhandsvisningen finns kvar.",
        "status.profileActivated": "Profilen ”%1$@” aktiverades.",
        "status.profileActivatedFrontApp": "Profilen ”%1$@” aktiverades (appen ligger överst).",
        "status.profileFromKeyboard": "Profilen ”%1$@” aktiv (vald på tangentbordet).",
        "status.profileRemoved": "Profilen togs bort från appen (tangentbordet behåller sina inställningar på plats %1$@).",
        "status.ready": "Redo",
        "status.recovering": "Återställning",
        "status.recoverySent": "Återställningssekvensen skickades.",
        "status.saving": "Sparar",
        "status.sendingImage": "Skickar bilden…",
        "status.uploadBusy": "En överföring pågår på %1$@ — vänta några sekunder.",
        "status.uploadBusyAlready": "En överföring pågår redan på %1$@ — vänta några sekunder.",
        "status.uploadFailed": "Överföringen misslyckades: %1$@",
        "status.uploadFailedKey": "%1$@: överföringen misslyckades — %2$@",
        "status.uploadStarted": "%1$@: skickar bilden till tangentbordet…",

        // MARK: system
        "system.askAgain": "Fråga igen",
        "system.autoDaemon": "Aktivera tangenterna D1–D4 automatiskt",
        "system.autoDaemonNote": "Daemonen startar med appen, återansluter själv när tangentbordet ansluts igen och startar om om den stannar.",
        "system.autostartHint": "Automatisk start vid inloggning: ./install-daemon.sh från Terminal.",
        "system.background": "Everest arbetar i bakgrunden, från menyraden",
        "system.daemonSubtitle": "Kör D1–D4-åtgärderna och skickar värden till ratten",
        "system.daemonTitle": "Tangentdaemon",
        "system.keepRunning": "Låt Everest köra när jag stänger fönstret",
        "system.keepRunningNote": "Tangenterna D1–D4, profilerna och effekterna fortsätter fungera; ikonen finns kvar i menyraden. Avsluta: ikonmenyn eller ⌘Q.",
        "system.keyboardCard": "Tangentbord",
        "system.keyboardCardNote": "Status rapporterad av firmware",
        "system.launchAtLogin": "Starta Everest vid inloggning",
        "system.launchAtLoginNote": "Startar diskret i menyraden utan att öppna fönstret.",
        "system.launchedFrom": "Everest körs från %1$@. För en pålitlig start, kopiera det till /Applications (./make-app.sh --install): en extern volym är inte alltid monterad vid inloggning.",
        "system.lightProfile": "Ljusprofil",
        "system.listening": "Lyssnar",
        "system.metricsEvery": "Daemonen skickar värdena var 0,5:e s medan den körs.",
        "system.modules": "Moduler",
        "system.monitoring": "Övervakning",
        "system.monitoringNote": "Systemvärden som visas på ratten",
        "system.noAccessibility": "Everest saknar behörigheten Hjälpmedel",
        "system.noAccessibilityNote": "Utan den gör åtgärderna ”kortkommando” och ”text” ingenting (app-, kommando- och länkåtgärder fungerar). Om Everest redan är ikryssat i listan är posten föråldrad: markera den, ta bort den med ”−”, lägg sedan till den igen med ”+” (Everest.app) och starta om daemonen.",
        "system.openSettings": "Öppna inställningar",
        "system.sendMetrics": "Skicka CPU, GPU, RAM, disk, nätverk och volym",
        "system.stoppedState": "Stoppad",
        "system.unlock": "Lås upp tangentbordet",
        "system.unlockNote": "”Lås upp” skickar SDK-återställningen om en bildöverföring avbröts. Räcker inte det, koppla från och anslut tangentbordet igen: inget går förlorat.",

        // MARK: upload
        "upload.phase.connect": "Ansluter till tangentbordet",
        "upload.phase.done": "Klart",
        "upload.phase.finish": "Slutför",
        "upload.phase.prepare": "Tangentbordet förbereder platsen",
        "upload.phase.send": "Skickar bilden",

        // MARK: pad
        "pad.keysActive": "P1–P12-tangenter aktiva",
        "pad.overview.keys": "%1$@ av 12 tangenter inställda",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "DisplayPad-firmware %1$@ stöds inte",
        "pad.unsupportedNote": "Everest skriver bara till firmware 8, den testade versionen, och lämnar den här plattan i fred.",
        "pad.noAnswer": "DisplayPad svarar inte",
        "pad.noAnswerNote": "Den är ansluten men svarar inte: vänta några sekunder eller anslut den direkt till Macen.",
        "section.displaypad.subtitle": "Tolv skärmtangenter, var och en med en bild och en macOS-åtgärd",
        "pad.connected": "DisplayPad ansluten",
        "pad.connectedNote": "Bilder skickas inom en sekund efter varje ändring; plattan behåller dem tills den kopplas ur.",
        "pad.notConnected": "DisplayPad inte ansluten",
        "pad.notConnectedNote": "Anslut den direkt till Macen: på vissa USB-hubbar förblir skärmen svart.",
        "pad.brightness": "Ljusstyrka",
        "pad.keys": "Tangenter",
        "pad.keysNote": "Klicka på en tangent för att redigera den. Bilder och åtgärder sparas i profilen ”%1$@”.",
        "pad.clearKey": "Rensa",
        "pad.clearKeyHelp": "Tar bort bilden och åtgärden för %1$@",
        "pad.noImage": "Ingen bild",
        "pad.ownImageNote": "Den beskärs i mitten och skalas till 102 × 102. Tangentens åtgärd ändras inte.",
        "pad.daemonStoppedNote": "DisplayPad-tangenterna fungerar bara medan den körs.",
        "pad.status.sent": "%1$@: skickad till DisplayPad.",
        "pad.status.savedOffline": "%1$@: sparad — visas när DisplayPad ansluts.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
