// Interface strings — de. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let de: [String: String] = [
        // MARK: action
        "action.app": "App",
        "action.keypress": "Tastenkürzel",
        "action.none": "Keine",
        "action.open": "Datei",
        "action.shell": "Befehl",
        "action.text": "Text",
        "action.textToType": "Zu tippender Text",
        "action.url": "Link",

        // MARK: app
        "app.closeWindow": "Fenster schließen",
        "app.copy": "Kopieren",
        "app.cut": "Ausschneiden",
        "app.edit": "Bearbeiten",
        "app.hide": "Everest ausblenden",
        "app.paste": "Einsetzen",
        "app.quit": "Everest beenden",
        "app.selectAll": "Alles auswählen",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS-Aktionen und getippte Tastenkürzel benötigen die Bedienungshilfen-Berechtigung (Einstellungen → Datenschutz & Sicherheit).",
        "buttons.actionRan": "Aktion von %1$@ ausgeführt.",
        "buttons.appHint": "Öffnet die App oder holt sie in den Vordergrund",
        "buttons.clearLeftovers": "Übrig gebliebene Aktionen löschen",
        "buttons.daemonStopped": "Der Daemon ist angehalten",
        "buttons.daemonStoppedNote": "Aktionen laufen nur, solange er auf die Tasten D1–D4 lauscht.",
        "buttons.factoryValues": "Werkseinstellungen",
        "buttons.factoryValuesHelp": "Stellt Bild und Aktion von %1$@ wieder her",
        "buttons.flashMemory": "Tastaturspeicher",
        "buttons.flashMemoryNote": "Base Camp kann Aktionen im Flash-Speicher hinterlassen (z. B. D4 sendet Esc)",
        "buttons.keyHeader": "TASTE %1$@",
        "buttons.noAction": "Keine Aktion — die Taste wird ignoriert.",
        "buttons.noApp": "Keine App ausgewählt",
        "buttons.pickPresetAppImage": "Vorlage, App oder Bild für %1$@",
        "buttons.presetsAndIcon": "Vorlagen und Symbol…",

        // MARK: clock
        "clock.analog": "Analog",
        "clock.digital": "Digital",
        "clock.sync": "Synchronisieren",

        // MARK: colormode
        "colormode.dual": "Zwei Farben",
        "colormode.quad": "4 Farben",
        "colormode.rainbow": "Regenbogen",
        "colormode.single": "Eine Farbe",
        "colormode.withBackground": "Taste + Hintergrund",

        // MARK: common
        "common.active": "Aktiv",
        "common.add": "Neu",
        "common.choose": "Auswählen…",
        "common.close": "Schließen",
        "common.configure": "Konfigurieren",
        "common.delete": "Löschen",
        "common.edit": "Bearbeiten",
        "common.name": "Name",
        "common.other": "Andere…",
        "common.refresh": "Aktualisieren",
        "common.remove": "Entfernen",
        "common.start": "Starten",
        "common.stop": "Stoppen",
        "common.test": "Testen",

        // MARK: daemon
        "daemon.keysActive": "Tasten D1–D4 aktiv",
        "daemon.stopped": "Daemon angehalten",

        // MARK: device
        "device.blocked": "Firmware nicht unterstützt",
        "device.connected": "Verbunden",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Getrennt",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Vollständiger Everest Max",
        "device.keyboardMissing": "Tastatur nicht verfügbar",
        "device.keyboardUnavailable": "Tastatur nicht verfügbar (nicht gefunden oder Firmware nicht unterstützt).",
        "device.notConnected": "Nicht verbunden",
        "device.refresh.help": "Status der Tastatur aktualisieren",
        "device.withDock": "Tastatur + Media-Dock",
        "device.withNumpad": "Tastatur + Ziffernblock",

        // MARK: displays
        "displays.change": "Ändern…",
        "displays.chooseImage": "Bild auswählen…",
        "displays.dial.subtitle": "Rundes 240 × 204-Display am Media-Dock",
        "displays.display": "Anzeige",
        "displays.factoryIcon": "Werkssymbol",
        "displays.factoryLogo": "Werkslogo",
        "displays.imageCropped": "Das Bild wird auf 240 × 204 zugeschnitten.",
        "displays.imagesResized": "Bilder werden auf 72 × 72 skaliert.",
        "displays.keys.subtitle": "Vier 72 × 72-Displays über dem Ziffernblock",
        "displays.keys.title": "Display-Tasten",
        "displays.logoRestored": "Mountain-Logo auf dem Dial wiederhergestellt.",
        "displays.metricsNote": "CPU, GPU, RAM, Datenträger, Netzwerk und Lautstärke zeigen die vom Daemon gesendeten Werte (Seite System).",

        // MARK: factory
        "factory.activityMonitor": "Aktivitätsanzeige",
        "factory.sleep": "Ruhezustand",

        // MARK: firmware
        "firmware.block.body": "Everest wurde nur mit Firmware %1$@ getestet. Um jedes Risiko auszuschließen, deine Tastatur unbrauchbar zu machen, sendet es ihr nichts, solange sie nicht diese Version hat: keine Beleuchtung, keine Bilder, keine Aktionen.",
        "firmware.block.check": "Erneut prüfen",
        "firmware.block.detected": "Erkannte Firmware: %1$@",
        "firmware.block.how": "Mountain bietet das Firmware-Update nur in der offiziellen Base-Camp-App für Windows an. Schließe die Tastatur an einen Windows-PC an, installiere Base Camp, aktualisiere die Firmware und schließe die Tastatur dann wieder an diesen Mac an: Everest erkennt sie automatisch.",
        "firmware.block.howTitle": "So aktualisierst du die Tastatur",
        "firmware.block.tested": "Getestete Firmware: %1$@",
        "firmware.block.title": "Firmware nicht unterstützt",
        "firmware.block.unreadableBody": "Everest kann die Firmware-Version der Tastatur nicht prüfen und rührt sie deshalb nicht an. Trenne die Tastatur, schließe sie wieder an und versuche es erneut.",
        "firmware.block.unreadableTitle": "Firmware nicht lesbar",
        "firmware.block.why": "Everest aktualisiert die Firmware nicht selbst: Das ist dieselbe Art von Vorgang, die eine Tastatur unbrauchbar machen kann, und er lässt sich hier nicht testen.",
        "firmware.status.unreadable": "Die Tastatur hat ihre Firmware nicht gemeldet — sie bleibt unverändert.",
        "firmware.status.unsupported": "Firmware %1$@ wird nicht unterstützt (getestet: %2$@) — die Tastatur bleibt unverändert.",

        // MARK: fx
        "fx.breathing": "Atmen",
        "fx.breathing.desc": "Sanftes Pulsieren",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Fallende Tropfen",
        "fx.off": "Aus",
        "fx.off.desc": "Alles ist aus",
        "fx.reactive": "Reaktiv",
        "fx.reactive.desc": "Leuchtet beim Tippen auf",
        "fx.static": "Statisch",
        "fx.static.desc": "Feste Farbe",
        "fx.tornado": "Wirbelsturm",
        "fx.tornado.desc": "Dreht sich um die Mitte",
        "fx.wave": "Welle",
        "fx.wave.desc": "Läuft über die Tastatur",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Welle von der Taste aus",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Auch die Aktion der Vorlage übernehmen",
        "keyappearance.appHint": "Die Taste öffnet die App oder holt sie in den Vordergrund, falls sie schon geöffnet ist.",
        "keyappearance.apps": "Apps",
        "keyappearance.background": "Im Hintergrund fortsetzen",
        "keyappearance.busyOther": "Auf %1$@ läuft eine Übertragung — warte, bis sie fertig ist, bevor du diese Taste änderst.",
        "keyappearance.chooseFile": "Datei auswählen…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Öffnet die App",
        "keyappearance.ownImage": "Dein eigenes Bild",
        "keyappearance.ownImageNote": "Es wird mittig zugeschnitten und auf 72 × 72 skaliert. Die Aktion der Taste ändert sich nicht.",
        "keyappearance.presets": "Vorlagen",
        "keyappearance.searchApp": "App suchen",
        "keyappearance.step.prepare": "Vorbereitung",
        "keyappearance.step.send": "Senden",
        "keyappearance.subtitle": "Wähle, was das Display zeigt und was die Taste tut",
        "keyappearance.title": "Taste %1$@",
        "keyappearance.transferNote": "Eine Übertragung dauert etwa 20 Sekunden: Die Tastatur bereitet den Speicherplatz vor (sie löscht das alte Bild selbst) und empfängt dann das neue in 64-Byte-Paketen. Trenne die Tastatur nicht.",

        // MARK: keyboard
        "keyboard.activeBadge": "AKTIV",
        "keyboard.ansiShape": "ANSI-Form: breite Eingabetaste, \\ am Ende der oberen Reihe",
        "keyboard.asPrinted": "wie aufgedruckt",
        "keyboard.automatic": "Automatisch",
        "keyboard.chosen": "VON HAND GEWÄHLT",
        "keyboard.clearRemaps": "Remaps löschen",
        "keyboard.detected": "ERKANNT",
        "keyboard.hidutilNote": "hidutil: Usage 0x64 → 0x31. Gilt bis zum Neustart. Für ein in der Tastatur gespeichertes Remap: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO-Taste",
        "keyboard.isoMuteNote": "Wenn macOS die Tastatur als ANSI behandelt, tut die Taste links von Y nichts",
        "keyboard.isoMuteTitle": "ISO-Taste reagiert nicht?",
        "keyboard.isoShape": "ISO-Form: hohe Eingabetaste, zusätzliche Taste links von Y",
        "keyboard.legend.at": "@ auf der Taste '",
        "keyboard.legend.backslash": "\\ | links von Y",
        "keyboard.legend.quote": "\" auf ⇧2",
        "keyboard.legend.rightOfSemicolon": "rechts von ;",
        "keyboard.macLayout": "macOS-Tastaturbelegung",
        "keyboard.macLayoutNote": "Damit macOS das schreibt, was auf den Tasten steht",
        "keyboard.noMacLayout": "Es ist keine passende macOS-Tastaturbelegung für „%1$@“ installiert: Füge sie in den Systemeinstellungen → Tastatur → Eingabequellen hinzu.",
        "keyboard.remapApplied": "ISO-Remap angewendet (bis zum Neustart).",
        "keyboard.remapIso": "ISO-Taste neu belegen",
        "keyboard.remapsCleared": "hidutil-Remaps gelöscht.",
        "keyboard.reportsLayout": "Die Tastatur meldet „%1$@“. Wechsle zurück zu „Automatisch“, wenn diese Auswahl nicht mehr nötig ist.",
        "keyboard.switchedTo": "Belegung gewechselt zu %1$@.",
        "keyboard.title": "Physische Tastatur",
        "keyboard.titleNote": "Aus der Tastatur gelesen, wie bei Base Camp: Zeichnung, Tasten und Effekte passen sich an",
        "keyboard.unknown": "unbekannt",
        "keyboard.use": "%1$@ verwenden",
        "keyboard.verifiedNote1": "Form und Beleuchtung jeder Taste folgen dem Raster der Tastatur; nur das UK-Layout wurde an einer echten Tastatur überprüft.",
        "keyboard.verifiedNote2": "Die Beschriftungen stammen aus den Tabellen von Base Camp, und die Form folgt dem LED-Raster; nur das UK-Layout wurde an einer echten Tastatur überprüft.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "Dial-Übertragung unterbrochen — verwende „Tastatur entsperren“ (Seite System) oder stecke sie neu ein",
        "keyboardError.dialRefused": "das Dial hat die Übertragung abgelehnt (es wurde nichts geschrieben)",
        "keyboardError.interrupted": "Übertragung unterbrochen — verwende „Tastatur entsperren“ (Seite System) oder stecke sie neu ein",
        "keyboardError.refused": "die Tastatur hat die Übertragung abgelehnt (es wurde nichts geschrieben) — versuche es erneut; bleibt das Problem, verwende „Tastatur entsperren“ (Seite System)",
        "keyboardError.selectTarget": "die Tastatur reagiert nicht auf die Tastenauswahl — verwende „Tastatur entsperren“ (Seite System) oder stecke sie neu ein",

        // MARK: layout
        "layout.french": "Französisch (AZERTY)",
        "layout.german": "Deutsch (QWERTZ)",
        "layout.hebrew": "Hebräisch",
        "layout.italian": "Italienisch",
        "layout.korean": "Koreanisch",
        "layout.nordic": "Nordisch",
        "layout.portuguese": "Portugiesisch",
        "layout.spanish": "Spanisch",
        "layout.uk": "Vereinigtes Königreich (ISO)",
        "layout.us": "USA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Farbe hinzufügen",
        "lighting.allHues": "Alle Farbtöne, von der Tastatur erzeugt.",
        "lighting.backgroundColour": "Hintergrund",
        "lighting.brightness": "Helligkeit",
        "lighting.byKeyboard": "Läuft in der Tastatur — auch ohne die App",
        "lighting.byMac": "Vom Mac berechnet — App geöffnet lassen",
        "lighting.clearAll": "Alles löschen",
        "lighting.clockwise": "Im Uhrzeigersinn",
        "lighting.colors": "Farben",
        "lighting.colour": "Farbe",
        "lighting.colour1": "Farbe 1",
        "lighting.colour2": "Farbe 2",
        "lighting.colourCount.one": "%1$@ Farbe",
        "lighting.colourCount.other": "%1$@ Farben",
        "lighting.counterclockwise": "Gegen den Uhrzeigersinn",
        "lighting.direction": "Richtung",
        "lighting.editEllipsis": "Bearbeiten…",
        "lighting.fast": "Schnell",
        "lighting.flameNote": "Feste Flammenskala, von Glut bis Weiß.",
        "lighting.freeze": "In der Tastatur fixieren",
        "lighting.freezeNote": "Sendet das aktuelle Bild an den Custom-Slot und speichert es: Es bleibt auch ohne die App.",
        "lighting.keyColour": "Taste",
        "lighting.ledsBlack": "Alle LEDs sind schwarz, solange der Effekt läuft.",
        "lighting.macNote": "Taste für Taste mit 30 Bildern/s berechnet, mit deiner Palette",
        "lighting.normal": "Normal",
        "lighting.offNote": "Hintergrundbeleuchtung und Seitenstreifen sind aus. Wähle einen anderen Effekt, um sie wieder einzuschalten.",
        "lighting.officialEffects": "Offizielle Effekte",
        "lighting.officialNote": "Die Effekte von Base Camp, genau wie von der Windows-App gesendet",
        "lighting.paintHint": "Klicke oder ziehe über die Tasten der Tastatur oben.",
        "lighting.paintKeys": "Taste für Taste malen",
        "lighting.palette": "Palette",
        "lighting.paused": "Pausiert",
        "lighting.reapply": "Erneut anwenden",
        "lighting.rightClickHint": "Rechtsklick auf ein Farbfeld, um es zu entfernen.",
        "lighting.rotation": "Drehrichtung",
        "lighting.runningOnKeyboard": "Läuft auf der Tastatur",
        "lighting.savedInProfile": "Im aktiven Profil der Tastatur gespeichert",
        "lighting.slow": "Langsam",
        "lighting.speed": "Geschwindigkeit",
        "lighting.title": "Beleuchtung",

        // MARK: live
        "live.keyboard": "Tastatur · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · pausiert",
        "live.pause": "Pause",
        "live.start": "Starten",

        // MARK: macfx
        "macfx.aurora": "Polarlicht",
        "macfx.equalizer": "Equalizer",
        "macfx.fire": "Feuer",
        "macfx.gradient": "Verlauf",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Digitaler Regen",
        "macfx.ripples": "Wellen",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Einfarbig",
        "macfx.spectrum": "Spektrum",
        "macfx.spiral": "Spirale",
        "macfx.stars": "Sterne",
        "macfx.waves": "Wogen",

        // MARK: menu
        "menu.allowAccessibility": "Bedienungshilfen erlauben…",
        "menu.disconnected": "Tastatur getrennt",
        "menu.firmwareBlocked": "Firmware nicht unterstützt — Tastatur wird ignoriert",
        "menu.keyboardEffects": "Tastatureffekte",
        "menu.launchAtLogin": "Beim Anmelden starten",
        "menu.macEffects": "Mac-Effekte",
        "menu.manageProfiles": "Profile verwalten…",
        "menu.newProfile": "Neues Profil",
        "menu.open": "Everest öffnen…",
        "menu.pauseEffect": "Effekt pausieren",
        "menu.profile": "Profil: %1$@",
        "menu.resumeEffect": "Effekt fortsetzen",

        // MARK: metric
        "metric.disk": "DATENTRÄGER",
        "metric.network": "NETZWERK",
        "metric.volume": "LAUTSTÄRKE",

        // MARK: mode
        "mode.clock": "Uhr",
        "mode.disk": "Datenträger",
        "mode.image": "Bild",
        "mode.network": "Netzwerk",
        "mode.volume": "Lautstärke",

        // MARK: overview
        "overview.actionsActive": "Aktionen aktiv",
        "overview.changeLighting": "Beleuchtung ändern",
        "overview.dialSubtitle": "Rundes Display des Media-Docks",
        "overview.keyboardEffect": "Tastatureffekt",
        "overview.macEffect": "Vom Mac berechneter Effekt",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Glut",
        "palette.forest": "Wald",
        "palette.ice": "Eis",
        "palette.neon": "Neon",
        "palette.ocean": "Ozean",
        "palette.sunset": "Sonnenuntergang",
        "palette.vapor": "Dunst",

        // MARK: preset
        "preset.bolt": "Blitz",
        "preset.calendar": "Kalender",
        "preset.captureScreen": "Bildschirmfoto",
        "preset.captureZone": "Bereich aufnehmen",
        "preset.category.apps": "Apps",
        "preset.category.decor": "Nur Symbol",
        "preset.category.media": "Medien",
        "preset.coffee": "Kaffee",
        "preset.flame": "Flamme",
        "preset.game": "Controller",
        "preset.heart": "Herz",
        "preset.home": "Zuhause",
        "preset.lock": "Sperren",
        "preset.music": "Musik",
        "preset.mute": "Stumm",
        "preset.next": "Weiter",
        "preset.playpause": "Wiedergabe / Pause",
        "preset.previous": "Zurück",
        "preset.sleepDisplay": "Bildschirm ausschalten",
        "preset.star": "Stern",
        "preset.volumeDown": "Leiser −",
        "preset.volumeUp": "Lauter +",

        // MARK: profile
        "profile.defaultName": "Profil %1$@",
        "profile.main": "Hauptprofil",

        // MARK: profiles
        "profiles.addApp": "App hinzufügen (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Automatischer Wechsel",
        "profiles.autoSwitchHint": "Funktioniert, solange die App geöffnet ist oder der Daemon läuft. Ein am Dial von Hand gewähltes Profil wird nicht ersetzt, solange du in einer App ohne Profil bleibst.",
        "profiles.autoSwitchNote": "Die Tastatur wechselt zum Profil einer App, wenn diese im Vordergrund ist",
        "profiles.deleteHelp": "Dieses Profil aus der App löschen",
        "profiles.dialMode": "Dial: %1$@",
        "profiles.dialOnActivate": "Dial bei Aktivierung",
        "profiles.dialUnchanged": "Dial unverändert",
        "profiles.dontChange": "Nicht ändern",
        "profiles.enable": "Aktivieren",
        "profiles.freeSlots": "%1$@ freie(r) Slot(s)",
        "profiles.hardwareNote": "Die Tastatur speichert fünf Profile (Menü „Profile“ des Dials). Jedes hat eigene Beleuchtung, Remaps und D1–D4-Bilder; die App ergänzt die Tastenaktionen, den Dial-Modus und die verknüpften Apps.",
        "profiles.header": "PROFIL %1$@",
        "profiles.iconAndColour": "Symbol und Farbe",
        "profiles.keyboardLighting": "Tastaturbeleuchtung",
        "profiles.keyboardProfiles": "TASTATURPROFILE",
        "profiles.keysNote": "Die Tasten D1–D4 und die Beleuchtung werden auf ihren eigenen Seiten eingestellt, solange dieses Profil aktiv ist: Sie werden in diesem Profil gespeichert.",
        "profiles.lightingFirmware": "Beleuchtung: %1$@",
        "profiles.lightingMac": "Mac-Beleuchtung: %1$@",
        "profiles.linkedApps": "Verknüpfte Apps",
        "profiles.manage": "Verwalten…",
        "profiles.namePlaceholder": "Coding, Musik…",
        "profiles.noLinkedApp": "Keine verknüpfte App",
        "profiles.otherwise": "Andernfalls zurück zu",
        "profiles.slot": "Slot %1$@",
        "profiles.slotOfKeyboard": "Tastatur-Slot %1$@",

        // MARK: reset
        "reset.title": "Zurücksetzen",

        // MARK: section
        "section.buttons.subtitle": "Eine macOS-Aktion auf jeder der vier Display-Tasten",
        "section.buttons.title": "Tasten D1–D4",
        "section.displays.subtitle": "Das runde Display des Dials und die Display-Tasten des Ziffernblocks",
        "section.displays.title": "Displays",
        "section.keyboard.subtitle": "Erkanntes Tastaturlayout und die passende macOS-Tastaturbelegung",
        "section.keyboard.title": "Layout",
        "section.lighting.subtitle": "Offizielle Tastatureffekte und dynamische, vom Mac berechnete Effekte",
        "section.overview.subtitle": "Dein Everest Max auf einen Blick",
        "section.overview.title": "Übersicht",
        "section.profiles.subtitle": "Fünf in der Tastatur gespeicherte Profile, jedes mit eigenen Tasten, Beleuchtung und Apps",
        "section.profiles.title": "Profile",
        "section.system.subtitle": "Tasten-Daemon, Überwachung und Fehlerbehebung",
        "section.system.title": "System",

        // MARK: settings
        "settings.language.automatic": "Automatisch (Systemsprache)",
        "settings.language.note": "Sprache der Oberfläche, des Menüleistenmenüs und der Meldungen.",
        "settings.language.title": "Sprache",

        // MARK: status
        "status.animationPaused": "Animation pausiert — die Tastatur behält das letzte Bild.",
        "status.appIconUnreadable": "Das Symbol der App konnte nicht gelesen werden.",
        "status.appNoId": "Diese App hat keine Kennung: Sie kann nicht verknüpft werden.",
        "status.changeFailed": "Änderung nicht möglich: %1$@",
        "status.cleaning": "Aufräumen",
        "status.clockSynced": "Uhr mit dem Mac synchronisiert.",
        "status.configSaved": "Einstellungen gespeichert.",
        "status.daemonOff": "Tasten D1–D4 ausgeschaltet.",
        "status.daemonOn": "Tasten D1–D4 aktiv.",
        "status.daemonStartFailed": "Der Daemon konnte nicht gestartet werden: %1$@",
        "status.dialImageSent": "Bild an das Dial gesendet.",
        "status.dialMode": "Dial: %1$@.",
        "status.displayLabel": "Display",
        "status.effectApplied": "%1$@ angewendet und im Profil gespeichert.",
        "status.effectRunningKeyboard": "Effekt „%1$@“ läuft auf der Tastatur.",
        "status.factoryIconRestored": "Werkssymbol auf %1$@ wiederhergestellt.",
        "status.frozen": "Bild fixiert und im „Custom“-Slot der Tastatur gespeichert.",
        "status.iconDrawFailed": "Das Symbol konnte nicht gezeichnet werden.",
        "status.iconSent": "Symbol in %2$@ s an %1$@ gesendet.",
        "status.keyboardConnected": "Tastatur verbunden.",
        "status.keyboardGone": "Tastatur getrennt — der Effekt wird beim Wiederanschließen fortgesetzt.",
        "status.layoutAuto": "Layout: automatische Erkennung.",
        "status.layoutForced": "Layout erzwungen: %1$@.",
        "status.leftoversCleared": "Übrig gebliebene Aktionen aus dem Tastaturspeicher gelöscht.",
        "status.loginApproval": "Muss in den Systemeinstellungen → Allgemein → Anmeldeobjekte erlaubt werden.",
        "status.previewOnly": "Tastatur nicht gefunden — die Vorschau bleibt verfügbar.",
        "status.profileActivated": "Profil „%1$@“ aktiviert.",
        "status.profileActivatedFrontApp": "Profil „%1$@“ aktiviert (App im Vordergrund).",
        "status.profileFromKeyboard": "Profil „%1$@“ aktiv (an der Tastatur gewählt).",
        "status.profileRemoved": "Profil aus der App entfernt (die Tastatur behält ihre Einstellungen in Slot %1$@).",
        "status.ready": "Bereit",
        "status.recovering": "Wiederherstellung",
        "status.recoverySent": "Wiederherstellungssequenz gesendet.",
        "status.saving": "Speichern",
        "status.sendingImage": "Bild wird gesendet…",
        "status.uploadBusy": "Auf %1$@ läuft eine Übertragung — warte ein paar Sekunden.",
        "status.uploadBusyAlready": "Auf %1$@ läuft bereits eine Übertragung — warte ein paar Sekunden.",
        "status.uploadFailed": "Übertragung fehlgeschlagen: %1$@",
        "status.uploadFailedKey": "%1$@: Übertragung fehlgeschlagen — %2$@",
        "status.uploadStarted": "%1$@: Bild wird an die Tastatur gesendet…",

        // MARK: system
        "system.askAgain": "Erneut fragen",
        "system.autoDaemon": "Tasten D1–D4 automatisch aktivieren",
        "system.autoDaemonNote": "Der Daemon startet mit der App, verbindet sich von selbst neu, wenn die Tastatur wieder angeschlossen wird, und startet neu, wenn er anhält.",
        "system.autostartHint": "Automatischer Start bei der Anmeldung: ./install-daemon.sh im Terminal.",
        "system.background": "Everest arbeitet im Hintergrund, über die Menüleiste",
        "system.daemonSubtitle": "Führt die D1–D4-Aktionen aus und sendet Werte an das Dial",
        "system.daemonTitle": "Tasten-Daemon",
        "system.keepRunning": "Everest weiterlaufen lassen, wenn ich das Fenster schließe",
        "system.keepRunningNote": "Die Tasten D1–D4, Profile und Effekte funktionieren weiter; das Symbol bleibt in der Menüleiste. Beenden: Symbolmenü oder ⌘Q.",
        "system.keyboardCard": "Tastatur",
        "system.keyboardCardNote": "Von der Firmware gemeldeter Status",
        "system.launchAtLogin": "Everest bei der Anmeldung starten",
        "system.launchAtLoginNote": "Startet unauffällig in der Menüleiste, ohne das Fenster zu öffnen.",
        "system.launchedFrom": "Everest läuft von %1$@. Für einen zuverlässigen Start kopiere es nach /Applications (./make-app.sh --install): Ein externes Volume ist bei der Anmeldung nicht immer eingebunden.",
        "system.lightProfile": "Lichtprofil",
        "system.listening": "Lauscht",
        "system.metricsEvery": "Der Daemon sendet die Werte alle 0,5 s, solange er läuft.",
        "system.modules": "Module",
        "system.monitoring": "Überwachung",
        "system.monitoringNote": "Systemwerte, die auf dem Dial angezeigt werden",
        "system.noAccessibility": "Everest hat keine Bedienungshilfen-Berechtigung",
        "system.noAccessibilityNote": "Ohne sie tun die Aktionen „Tastenkürzel“ und „Text“ nichts (App-, Befehls- und Link-Aktionen funktionieren weiterhin). Wenn Everest in der Liste bereits angehakt ist, ist der Eintrag veraltet: Wähle ihn aus, entferne ihn mit „−“, füge ihn mit „+“ erneut hinzu (Everest.app) und starte den Daemon neu.",
        "system.openSettings": "Einstellungen öffnen",
        "system.sendMetrics": "CPU, GPU, RAM, Datenträger, Netzwerk und Lautstärke senden",
        "system.stoppedState": "Angehalten",
        "system.unlock": "Tastatur entsperren",
        "system.unlockNote": "„Entsperren“ sendet das SDK-Reset, falls eine Bildübertragung unterbrochen wurde. Reicht das nicht, trenne die Tastatur und schließe sie neu an: Nichts geht verloren.",

        // MARK: upload
        "upload.phase.connect": "Verbindung zur Tastatur",
        "upload.phase.done": "Fertig",
        "upload.phase.finish": "Abschluss",
        "upload.phase.prepare": "Die Tastatur bereitet den Slot vor",
        "upload.phase.send": "Bild wird gesendet",

        // MARK: pad
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "DisplayPad-Firmware %1$@ wird nicht unterstützt",
        "pad.unsupportedNote": "Everest schreibt nur auf Firmware 8, die getestete Version, und lässt dieses Pad in Ruhe.",
        "pad.noAnswer": "DisplayPad antwortet nicht",
        "pad.noAnswerNote": "Es ist angeschlossen, antwortet aber nicht: einige Sekunden warten oder direkt am Mac anschließen.",
        "section.displaypad.subtitle": "Zwölf Display-Tasten, jede mit einem Bild und einer macOS-Aktion",
        "pad.connected": "DisplayPad verbunden",
        "pad.connectedNote": "Bilder werden innerhalb einer Sekunde nach jeder Änderung gesendet; das Pad behält sie, bis es ausgesteckt wird.",
        "pad.notConnected": "DisplayPad nicht verbunden",
        "pad.notConnectedNote": "Direkt am Mac anschließen: an manchen USB-Hubs bleibt sein Bildschirm schwarz.",
        "pad.brightness": "Helligkeit",
        "pad.keys": "Tasten",
        "pad.keysNote": "Klicken Sie auf eine Taste, um sie zu bearbeiten. Bilder und Aktionen werden im Profil „%1$@“ gespeichert.",
        "pad.clearKey": "Leeren",
        "pad.clearKeyHelp": "Entfernt Bild und Aktion von %1$@",
        "pad.noImage": "Kein Bild",
        "pad.ownImageNote": "Es wird mittig zugeschnitten und auf 102 × 102 verkleinert. Die Aktion der Taste bleibt unverändert.",
        "pad.daemonStoppedNote": "Die DisplayPad-Tasten funktionieren nur, solange er läuft.",
        "pad.status.sent": "%1$@: an das DisplayPad gesendet.",
        "pad.status.savedOffline": "%1$@: gespeichert — wird angezeigt, sobald das DisplayPad angeschlossen ist.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
