// Interface strings — he. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let he: [String: String] = [
        // MARK: action
        "action.app": "אפליקציה",
        "action.keypress": "קיצור דרך",
        "action.none": "ללא",
        "action.open": "קובץ",
        "action.shell": "פקודה",
        "action.text": "טקסט",
        "action.textToType": "טקסט להקלדה",
        "action.url": "קישור",

        // MARK: app
        "app.closeWindow": "סגור חלון",
        "app.copy": "העתק",
        "app.cut": "גזור",
        "app.edit": "עריכה",
        "app.hide": "הסתר את Everest",
        "app.paste": "הדבק",
        "app.quit": "צא מ-Everest",
        "app.selectAll": "בחר הכול",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "פעולות macOS וקיצורי דרך מוקלדים דורשים הרשאת נגישות (הגדרות ← פרטיות ואבטחה).",
        "buttons.actionRan": "הפעולה של %1$@ בוצעה.",
        "buttons.appHint": "פותח את האפליקציה או מביא אותה לחזית",
        "buttons.clearLeftovers": "נקה פעולות שנותרו",
        "buttons.daemonStopped": "ה-daemon נעצר",
        "buttons.daemonStoppedNote": "פעולות מופעלות רק כשהוא מאזין למקשים D1–D4.",
        "buttons.factoryValues": "הגדרות יצרן",
        "buttons.factoryValuesHelp": "משחזר את התמונה והפעולה המקוריות של %1$@",
        "buttons.flashMemory": "זיכרון המקלדת",
        "buttons.flashMemoryNote": "Base Camp עלול להשאיר פעולות בזיכרון הפלאש (למשל D4 ששולח Esc)",
        "buttons.keyHeader": "מקש %1$@",
        "buttons.noAction": "אין פעולה — המקש מתעלם מהלחיצה.",
        "buttons.noApp": "לא נבחרה אפליקציה",
        "buttons.pickPresetAppImage": "הגדרה מוכנה, אפליקציה או תמונה עבור %1$@",
        "buttons.presetsAndIcon": "הגדרות מוכנות וסמל…",

        // MARK: clock
        "clock.analog": "אנלוגי",
        "clock.digital": "דיגיטלי",
        "clock.sync": "סנכרון",

        // MARK: colormode
        "colormode.dual": "שני צבעים",
        "colormode.quad": "4 צבעים",
        "colormode.rainbow": "קשת",
        "colormode.single": "צבע אחד",
        "colormode.withBackground": "מקש + רקע",

        // MARK: common
        "common.active": "פעיל",
        "common.add": "חדש",
        "common.choose": "בחירה…",
        "common.close": "סגירה",
        "common.configure": "הגדרה",
        "common.delete": "מחיקה",
        "common.edit": "עריכה",
        "common.name": "שם",
        "common.other": "אחר…",
        "common.refresh": "רענון",
        "common.remove": "הסרה",
        "common.start": "התחלה",
        "common.stop": "עצירה",
        "common.test": "בדיקה",

        // MARK: daemon
        "daemon.keysActive": "המקשים D1–D4 פעילים",
        "daemon.stopped": "ה-daemon נעצר",

        // MARK: device
        "device.blocked": "קושחה לא נתמכת",
        "device.connected": "מחובר",
        "device.core": "Everest Core",
        "device.dial": "חוגה",
        "device.disconnected": "מנותק",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Everest Max מלא",
        "device.keyboardMissing": "המקלדת אינה זמינה",
        "device.keyboardUnavailable": "המקלדת אינה זמינה (לא נמצאה, או שהקושחה אינה נתמכת).",
        "device.notConnected": "לא מחובר",
        "device.refresh.help": "רענון מצב המקלדת",
        "device.withDock": "מקלדת + תחנת מדיה",
        "device.withNumpad": "מקלדת + מקלדת מספרים",

        // MARK: displays
        "displays.change": "שינוי…",
        "displays.chooseImage": "בחירת תמונה…",
        "displays.dial.subtitle": "מסך עגול 240 × 204 בתחנת המדיה",
        "displays.display": "תצוגה",
        "displays.factoryIcon": "סמל יצרן",
        "displays.factoryLogo": "לוגו יצרן",
        "displays.imageCropped": "התמונה נחתכת ל-240 × 204.",
        "displays.imagesResized": "גודל התמונות משתנה ל-72 × 72.",
        "displays.keys.subtitle": "ארבעה מסכים בגודל 72 × 72 מעל מקלדת המספרים",
        "displays.keys.title": "מקשי תצוגה",
        "displays.logoRestored": "הלוגו של Mountain שוחזר בחוגה.",
        "displays.metricsNote": "CPU, GPU, RAM, דיסק, רשת ועוצמת שמע מציגים את הערכים שה-daemon שולח (עמוד מערכת).",

        // MARK: factory
        "factory.activityMonitor": "צג פעילות",
        "factory.sleep": "שינה",

        // MARK: firmware
        "firmware.block.body": "Everest נבדק רק עם קושחה %1$@. כדי להימנע מכל סיכון לשבש את המקלדת שלך, הוא לא שולח לה דבר כל עוד אין בה גרסה זו: לא תאורה, לא תמונות, לא פעולות.",
        "firmware.block.check": "בדיקה חוזרת",
        "firmware.block.detected": "קושחה שזוהתה: %1$@",
        "firmware.block.how": "Mountain מציעה את עדכון הקושחה רק באפליקציית Base Camp הרשמית שלה ל-Windows. חבר את המקלדת למחשב Windows, התקן את Base Camp, עדכן את הקושחה, ואז חבר את המקלדת חזרה ל-Mac הזה: Everest יזהה אותה בעצמו.",
        "firmware.block.howTitle": "איך מעדכנים את המקלדת",
        "firmware.block.tested": "קושחה שנבדקה: %1$@",
        "firmware.block.title": "קושחה לא נתמכת",
        "firmware.block.unreadableBody": "Everest לא מצליח לבדוק את גרסת הקושחה של המקלדת ולכן אינו נוגע בה. נתק וחבר את המקלדת מחדש ונסה שוב.",
        "firmware.block.unreadableTitle": "לא ניתן לקרוא את הקושחה",
        "firmware.block.why": "Everest אינו מעדכן את הקושחה בעצמו: זו אותה סוג פעולה שעלולה להפוך מקלדת לבלתי שמישה, ואי אפשר לבדוק אותה כאן.",
        "firmware.status.unreadable": "המקלדת לא דיווחה על הקושחה שלה — לא נוגעים בה.",
        "firmware.status.unsupported": "קושחה %1$@ אינה נתמכת (נבדקה: %2$@) — לא נוגעים במקלדת.",

        // MARK: fx
        "fx.breathing": "נשימה",
        "fx.breathing.desc": "פעימה עדינה",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "טיפות נופלות",
        "fx.off": "כבוי",
        "fx.off.desc": "הכול כבוי",
        "fx.reactive": "מגיב",
        "fx.reactive.desc": "נדלק בהקלדה",
        "fx.static": "סטטי",
        "fx.static.desc": "צבע קבוע",
        "fx.tornado": "טורנדו",
        "fx.tornado.desc": "מסתובב סביב המרכז",
        "fx.wave": "גל",
        "fx.wave.desc": "עובר לאורך המקלדת",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "אדווה מהמקש",

        // MARK: keyappearance
        "keyappearance.alsoAction": "החל גם את הפעולה של ההגדרה המוכנה",
        "keyappearance.appHint": "המקש פותח את האפליקציה, או מביא אותה לחזית אם היא כבר פתוחה.",
        "keyappearance.apps": "אפליקציות",
        "keyappearance.background": "המשך ברקע",
        "keyappearance.busyOther": "העברה מתבצעת ב-%1$@ — המתן לסיומה לפני שתשנה מקש זה.",
        "keyappearance.chooseFile": "בחירת קובץ…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "פותח את האפליקציה",
        "keyappearance.ownImage": "התמונה שלך",
        "keyappearance.ownImageNote": "היא נחתכת במרכז ומשנה גודל ל-72 × 72. הפעולה של המקש אינה משתנה.",
        "keyappearance.presets": "הגדרות מוכנות",
        "keyappearance.searchApp": "חיפוש אפליקציה",
        "keyappearance.step.prepare": "הכנה",
        "keyappearance.step.send": "שליחה",
        "keyappearance.subtitle": "בחר מה המסך מציג ומה המקש עושה",
        "keyappearance.title": "מקש %1$@",
        "keyappearance.transferNote": "העברה נמשכת כ-20 שניות: המקלדת מכינה את החריץ (היא מוחקת בעצמה את התמונה הישנה) ואז מקבלת את החדשה בחבילות של 64 בתים. אל תנתק את המקלדת.",

        // MARK: keyboard
        "keyboard.activeBadge": "פעיל",
        "keyboard.ansiShape": "צורת ANSI: Enter רחב, \\ בסוף השורה העליונה",
        "keyboard.asPrinted": "כפי שמודפס",
        "keyboard.automatic": "אוטומטי",
        "keyboard.chosen": "נבחר ידנית",
        "keyboard.clearRemaps": "נקה מיפויים מחדש",
        "keyboard.detected": "זוהה",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. נשאר עד הפעלה מחדש. למיפוי שנשמר במקלדת: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "מקש ISO",
        "keyboard.isoMuteNote": "אם macOS מתייחס למקלדת כ-ANSI, המקש משמאל ל-Z לא עושה דבר",
        "keyboard.isoMuteTitle": "מקש ISO לא מגיב?",
        "keyboard.isoShape": "צורת ISO: Enter גבוה, מקש נוסף משמאל ל-Z",
        "keyboard.legend.at": "@ על המקש '",
        "keyboard.legend.backslash": "\\ | משמאל ל-Z",
        "keyboard.legend.quote": "\" על ⇧2",
        "keyboard.legend.rightOfSemicolon": "מימין ל-;",
        "keyboard.macLayout": "פריסת macOS",
        "keyboard.macLayoutNote": "כדי ש-macOS יכתוב את מה שמודפס על המקשים",
        "keyboard.noMacLayout": "לא מותקנת פריסת macOS שמתאימה ל-“%1$@”: הוסף אותה בהגדרות המערכת ← מקלדת ← מקורות קלט.",
        "keyboard.remapApplied": "מיפוי ISO הוחל (עד הפעלה מחדש).",
        "keyboard.remapIso": "מיפוי מחדש של מקש ISO",
        "keyboard.remapsCleared": "מיפויי hidutil נוקו.",
        "keyboard.reportsLayout": "המקלדת מדווחת “%1$@”. חזור לאוטומטי אם אין עוד צורך בבחירה זו.",
        "keyboard.switchedTo": "הפריסה הוחלפה ל-%1$@.",
        "keyboard.title": "מקלדת פיזית",
        "keyboard.titleNote": "נקרא מהמקלדת, כמו ב-Base Camp: האיור, המקשים והאפקטים מתאימים את עצמם",
        "keyboard.unknown": "לא ידוע",
        "keyboard.use": "השתמש ב-%1$@",
        "keyboard.verifiedNote1": "הצורה והתאורה של כל מקש עוקבות אחר רשת המקלדת; רק פריסת UK אומתה על מקלדת אמיתית.",
        "keyboard.verifiedNote2": "הכיתובים מגיעים מהטבלאות של Base Camp והצורה עוקבת אחר רשת ה-LED; רק פריסת UK אומתה על מקלדת אמיתית.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "ההעברה לחוגה הופסקה — השתמש ב“שחרור המקלדת” (עמוד מערכת) או חבר אותה מחדש",
        "keyboardError.dialRefused": "החוגה דחתה את ההעברה (דבר לא נכתב)",
        "keyboardError.interrupted": "ההעברה הופסקה — השתמש ב“שחרור המקלדת” (עמוד מערכת) או חבר אותה מחדש",
        "keyboardError.refused": "המקלדת דחתה את ההעברה (דבר לא נכתב) — נסה שוב; אם הבעיה נמשכת, השתמש ב“שחרור המקלדת” (עמוד מערכת)",
        "keyboardError.selectTarget": "המקלדת אינה מגיבה לבחירת המקשים — השתמש ב“שחרור המקלדת” (עמוד מערכת) או חבר אותה מחדש",

        // MARK: layout
        "layout.french": "צרפתית (AZERTY)",
        "layout.german": "גרמנית (QWERTZ)",
        "layout.hebrew": "עברית",
        "layout.italian": "איטלקית",
        "layout.korean": "קוריאנית",
        "layout.nordic": "נורדית",
        "layout.portuguese": "פורטוגזית",
        "layout.spanish": "ספרדית",
        "layout.uk": "בריטניה (ISO)",
        "layout.us": "ארה״ב (ANSI)",

        // MARK: lighting
        "lighting.addColour": "הוסף צבע",
        "lighting.allHues": "כל הגוונים, שנוצרים על ידי המקלדת.",
        "lighting.backgroundColour": "רקע",
        "lighting.brightness": "בהירות",
        "lighting.byKeyboard": "מופעל על ידי המקלדת — ממשיך גם בלי האפליקציה",
        "lighting.byMac": "מחושב על ידי ה-Mac — השאר את האפליקציה פתוחה",
        "lighting.clearAll": "נקה הכול",
        "lighting.clockwise": "עם כיוון השעון",
        "lighting.colors": "צבעים",
        "lighting.colour": "צבע",
        "lighting.colour1": "צבע 1",
        "lighting.colour2": "צבע 2",
        "lighting.colourCount.one": "צבע %1$@",
        "lighting.colourCount.other": "%1$@ צבעים",
        "lighting.counterclockwise": "נגד כיוון השעון",
        "lighting.direction": "כיוון",
        "lighting.editEllipsis": "עריכה…",
        "lighting.fast": "מהיר",
        "lighting.flameNote": "סולם להבה קבוע, מגחלת ללבן.",
        "lighting.freeze": "קבע במקלדת",
        "lighting.freezeNote": "שולח את הפריים הנוכחי לחריץ Custom ושומר אותו: הוא נשאר גם בלי האפליקציה.",
        "lighting.keyColour": "מקש",
        "lighting.ledsBlack": "כל נוריות ה-LED שחורות בזמן שהאפקט פועל.",
        "lighting.macNote": "מחושב מקש אחר מקש ב-30 פריימים/שנייה, עם הפלטה שלך",
        "lighting.normal": "Normal",
        "lighting.offNote": "התאורה האחורית והפסים בצדדים כבויים. בחר אפקט אחר כדי להדליק אותם שוב.",
        "lighting.officialEffects": "אפקטים רשמיים",
        "lighting.officialNote": "האפקטים של Base Camp, נשלחים בדיוק כמו באפליקציית Windows",
        "lighting.paintHint": "לחץ או גרור מעל מקשי המקלדת שלמעלה.",
        "lighting.paintKeys": "צביעה מקש אחר מקש",
        "lighting.palette": "Palette",
        "lighting.paused": "מושהה",
        "lighting.reapply": "החל שוב",
        "lighting.rightClickHint": "לחיצה ימנית על דוגמית מסירה אותה.",
        "lighting.rotation": "כיוון סיבוב",
        "lighting.runningOnKeyboard": "פועל על המקלדת",
        "lighting.savedInProfile": "נשמר בפרופיל הפעיל של המקלדת",
        "lighting.slow": "איטי",
        "lighting.speed": "מהירות",
        "lighting.title": "תאורה",

        // MARK: live
        "live.keyboard": "מקלדת · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · מושהה",
        "live.pause": "השהיה",
        "live.start": "התחלה",

        // MARK: macfx
        "macfx.aurora": "זוהר צפוני",
        "macfx.equalizer": "אקולייזר",
        "macfx.fire": "אש",
        "macfx.gradient": "מעבר צבעים",
        "macfx.plasma": "Plasma",
        "macfx.rain": "גשם דיגיטלי",
        "macfx.ripples": "אדוות",
        "macfx.scanner": "Scanner",
        "macfx.solid": "צבע אחיד",
        "macfx.spectrum": "ספקטרום",
        "macfx.spiral": "ספירלה",
        "macfx.stars": "כוכבים",
        "macfx.waves": "גלים",

        // MARK: menu
        "menu.allowAccessibility": "אפשר נגישות…",
        "menu.disconnected": "המקלדת מנותקת",
        "menu.firmwareBlocked": "קושחה לא נתמכת — המקלדת לא נוגעים בה",
        "menu.keyboardEffects": "אפקטים של המקלדת",
        "menu.launchAtLogin": "הפעלה בעת כניסה",
        "menu.macEffects": "אפקטים של ה-Mac",
        "menu.manageProfiles": "ניהול פרופילים…",
        "menu.newProfile": "פרופיל חדש",
        "menu.open": "פתח את Everest…",
        "menu.pauseEffect": "השהה את האפקט",
        "menu.profile": "פרופיל: %1$@",
        "menu.resumeEffect": "המשך את האפקט",

        // MARK: metric
        "metric.disk": "דיסק",
        "metric.network": "רשת",
        "metric.volume": "עוצמה",

        // MARK: mode
        "mode.clock": "שעון",
        "mode.disk": "דיסק",
        "mode.image": "תמונה",
        "mode.network": "רשת",
        "mode.volume": "עוצמת שמע",

        // MARK: overview
        "overview.actionsActive": "פעולות פעילות",
        "overview.changeLighting": "שינוי התאורה",
        "overview.dialSubtitle": "המסך העגול של תחנת המדיה",
        "overview.keyboardEffect": "אפקט המקלדת",
        "overview.macEffect": "אפקט שמחושב על ידי ה-Mac",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "גחלת",
        "palette.forest": "יער",
        "palette.ice": "קרח",
        "palette.neon": "ניאון",
        "palette.ocean": "אוקיינוס",
        "palette.sunset": "שקיעה",
        "palette.vapor": "אדים",

        // MARK: preset
        "preset.bolt": "ברק",
        "preset.calendar": "לוח שנה",
        "preset.captureScreen": "צילום מסך",
        "preset.captureZone": "צילום אזור",
        "preset.category.apps": "אפליקציות",
        "preset.category.decor": "סמל בלבד",
        "preset.category.media": "מדיה",
        "preset.coffee": "קפה",
        "preset.flame": "להבה",
        "preset.game": "בקר משחק",
        "preset.heart": "לב",
        "preset.home": "בית",
        "preset.lock": "נעילה",
        "preset.music": "מוזיקה",
        "preset.mute": "השתקה",
        "preset.next": "הבא",
        "preset.playpause": "נגן / השהה",
        "preset.previous": "הקודם",
        "preset.sleepDisplay": "כיבוי המסך",
        "preset.star": "כוכב",
        "preset.volumeDown": "עוצמה −",
        "preset.volumeUp": "עוצמה +",

        // MARK: profile
        "profile.defaultName": "פרופיל %1$@",
        "profile.main": "ראשי",

        // MARK: profiles
        "profiles.addApp": "הוסף אפליקציה (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "החלפה אוטומטית",
        "profiles.autoSwitchHint": "פועל כשהאפליקציה פתוחה או שה-daemon רץ. פרופיל שנבחר ידנית בחוגה לא יוחלף כל עוד אתה נשאר באפליקציה ללא פרופיל.",
        "profiles.autoSwitchNote": "המקלדת עוברת לפרופיל של אפליקציה כשהיא בחזית",
        "profiles.deleteHelp": "מחק את הפרופיל הזה מהאפליקציה",
        "profiles.dialMode": "חוגה: %1$@",
        "profiles.dialOnActivate": "חוגה בעת הפעלה",
        "profiles.dialUnchanged": "החוגה ללא שינוי",
        "profiles.dontChange": "אל תשנה",
        "profiles.enable": "הפעל",
        "profiles.freeSlots": "%1$@ חריצים פנויים",
        "profiles.hardwareNote": "המקלדת שומרת חמישה פרופילים בזיכרון (תפריט Profile של החוגה). לכל אחד תאורה, מיפויים ותמונות D1–D4 משלו; האפליקציה מוסיפה את פעולות המקשים, מצב החוגה והאפליקציות המקושרות. שנים־עשר המקשים של ה־DisplayPad נשמרים גם הם בכל פרופיל.",
        "profiles.header": "פרופיל %1$@",
        "profiles.iconAndColour": "סמל וצבע",
        "profiles.keyboardLighting": "תאורת המקלדת",
        "profiles.keyboardProfiles": "פרופילי מקלדת",
        "profiles.keysNote": "המקשים D1–D4 והתאורה מוגדרים בעמודים שלהם כל עוד הפרופיל הזה פעיל: הם נשמרים בפרופיל הזה.",
        "profiles.lightingFirmware": "תאורה: %1$@",
        "profiles.lightingMac": "תאורת Mac: %1$@",
        "profiles.linkedApps": "אפליקציות מקושרות",
        "profiles.manage": "ניהול…",
        "profiles.namePlaceholder": "תכנות, מוזיקה…",
        "profiles.noLinkedApp": "אין אפליקציה מקושרת",
        "profiles.otherwise": "אחרת, חזור אל",
        "profiles.slot": "חריץ %1$@",
        "profiles.slotOf": "פרופיל %1$@ מתוך %2$@",

        // MARK: reset
        "reset.title": "איפוס",

        // MARK: section
        "section.buttons.subtitle": "פעולת macOS על כל אחד מארבעת מקשי התצוגה",
        "section.buttons.title": "מקשים D1–D4",
        "section.displays.subtitle": "המסך העגול של החוגה ומקשי התצוגה של מקלדת המספרים",
        "section.displays.title": "מסכים",
        "section.keyboard.subtitle": "פריסת המקלדת שזוהתה ופריסת macOS התואמת",
        "section.keyboard.title": "פריסה",
        "section.lighting.subtitle": "אפקטים רשמיים של המקלדת ואפקטים דינמיים שמחושבים על ידי ה-Mac",
        "section.overview.subtitle": "ה-Everest Max שלך במבט אחד",
        "section.overview.title": "סקירה",
        "section.profiles.subtitle": "חמישה פרופילים השמורים במקלדת, לכל אחד מקשים, תאורה ואפליקציות משלו",
        "section.profiles.title": "פרופילים",
        "section.system.subtitle": "daemon המקשים, ניטור ופתרון בעיות",
        "section.system.title": "מערכת",

        // MARK: settings
        "settings.language.automatic": "אוטומטי (שפת המערכת)",
        "settings.language.note": "שפת הממשק, תפריט שורת התפריטים וההודעות.",
        "settings.language.title": "שפה",

        // MARK: status
        "status.animationPaused": "האנימציה מושהית — המקלדת שומרת את הפריים האחרון.",
        "status.appIconUnreadable": "לא ניתן לקרוא את הסמל של האפליקציה.",
        "status.appNoId": "לאפליקציה הזו אין מזהה: אי אפשר לקשר אותה.",
        "status.changeFailed": "לא ניתן לשנות: %1$@",
        "status.cleaning": "מנקה",
        "status.clockSynced": "השעון סונכרן עם ה-Mac.",
        "status.configSaved": "ההגדרות נשמרו.",
        "status.daemonOff": "המקשים D1–D4 כבויים.",
        "status.daemonOn": "המקשים D1–D4 פעילים.",
        "status.daemonStartFailed": "לא ניתן להפעיל את ה-daemon: %1$@",
        "status.dialImageSent": "התמונה נשלחה לחוגה.",
        "status.dialMode": "חוגה: %1$@.",
        "status.displayLabel": "מסך",
        "status.effectApplied": "%1$@ הוחל ונשמר בפרופיל.",
        "status.effectRunningKeyboard": "האפקט “%1$@” פועל על המקלדת.",
        "status.factoryIconRestored": "סמל היצרן שוחזר ב-%1$@.",
        "status.frozen": "הפריים נקבע ונשמר בחריץ “Custom” של המקלדת.",
        "status.iconDrawFailed": "לא ניתן לצייר את הסמל.",
        "status.iconSent": "הסמל נשלח ל-%1$@ תוך %2$@ שניות.",
        "status.keyboardConnected": "המקלדת מחוברת.",
        "status.keyboardGone": "המקלדת מנותקת — האפקט יימשך כשתחובר מחדש.",
        "status.layoutAuto": "פריסה: זיהוי אוטומטי.",
        "status.layoutForced": "פריסה נקבעה ידנית: %1$@.",
        "status.leftoversCleared": "פעולות שנותרו נמחקו מזיכרון המקלדת.",
        "status.loginApproval": "יש לאשר בהגדרות המערכת ← כללי ← פריטי כניסה.",
        "status.previewOnly": "המקלדת לא נמצאה — התצוגה המקדימה עדיין זמינה.",
        "status.profileActivated": "הפרופיל “%1$@” הופעל.",
        "status.profileActivatedFrontApp": "הפרופיל “%1$@” הופעל (האפליקציה בחזית).",
        "status.profileFromKeyboard": "הפרופיל “%1$@” פעיל (נבחר במקלדת).",
        "status.profileRemoved": "הפרופיל הוסר מהאפליקציה (המקלדת שומרת את ההגדרות שלה בחריץ %1$@).",
        "status.ready": "מוכן",
        "status.recovering": "שחזור",
        "status.recoverySent": "רצף השחזור נשלח.",
        "status.saving": "שומר",
        "status.sendingImage": "שולח את התמונה…",
        "status.uploadBusy": "העברה מתבצעת ב-%1$@ — המתן כמה שניות.",
        "status.uploadBusyAlready": "כבר מתבצעת העברה ב-%1$@ — המתן כמה שניות.",
        "status.uploadFailed": "ההעברה נכשלה: %1$@",
        "status.uploadFailedKey": "%1$@: ההעברה נכשלה — %2$@",
        "status.uploadStarted": "%1$@: שולח את התמונה למקלדת…",

        // MARK: system
        "system.askAgain": "שאל שוב",
        "system.autoDaemon": "הפעל את המקשים D1–D4 אוטומטית",
        "system.autoDaemonNote": "ה-daemon מתחיל עם האפליקציה, מתחבר מחדש בעצמו כשהמקלדת מחוברת שוב, ומופעל מחדש אם הוא נעצר.",
        "system.autostartHint": "הפעלה אוטומטית בעת כניסה: ‎./install-daemon.sh מה-Terminal.",
        "system.background": "Everest פועל ברקע, משורת התפריטים",
        "system.daemonSubtitle": "מריץ את פעולות D1–D4 ושולח ערכים לחוגה",
        "system.daemonTitle": "daemon המקשים",
        "system.keepRunning": "השאר את Everest פועל כשאני סוגר את החלון",
        "system.keepRunningNote": "המקשים D1–D4, הפרופילים והאפקטים ממשיכים לעבוד; הסמל נשאר בשורת התפריטים. ליציאה: תפריט הסמל או ⌘Q.",
        "system.keyboardCard": "מקלדת",
        "system.keyboardCardNote": "מצב שדווח על ידי הקושחה",
        "system.launchAtLogin": "הפעל את Everest בעת כניסה",
        "system.launchAtLoginNote": "מתחיל בשקט בשורת התפריטים, בלי לפתוח את החלון.",
        "system.launchedFrom": "Everest פועל מ-%1$@. להפעלה אמינה, העתק אותו אל /Applications (‎./make-app.sh --install): כונן חיצוני לא תמיד מחובר בעת הכניסה.",
        "system.lightProfile": "פרופיל תאורה",
        "system.listening": "מאזין",
        "system.metricsEvery": "ה-daemon שולח את הערכים כל 0.5 שניות בזמן שהוא פועל.",
        "system.modules": "מודולים",
        "system.monitoring": "ניטור",
        "system.monitoringNote": "ערכי מערכת שמוצגים בחוגה",
        "system.noAccessibility": "ל-Everest אין הרשאת נגישות",
        "system.noAccessibilityNote": "בלעדיה, הפעולות “קיצור דרך” ו“טקסט” לא עושות דבר (פעולות אפליקציה, פקודה וקישור כן עובדות). אם Everest כבר מסומן ברשימה, הרשומה מיושנת: בחר בה, הסר אותה באמצעות “−”, הוסף אותה שוב באמצעות “+” (Everest.app) והפעל מחדש את ה-daemon.",
        "system.openSettings": "פתח הגדרות",
        "system.sendMetrics": "שלח CPU, GPU, RAM, דיסק, רשת ועוצמת שמע",
        "system.stoppedState": "נעצר",
        "system.unlock": "שחרור המקלדת",
        "system.unlockNote": "“שחרור” שולח את איפוס ה-SDK אם העברת תמונה הופסקה. אם זה לא מספיק, נתק וחבר את המקלדת מחדש: דבר לא הולך לאיבוד.",

        // MARK: upload
        "upload.phase.connect": "מתחבר למקלדת",
        "upload.phase.done": "הושלם",
        "upload.phase.finish": "מסיים",
        "upload.phase.prepare": "המקלדת מכינה את החריץ",
        "upload.phase.send": "שולח את התמונה",

        "status.configReloaded": "ההגדרות שונו מחוץ לאפליקציה ונטענו מחדש.",

        // MARK: pad
        "action.profile": "פרופיל",
        "profileAction.next": "הפרופיל הבא",
        "profileAction.previous": "הפרופיל הקודם",
        "profiles.newCopyPad": "חדש, עם מקשי ה־DisplayPad של „%1$@”",
        "pad.status.swapped": "%1$@ ו־%2$@ הוחלפו.",
        "keyappearance.live": "בזמן אמת",
        "keyappearance.liveAction": "לפתוח גם את האפליקציה המתאימה",
        "keyappearance.liveNote": "מצויר מחדש בכל שינוי בערך (לכל היותר פעם בשנייה) כל עוד המשטח מחובר. המקש שומר על הפעולה שלו.",
        "pad.keysActive": "מקשי P1–P12 פעילים",
        "pad.overview.keys": "%1$@ מתוך 12 מקשים הוגדרו",
        "pad.overview.firmware": "קושחה %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "קושחת DisplayPad %1$@ אינה נתמכת",
        "pad.unsupportedNote": "Everest כותב רק לקושחה 8, הגרסה שנבדקה, ומשאיר את המשטח הזה בשקט.",
        "pad.noAnswer": "ה־DisplayPad לא מגיב",
        "pad.noAnswerNote": "הוא מחובר אך לא עונה: המתינו כמה שניות, או חברו אותו ישירות ל־Mac.",
        "section.displaypad.subtitle": "שנים־עשר מקשי מסך, לכל אחד תמונה ופעולת macOS",
        "pad.connected": "DisplayPad מחובר",
        "pad.connectedNote": "התמונות נשלחות תוך שנייה מכל שינוי; המשטח שומר אותן עד שמנתקים אותו.",
        "pad.notConnected": "DisplayPad לא מחובר",
        "pad.notConnectedNote": "חברו אותו ישירות ל־Mac: בחלק ממפצלי ה־USB המסך נשאר שחור.",
        "pad.brightness": "בהירות",
        "pad.keys": "מקשים",
        "pad.keysNote": "לחצו על מקש כדי לערוך אותו, או גררו אותו אל מקש אחר כדי להחליף ביניהם. התמונות והפעולות נשמרות בפרופיל „%1$@”.",
        "pad.clearKey": "ניקוי",
        "pad.clearKeyHelp": "מסיר את התמונה והפעולה של %1$@",
        "pad.noImage": "ללא תמונה",
        "pad.ownImageNote": "התמונה נחתכת במרכז ומוקטנת ל־102 × 102. הפעולה של המקש לא משתנה.",
        "pad.daemonStoppedNote": "מקשי ה־DisplayPad פועלים רק כשהוא פועל.",
        "pad.status.sent": "%1$@: נשלח ל־DisplayPad.",
        "pad.status.savedOffline": "%1$@: נשמר — יוצג כשה־DisplayPad יחובר.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
