// Interface strings — pt. Generated from the spec once, now edited by hand.
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let pt: [String: String] = [
        // MARK: action
        "action.app": "Aplicativo",
        "action.keypress": "Atalho",
        "action.none": "Nenhuma",
        "action.open": "Arquivo",
        "action.shell": "Comando",
        "action.text": "Texto",
        "action.textToType": "Texto a digitar",
        "action.url": "Link",

        // MARK: app
        "app.closeWindow": "Fechar janela",
        "app.copy": "Copiar",
        "app.cut": "Cortar",
        "app.edit": "Editar",
        "app.hide": "Ocultar o Everest",
        "app.paste": "Colar",
        "app.quit": "Sair do Everest",
        "app.selectAll": "Selecionar tudo",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "As ações do macOS e os atalhos digitados exigem a permissão de Acessibilidade (Ajustes → Privacidade e segurança).",
        "buttons.actionRan": "Ação de %1$@ executada.",
        "buttons.appHint": "Abre o app ou o traz para a frente",
        "buttons.clearLeftovers": "Apagar ações residuais",
        "buttons.daemonStopped": "O daemon está parado",
        "buttons.daemonStoppedNote": "As ações só são executadas enquanto ele escuta as teclas D1–D4.",
        "buttons.factoryValues": "Valores de fábrica",
        "buttons.factoryValuesHelp": "Restaura a imagem e a ação originais de %1$@",
        "buttons.flashMemory": "Memória do teclado",
        "buttons.flashMemoryNote": "O Base Camp pode deixar ações na memória flash (ex.: D4 enviando Esc)",
        "buttons.keyHeader": "TECLA %1$@",
        "buttons.noAction": "Nenhuma ação — a tecla é ignorada.",
        "buttons.noApp": "Nenhum app escolhido",
        "buttons.pickPresetAppImage": "Predefinição, app ou imagem para %1$@",
        "buttons.presetsAndIcon": "Predefinições e ícone…",

        // MARK: clock
        "clock.analog": "Analógico",
        "clock.digital": "Digital",
        "clock.sync": "Sincronizar",

        // MARK: colormode
        "colormode.dual": "Duas cores",
        "colormode.quad": "4 cores",
        "colormode.rainbow": "Arco-íris",
        "colormode.single": "Uma cor",
        "colormode.withBackground": "Tecla + fundo",

        // MARK: common
        "common.active": "Ativo",
        "common.add": "Novo",
        "common.choose": "Escolher…",
        "common.close": "Fechar",
        "common.configure": "Configurar",
        "common.delete": "Excluir",
        "common.edit": "Editar",
        "common.name": "Nome",
        "common.other": "Outro…",
        "common.refresh": "Atualizar",
        "common.remove": "Remover",
        "common.start": "Iniciar",
        "common.stop": "Parar",
        "common.test": "Testar",

        // MARK: daemon
        "daemon.keysActive": "Teclas D1–D4 ativas",
        "daemon.stopped": "Daemon parado",

        // MARK: device
        "device.blocked": "Firmware sem suporte",
        "device.connected": "Conectado",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Desconectado",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Everest Max completo",
        "device.keyboardMissing": "teclado indisponível",
        "device.keyboardUnavailable": "Teclado indisponível (não encontrado ou firmware sem suporte).",
        "device.notConnected": "Não conectado",
        "device.refresh.help": "Atualizar o estado do teclado",
        "device.withDock": "Teclado + dock de mídia",
        "device.withNumpad": "Teclado + teclado numérico",

        // MARK: displays
        "displays.change": "Alterar…",
        "displays.chooseImage": "Escolher uma imagem…",
        "displays.dial.subtitle": "Tela redonda de 240 × 204 do dock de mídia",
        "displays.display": "Exibição",
        "displays.factoryIcon": "Ícone de fábrica",
        "displays.factoryLogo": "Logo de fábrica",
        "displays.imageCropped": "A imagem é recortada para 240 × 204.",
        "displays.imagesResized": "As imagens são redimensionadas para 72 × 72.",
        "displays.keys.subtitle": "Quatro telas de 72 × 72 acima do teclado numérico",
        "displays.keys.title": "Teclas com tela",
        "displays.logoRestored": "Logo da Mountain restaurado no dial.",
        "displays.metricsNote": "CPU, GPU, RAM, disco, rede e volume mostram os valores enviados pelo daemon (página Sistema).",

        // MARK: factory
        "factory.activityMonitor": "Monitor de Atividade",
        "factory.sleep": "Repouso",

        // MARK: firmware
        "firmware.block.body": "O Everest só foi testado com o firmware %1$@. Para não correr o risco de inutilizar o seu teclado, ele não envia nada enquanto não for essa versão: nem iluminação, nem imagens, nem ações.",
        "firmware.block.check": "Verificar novamente",
        "firmware.block.detected": "Firmware detectado: %1$@",
        "firmware.block.how": "A Mountain só oferece a atualização de firmware em seu aplicativo oficial Base Camp para Windows. Conecte o teclado a um PC com Windows, instale o Base Camp, atualize o firmware e reconecte o teclado a este Mac: o Everest o detecta sozinho.",
        "firmware.block.howTitle": "Como atualizar o teclado",
        "firmware.block.tested": "Firmware testado: %1$@",
        "firmware.block.title": "Firmware sem suporte",
        "firmware.block.unreadableBody": "O Everest não consegue verificar a versão do firmware do teclado, então não mexe nele. Desconecte e reconecte o teclado e tente novamente.",
        "firmware.block.unreadableTitle": "Firmware ilegível",
        "firmware.block.why": "O Everest não atualiza o firmware por conta própria: é o mesmo tipo de operação que pode inutilizar um teclado e não pode ser testada aqui.",
        "firmware.status.unreadable": "O teclado não informou o firmware — ele não é modificado.",
        "firmware.status.unsupported": "Firmware %1$@ sem suporte (testado: %2$@) — o teclado não é modificado.",

        // MARK: fx
        "fx.breathing": "Respiração",
        "fx.breathing.desc": "Pulsação suave",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Gotas que caem",
        "fx.off": "Desligado",
        "fx.off.desc": "Tudo apagado",
        "fx.reactive": "Reativo",
        "fx.reactive.desc": "Acende ao digitar",
        "fx.static": "Estático",
        "fx.static.desc": "Cor fixa",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Gira em torno do centro",
        "fx.wave": "Onda",
        "fx.wave.desc": "Atravessa o teclado",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Onda a partir da tecla",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Aplicar também a ação da predefinição",
        "keyappearance.appHint": "A tecla abre o app ou o traz para a frente se já estiver aberto.",
        "keyappearance.apps": "Aplicativos",
        "keyappearance.background": "Continuar em segundo plano",
        "keyappearance.busyOther": "Há um envio em andamento em %1$@ — espere terminar para alterar esta tecla.",
        "keyappearance.chooseFile": "Escolher um arquivo…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Abre o app",
        "keyappearance.ownImage": "Sua própria imagem",
        "keyappearance.ownImageNote": "Ela é recortada no centro e redimensionada para 72 × 72. A ação da tecla não muda.",
        "keyappearance.presets": "Predefinições",
        "keyappearance.searchApp": "Procurar um app",
        "keyappearance.step.prepare": "Preparação",
        "keyappearance.step.send": "Envio",
        "keyappearance.subtitle": "Escolha o que a tela mostra e o que a tecla faz",
        "keyappearance.title": "Tecla %1$@",
        "keyappearance.transferNote": "Um envio leva cerca de 20 segundos: o teclado prepara o slot (ele mesmo apaga a imagem antiga) e depois recebe a nova em pacotes de 64 bytes. Não desconecte o teclado.",

        // MARK: keyboard
        "keyboard.activeBadge": "ATIVO",
        "keyboard.ansiShape": "Formato ANSI: Enter largo, \\ no fim da fileira de cima",
        "keyboard.asPrinted": "como impresso",
        "keyboard.automatic": "Automático",
        "keyboard.chosen": "ESCOLHIDO À MÃO",
        "keyboard.clearRemaps": "Apagar remapeamentos",
        "keyboard.detected": "DETECTADO",
        "keyboard.hidutilNote": "hidutil: uso 0x64 → 0x31. Dura até reiniciar. Para um remapeamento salvo no teclado: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "tecla ISO",
        "keyboard.isoMuteNote": "Se o macOS tratar o teclado como ANSI, a tecla à esquerda do Z não produz nada",
        "keyboard.isoMuteTitle": "Tecla ISO muda?",
        "keyboard.isoShape": "Formato ISO: Enter alto, tecla extra à esquerda de W/Z",
        "keyboard.legend.at": "@ na tecla '",
        "keyboard.legend.backslash": "\\ | à esquerda do Z",
        "keyboard.legend.quote": "\" em ⇧2",
        "keyboard.legend.rightOfSemicolon": "à direita de ;",
        "keyboard.macLayout": "Layout do macOS",
        "keyboard.macLayoutNote": "Para que o macOS digite o que está impresso nas teclas",
        "keyboard.noMacLayout": "Nenhum layout do macOS correspondente a “%1$@” está instalado: adicione-o em Ajustes do Sistema → Teclado → Fontes de entrada.",
        "keyboard.remapApplied": "Remapeamento ISO aplicado (até reiniciar).",
        "keyboard.remapIso": "Remapear a tecla ISO",
        "keyboard.remapsCleared": "Remapeamentos do hidutil apagados.",
        "keyboard.reportsLayout": "O teclado informa “%1$@”. Volte ao automático se esta escolha não for mais necessária.",
        "keyboard.switchedTo": "Layout alterado para %1$@.",
        "keyboard.title": "Teclado físico",
        "keyboard.titleNote": "Lido do teclado, como o Base Camp: o desenho, as teclas e os efeitos se adaptam a ele",
        "keyboard.unknown": "desconhecida",
        "keyboard.use": "Usar %1$@",
        "keyboard.verifiedNote1": "O formato e a iluminação de cada tecla seguem a grade do teclado; apenas o layout UK foi verificado em um teclado real.",
        "keyboard.verifiedNote2": "As legendas vêm das tabelas do Base Camp e o formato segue a grade de LEDs; apenas o layout UK foi verificado em um teclado real.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "a transferência para o dial foi interrompida — use “Desbloquear o teclado” (página Sistema) ou reconecte-o",
        "keyboardError.dialRefused": "o dial recusou o envio (nada foi gravado)",
        "keyboardError.interrupted": "transferência interrompida — use “Desbloquear o teclado” (página Sistema) ou reconecte-o",
        "keyboardError.refused": "o teclado recusou o envio (nada foi gravado) — tente de novo; se persistir, use “Desbloquear o teclado” (página Sistema)",
        "keyboardError.selectTarget": "o teclado não responde à seleção das teclas — use “Desbloquear o teclado” (página Sistema) ou reconecte-o",

        // MARK: layout
        "layout.french": "Francês (AZERTY)",
        "layout.german": "Alemão (QWERTZ)",
        "layout.hebrew": "Hebraico",
        "layout.italian": "Italiano",
        "layout.korean": "Coreano",
        "layout.nordic": "Nórdico",
        "layout.portuguese": "Português",
        "layout.spanish": "Espanhol",
        "layout.uk": "Reino Unido (ISO)",
        "layout.us": "EUA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Adicionar uma cor",
        "lighting.allHues": "Todos os tons, gerados pelo teclado.",
        "lighting.backgroundColour": "Fundo",
        "lighting.brightness": "Brilho",
        "lighting.byKeyboard": "Executado pelo teclado — continua sem o app",
        "lighting.byMac": "Calculado pelo Mac — mantenha o app aberto",
        "lighting.clearAll": "Limpar tudo",
        "lighting.clockwise": "Horário",
        "lighting.colors": "Cores",
        "lighting.colour": "Cor",
        "lighting.colour1": "Cor 1",
        "lighting.colour2": "Cor 2",
        "lighting.colourCount.one": "%1$@ cor",
        "lighting.colourCount.other": "%1$@ cores",
        "lighting.counterclockwise": "Anti-horário",
        "lighting.direction": "Direção",
        "lighting.editEllipsis": "Editar…",
        "lighting.fast": "Rápido",
        "lighting.flameNote": "Rampa de chama fixa, da brasa ao branco.",
        "lighting.freeze": "Fixar no teclado",
        "lighting.freezeNote": "Envia o quadro atual ao slot Custom e o salva: ele permanece sem o app.",
        "lighting.keyColour": "Tecla",
        "lighting.ledsBlack": "Todos os LEDs ficam pretos enquanto o efeito é executado.",
        "lighting.macNote": "Renderizados tecla por tecla a 30 quadros/s, com a sua paleta",
        "lighting.normal": "Normal",
        "lighting.offNote": "A retroiluminação e as faixas laterais estão apagadas. Escolha outro efeito para acendê-las novamente.",
        "lighting.officialEffects": "Efeitos oficiais",
        "lighting.officialNote": "Os efeitos do Base Camp, enviados exatamente como o app do Windows",
        "lighting.paintHint": "Clique ou arraste sobre as teclas do teclado acima.",
        "lighting.paintKeys": "Pintar tecla por tecla",
        "lighting.palette": "Paleta",
        "lighting.paused": "Em pausa",
        "lighting.reapply": "Aplicar novamente",
        "lighting.rightClickHint": "Clique com o botão direito em uma amostra para removê-la.",
        "lighting.rotation": "Sentido de rotação",
        "lighting.runningOnKeyboard": "Em execução no teclado",
        "lighting.savedInProfile": "Salvo no perfil ativo do teclado",
        "lighting.slow": "Lento",
        "lighting.speed": "Velocidade",
        "lighting.title": "Iluminação",

        // MARK: live
        "live.keyboard": "Teclado · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · em pausa",
        "live.pause": "Pausar",
        "live.start": "Iniciar",

        // MARK: macfx
        "macfx.aurora": "Aurora",
        "macfx.equalizer": "Equalizador",
        "macfx.fire": "Fogo",
        "macfx.gradient": "Degradê",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Chuva digital",
        "macfx.ripples": "Ondulações",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Cor sólida",
        "macfx.spectrum": "Espectro",
        "macfx.spiral": "Espiral",
        "macfx.stars": "Estrelas",
        "macfx.waves": "Ondas",

        // MARK: menu
        "menu.allowAccessibility": "Permitir acessibilidade…",
        "menu.disconnected": "Teclado desconectado",
        "menu.firmwareBlocked": "Firmware sem suporte — teclado ignorado",
        "menu.keyboardEffects": "Efeitos do teclado",
        "menu.launchAtLogin": "Abrir ao iniciar a sessão",
        "menu.macEffects": "Efeitos do Mac",
        "menu.manageProfiles": "Gerenciar perfis…",
        "menu.newProfile": "Novo perfil",
        "menu.open": "Abrir o Everest…",
        "menu.pauseEffect": "Pausar o efeito",
        "menu.profile": "Perfil: %1$@",
        "menu.resumeEffect": "Retomar o efeito",

        // MARK: metric
        "metric.disk": "DISCO",
        "metric.network": "REDE",
        "metric.volume": "VOLUME",

        // MARK: mode
        "mode.clock": "Relógio",
        "mode.disk": "Disco",
        "mode.image": "Imagem",
        "mode.network": "Rede",
        "mode.volume": "Volume",

        // MARK: overview
        "overview.actionsActive": "Ações ativas",
        "overview.changeLighting": "Alterar a iluminação",
        "overview.dialSubtitle": "Tela redonda do dock de mídia",
        "overview.keyboardEffect": "Efeito do teclado",
        "overview.macEffect": "Efeito calculado pelo Mac",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Brasa",
        "palette.forest": "Floresta",
        "palette.ice": "Gelo",
        "palette.neon": "Néon",
        "palette.ocean": "Oceano",
        "palette.sunset": "Pôr do sol",
        "palette.vapor": "Vapor",

        // MARK: preset
        "preset.bolt": "Raio",
        "preset.calendar": "Calendário",
        "preset.captureScreen": "Captura de tela",
        "preset.captureZone": "Captura de área",
        "preset.category.apps": "Apps",
        "preset.category.decor": "Só ícone",
        "preset.category.media": "Mídia",
        "preset.coffee": "Café",
        "preset.flame": "Chama",
        "preset.game": "Controle",
        "preset.heart": "Coração",
        "preset.home": "Casa",
        "preset.lock": "Bloquear",
        "preset.music": "Música",
        "preset.mute": "Silenciar",
        "preset.next": "Próxima",
        "preset.playpause": "Reproduzir / Pausar",
        "preset.previous": "Anterior",
        "preset.sleepDisplay": "Desligar a tela",
        "preset.star": "Estrela",
        "preset.volumeDown": "Volume −",
        "preset.volumeUp": "Volume +",

        // MARK: profile
        "profile.defaultName": "Perfil %1$@",
        "profile.main": "Principal",

        // MARK: profiles
        "profiles.addApp": "Adicionar um app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Troca automática",
        "profiles.autoSwitchHint": "Funciona enquanto o app está aberto ou o daemon em execução. Um perfil escolhido à mão no dial não é substituído enquanto você permanecer em um app sem perfil.",
        "profiles.autoSwitchNote": "O teclado muda para o perfil de um app quando ele está em primeiro plano",
        "profiles.deleteHelp": "Excluir este perfil do app",
        "profiles.dialMode": "Dial: %1$@",
        "profiles.dialOnActivate": "Dial ao ativar",
        "profiles.dialUnchanged": "Dial inalterado",
        "profiles.dontChange": "Não alterar",
        "profiles.enable": "Ativar",
        "profiles.freeSlots": "%1$@ slot(s) livre(s)",
        "profiles.hardwareNote": "O teclado guarda cinco perfis na memória (menu Profile do dial). Cada um tem sua iluminação, seus remapeamentos e suas imagens D1–D4; o app adiciona as ações das teclas, o modo do dial e os apps vinculados. As doze teclas do DisplayPad também são guardadas em cada perfil.",
        "profiles.header": "PERFIL %1$@",
        "profiles.iconAndColour": "Ícone e cor",
        "profiles.keyboardLighting": "Iluminação do teclado",
        "profiles.keyboardProfiles": "PERFIS DO TECLADO",
        "profiles.keysNote": "As teclas D1–D4 e a iluminação são ajustadas em suas páginas enquanto este perfil está ativo: elas são salvas neste perfil.",
        "profiles.lightingFirmware": "Iluminação: %1$@",
        "profiles.lightingMac": "Iluminação do Mac: %1$@",
        "profiles.linkedApps": "Apps vinculados",
        "profiles.manage": "Gerenciar…",
        "profiles.namePlaceholder": "Programação, Música…",
        "profiles.noLinkedApp": "Nenhum app vinculado",
        "profiles.otherwise": "Caso contrário, voltar para",
        "profiles.slot": "Slot %1$@",
        "profiles.slotOf": "Perfil %1$@ de %2$@",

        // MARK: reset
        "reset.title": "Redefinição",

        // MARK: section
        "section.buttons.subtitle": "Uma ação do macOS em cada uma das quatro teclas com tela",
        "section.buttons.title": "Teclas D1–D4",
        "section.displays.subtitle": "Tela redonda do dial e teclas com tela do teclado numérico",
        "section.displays.title": "Telas",
        "section.keyboard.subtitle": "Layout do teclado detectado e o layout do macOS correspondente",
        "section.keyboard.title": "Layout",
        "section.lighting.subtitle": "Efeitos oficiais do teclado e efeitos dinâmicos calculados pelo Mac",
        "section.overview.subtitle": "Seu Everest Max num relance",
        "section.overview.title": "Visão geral",
        "section.profiles.subtitle": "Cinco perfis no teclado, cada um com suas teclas, iluminação e apps",
        "section.profiles.title": "Perfis",
        "section.system.subtitle": "Daemon dos botões, monitoramento e solução de problemas",
        "section.system.title": "Sistema",

        // MARK: settings
        "settings.language.automatic": "Automático (idioma do sistema)",
        "settings.language.note": "Idioma da interface, do menu da barra de menus e das mensagens.",
        "settings.language.title": "Idioma",

        // MARK: status
        "status.animationPaused": "Animação em pausa — o teclado mantém o último quadro.",
        "status.appIconUnreadable": "Não foi possível ler o ícone do app.",
        "status.appNoId": "Este app não tem identificador: não é possível vinculá-lo.",
        "status.changeFailed": "Não foi possível alterar: %1$@",
        "status.cleaning": "Limpeza",
        "status.clockSynced": "Relógio sincronizado com o Mac.",
        "status.configSaved": "Configurações salvas.",
        "status.daemonOff": "Teclas D1–D4 desativadas.",
        "status.daemonOn": "Teclas D1–D4 ativas.",
        "status.daemonStartFailed": "Não foi possível iniciar o daemon: %1$@",
        "status.dialImageSent": "Imagem enviada ao dial.",
        "status.dialMode": "Dial: %1$@.",
        "status.displayLabel": "Tela",
        "status.effectApplied": "%1$@ aplicado e salvo no perfil.",
        "status.effectRunningKeyboard": "Efeito “%1$@” em execução no teclado.",
        "status.factoryIconRestored": "Ícone de fábrica restaurado em %1$@.",
        "status.frozen": "Quadro fixado e salvo no slot “Custom” do teclado.",
        "status.iconDrawFailed": "Não foi possível desenhar o ícone.",
        "status.iconSent": "Ícone enviado para %1$@ em %2$@ s.",
        "status.keyboardConnected": "Teclado conectado.",
        "status.keyboardGone": "Teclado desconectado — o efeito será retomado ao reconectar.",
        "status.layoutAuto": "Layout: detecção automática.",
        "status.layoutForced": "Layout forçado: %1$@.",
        "status.leftoversCleared": "Ações residuais apagadas da memória do teclado.",
        "status.loginApproval": "Precisa ser autorizado em Ajustes do Sistema → Geral → Itens de início.",
        "status.previewOnly": "Teclado não encontrado — a prévia continua disponível.",
        "status.profileActivated": "Perfil “%1$@” ativado.",
        "status.profileActivatedFrontApp": "Perfil “%1$@” ativado (app em primeiro plano).",
        "status.profileFromKeyboard": "Perfil “%1$@” ativo (escolhido no teclado).",
        "status.profileRemoved": "Perfil removido do app (o teclado mantém suas configurações no slot %1$@).",
        "status.ready": "Pronto",
        "status.recovering": "Recuperação",
        "status.recoverySent": "Sequência de recuperação enviada.",
        "status.saving": "Salvando",
        "status.sendingImage": "Enviando a imagem…",
        "status.uploadBusy": "Há um envio em andamento em %1$@ — aguarde alguns segundos.",
        "status.uploadBusyAlready": "Já há um envio em andamento em %1$@ — aguarde alguns segundos.",
        "status.uploadFailed": "Falha no envio: %1$@",
        "status.uploadFailedKey": "%1$@: falha no envio — %2$@",
        "status.uploadStarted": "%1$@: enviando a imagem ao teclado…",

        // MARK: system
        "system.askAgain": "Pedir novamente",
        "system.autoDaemon": "Ativar as teclas D1–D4 automaticamente",
        "system.autoDaemonNote": "O daemon inicia com o app, reconecta sozinho quando o teclado é reconectado e reinicia se parar.",
        "system.autostartHint": "Início automático ao iniciar a sessão: ./install-daemon.sh no seu Terminal.",
        "system.background": "O Everest funciona em segundo plano, a partir da barra de menus",
        "system.daemonSubtitle": "Executa as ações de D1–D4 e envia valores ao dial",
        "system.daemonTitle": "Daemon das teclas",
        "system.keepRunning": "Manter o Everest ativo ao fechar a janela",
        "system.keepRunningNote": "As teclas D1–D4, os perfis e os efeitos continuam funcionando; o ícone fica na barra de menus. Sair: menu do ícone ou ⌘Q.",
        "system.keyboardCard": "Teclado",
        "system.keyboardCardNote": "Estado informado pelo firmware",
        "system.launchAtLogin": "Abrir o Everest ao iniciar a sessão",
        "system.launchAtLoginNote": "Inicia discretamente na barra de menus, sem abrir a janela.",
        "system.launchedFrom": "O Everest está sendo executado de %1$@. Para um início confiável, copie-o para /Applications (./make-app.sh --install): um volume externo nem sempre está montado ao iniciar a sessão.",
        "system.lightProfile": "Perfil de luz",
        "system.listening": "Escutando",
        "system.metricsEvery": "O daemon envia os valores a cada 0,5 s enquanto está em execução.",
        "system.modules": "Módulos",
        "system.monitoring": "Monitoramento",
        "system.monitoringNote": "Valores do sistema exibidos no dial",
        "system.noAccessibility": "O Everest não tem a permissão de Acessibilidade",
        "system.noAccessibilityNote": "Sem ela, as ações “atalho” e “texto” não fazem nada (as ações de app, comando e link funcionam). Se o Everest já estiver marcado na lista, a entrada está desatualizada: selecione-a, remova-a com “−”, adicione-a de novo com “+” (Everest.app) e reinicie o daemon.",
        "system.openSettings": "Abrir ajustes",
        "system.sendMetrics": "Enviar CPU, GPU, RAM, disco, rede e volume",
        "system.stoppedState": "Parado",
        "system.unlock": "Desbloquear o teclado",
        "system.unlockNote": "“Desbloquear” envia a redefinição do SDK se uma transferência de imagem foi interrompida. Se não bastar, desconecte e reconecte o teclado: nada se perde.",

        // MARK: upload
        "upload.phase.connect": "Conectando ao teclado",
        "upload.phase.done": "Concluído",
        "upload.phase.finish": "Finalizando",
        "upload.phase.prepare": "O teclado está preparando o slot",
        "upload.phase.send": "Enviando a imagem",

        "status.configReloaded": "As definições foram alteradas fora da app e foram recarregadas.",

        // MARK: pad
        "action.profile": "Perfil",
        "profileAction.next": "Perfil seguinte",
        "profileAction.previous": "Perfil anterior",
        "profiles.newCopyPad": "Novo, com as teclas do DisplayPad de «%1$@»",
        "pad.status.swapped": "%1$@ e %2$@ trocadas.",
        "keyappearance.live": "Em direto",
        "keyappearance.liveAction": "Abrir também a app correspondente",
        "keyappearance.liveNote": "Redesenhado quando o valor muda (no máximo uma vez por segundo) enquanto o pad estiver ligado. A tecla mantém a sua ação.",
        "pad.keysActive": "Teclas P1–P12 ativas",
        "pad.overview.keys": "%1$@ de 12 teclas configuradas",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "O firmware %1$@ do DisplayPad não é suportado",
        "pad.unsupportedNote": "O Everest só escreve no firmware 8, a versão testada, e deixa este pad em paz.",
        "pad.noAnswer": "O DisplayPad não responde",
        "pad.noAnswerNote": "Está ligado mas não responde: aguarde alguns segundos ou ligue-o diretamente ao Mac.",
        "section.displaypad.subtitle": "Doze teclas com ecrã, cada uma com uma imagem e uma ação do macOS",
        "pad.connected": "DisplayPad ligado",
        "pad.connectedNote": "As imagens são enviadas menos de um segundo após cada alteração; o pad guarda-as até ser desligado.",
        "pad.notConnected": "DisplayPad não ligado",
        "pad.notConnectedNote": "Ligue-o diretamente ao Mac: em alguns hubs USB o ecrã fica preto.",
        "pad.brightness": "Brilho",
        "pad.keys": "Teclas",
        "pad.keysNote": "Clique numa tecla para a editar, ou arraste-a para outra para as trocar. Imagens e ações são guardadas no perfil «%1$@».",
        "pad.clearKey": "Limpar",
        "pad.clearKeyHelp": "Remove a imagem e a ação de %1$@",
        "pad.noImage": "Sem imagem",
        "pad.ownImageNote": "É recortada ao centro e redimensionada para 102 × 102. A ação da tecla não muda.",
        "pad.daemonStoppedNote": "As teclas do DisplayPad só funcionam enquanto ele estiver ativo.",
        "pad.status.sent": "%1$@: enviado para o DisplayPad.",
        "pad.status.savedOffline": "%1$@: guardado — aparece quando o DisplayPad for ligado.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
