// Interface strings — nb. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let nb: [String: String] = [
        // MARK: action
        "action.app": "App",
        "action.keypress": "Hurtigtast",
        "action.none": "Ingen",
        "action.open": "Fil",
        "action.shell": "Kommando",
        "action.text": "Tekst",
        "action.textToType": "Tekst som skal skrives",
        "action.url": "Lenke",

        // MARK: app
        "app.closeWindow": "Lukk vindu",
        "app.copy": "Kopier",
        "app.cut": "Klipp ut",
        "app.edit": "Rediger",
        "app.hide": "Skjul Everest",
        "app.paste": "Lim inn",
        "app.quit": "Avslutt Everest",
        "app.selectAll": "Velg alt",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS-handlinger og innskrevne hurtigtaster krever tillatelsen Tilgjengelighet (Innstillinger → Personvern og sikkerhet).",
        "buttons.actionRan": "Handlingen for %1$@ ble utført.",
        "buttons.appHint": "Åpner appen eller henter den frem",
        "buttons.clearLeftovers": "Fjern gjenværende handlinger",
        "buttons.daemonStopped": "Daemonen er stoppet",
        "buttons.daemonStoppedNote": "Handlinger kjører bare mens den lytter etter tastene D1–D4.",
        "buttons.factoryValues": "Fabrikkinnstillinger",
        "buttons.factoryValuesHelp": "Gjenoppretter det opprinnelige bildet og den opprinnelige handlingen for %1$@",
        "buttons.flashMemory": "Tastaturets minne",
        "buttons.flashMemoryNote": "Base Camp kan etterlate handlinger i flashminnet (f.eks. D4 som sender Esc)",
        "buttons.keyHeader": "TAST %1$@",
        "buttons.noAction": "Ingen handling — tasten ignoreres.",
        "buttons.noApp": "Ingen app valgt",
        "buttons.pickPresetAppImage": "Forhåndsinnstilling, app eller bilde for %1$@",
        "buttons.presetsAndIcon": "Forhåndsinnstillinger og ikon…",

        // MARK: clock
        "clock.analog": "Analog",
        "clock.digital": "Digital",
        "clock.sync": "Synkroniser",

        // MARK: colormode
        "colormode.dual": "To farger",
        "colormode.quad": "4 farger",
        "colormode.rainbow": "Regnbue",
        "colormode.single": "Én farge",
        "colormode.withBackground": "Tast + bakgrunn",

        // MARK: common
        "common.active": "Aktiv",
        "common.add": "Ny",
        "common.choose": "Velg…",
        "common.close": "Lukk",
        "common.configure": "Konfigurer",
        "common.delete": "Slett",
        "common.edit": "Rediger",
        "common.name": "Navn",
        "common.other": "Annet…",
        "common.refresh": "Oppdater",
        "common.remove": "Fjern",
        "common.start": "Start",
        "common.stop": "Stopp",
        "common.test": "Test",

        // MARK: daemon
        "daemon.keysActive": "Tastene D1–D4 aktive",
        "daemon.stopped": "Daemon stoppet",

        // MARK: device
        "device.blocked": "Firmware støttes ikke",
        "device.connected": "Tilkoblet",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Frakoblet",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Komplett Everest Max",
        "device.keyboardMissing": "tastaturet er ikke tilgjengelig",
        "device.keyboardUnavailable": "Tastaturet er ikke tilgjengelig (ikke funnet, eller firmware støttes ikke).",
        "device.notConnected": "Ikke tilkoblet",
        "device.refresh.help": "Oppdater tastaturets status",
        "device.withDock": "Tastatur + mediedokk",
        "device.withNumpad": "Tastatur + numerisk tastatur",

        // MARK: displays
        "displays.change": "Endre…",
        "displays.chooseImage": "Velg et bilde…",
        "displays.dial.subtitle": "Rund 240 × 204-skjerm på mediedokken",
        "displays.display": "Visning",
        "displays.factoryIcon": "Fabrikkikon",
        "displays.factoryLogo": "Fabrikklogo",
        "displays.imageCropped": "Bildet beskjæres til 240 × 204.",
        "displays.imagesResized": "Bilder skaleres til 72 × 72.",
        "displays.keys.subtitle": "Fire 72 × 72-skjermer over det numeriske tastaturet",
        "displays.keys.title": "Skjermtaster",
        "displays.logoRestored": "Mountain-logoen er gjenopprettet på dreieknappen.",
        "displays.metricsNote": "CPU, GPU, RAM, disk, nettverk og volum viser verdiene daemonen sender (siden System).",

        // MARK: factory
        "factory.activityMonitor": "Aktivitetsmonitor",
        "factory.sleep": "Hvile",

        // MARK: firmware
        "firmware.block.body": "Everest er bare testet med firmware %1$@. For å unngå enhver risiko for at tastaturet blir ubrukelig, sender det ingenting til det før det kjører den versjonen: ingen belysning, ingen bilder, ingen handlinger.",
        "firmware.block.check": "Sjekk på nytt",
        "firmware.block.detected": "Oppdaget firmware: %1$@",
        "firmware.block.how": "Mountain tilbyr bare firmwareoppdateringen i sin offisielle Base Camp-app for Windows. Koble tastaturet til en Windows-PC, installer Base Camp, oppdater firmwaren, og koble deretter tastaturet til denne Macen igjen: Everest oppdager det selv.",
        "firmware.block.howTitle": "Slik oppdaterer du tastaturet",
        "firmware.block.tested": "Testet firmware: %1$@",
        "firmware.block.title": "Firmware støttes ikke",
        "firmware.block.unreadableBody": "Everest kan ikke kontrollere tastaturets firmwareversjon og rører det derfor ikke. Koble fra og til tastaturet igjen, og prøv på nytt.",
        "firmware.block.unreadableTitle": "Firmware kan ikke leses",
        "firmware.block.why": "Everest oppdaterer ikke firmwaren selv: Det er samme type operasjon som kan gjøre et tastatur ubrukelig, og den kan ikke testes her.",
        "firmware.status.unreadable": "Tastaturet oppga ikke firmwaren sin — det blir latt være i fred.",
        "firmware.status.unsupported": "Firmware %1$@ støttes ikke (testet: %2$@) — tastaturet blir latt være i fred.",

        // MARK: fx
        "fx.breathing": "Pust",
        "fx.breathing.desc": "Myk pulsering",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Fallende dråper",
        "fx.off": "Av",
        "fx.off.desc": "Alt er slukket",
        "fx.reactive": "Reaktiv",
        "fx.reactive.desc": "Lyser opp når du skriver",
        "fx.static": "Statisk",
        "fx.static.desc": "Fast farge",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Roterer rundt midten",
        "fx.wave": "Bølge",
        "fx.wave.desc": "Sveiper over tastaturet",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Krusning fra tasten",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Bruk også forhåndsinnstillingens handling",
        "keyappearance.appHint": "Tasten åpner appen, eller henter den frem hvis den allerede er åpen.",
        "keyappearance.apps": "Apper",
        "keyappearance.background": "Fortsett i bakgrunnen",
        "keyappearance.busyOther": "En overføring pågår på %1$@ — vent til den er ferdig før du endrer denne tasten.",
        "keyappearance.chooseFile": "Velg en fil…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Åpner appen",
        "keyappearance.ownImage": "Ditt eget bilde",
        "keyappearance.ownImageNote": "Det beskjæres midt i og skaleres til 72 × 72. Tastens handling endres ikke.",
        "keyappearance.presets": "Forhåndsinnstillinger",
        "keyappearance.searchApp": "Søk etter en app",
        "keyappearance.step.prepare": "Forbereder",
        "keyappearance.step.send": "Sender",
        "keyappearance.subtitle": "Velg hva skjermen viser og hva tasten gjør",
        "keyappearance.title": "Tast %1$@",
        "keyappearance.transferNote": "En overføring tar omtrent 20 sekunder: Tastaturet forbereder plassen (det sletter selv det gamle bildet) og mottar deretter det nye i pakker på 64 byte. Ikke koble fra tastaturet.",

        // MARK: keyboard
        "keyboard.activeBadge": "AKTIV",
        "keyboard.ansiShape": "ANSI-form: bred Enter, \\ på slutten av øverste rad",
        "keyboard.asPrinted": "som trykt",
        "keyboard.automatic": "Automatisk",
        "keyboard.chosen": "VALGT MANUELT",
        "keyboard.clearRemaps": "Fjern omtilordninger",
        "keyboard.detected": "OPPDAGET",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. Varer til omstart. For en omtilordning lagret i tastaturet: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO-tast",
        "keyboard.isoMuteNote": "Hvis macOS behandler tastaturet som ANSI, gjør tasten til venstre for Z ingenting",
        "keyboard.isoMuteTitle": "Reagerer ikke ISO-tasten?",
        "keyboard.isoShape": "ISO-form: høy Enter, ekstra tast til venstre for Z",
        "keyboard.legend.at": "@ på tasten '",
        "keyboard.legend.backslash": "\\ | til venstre for Z",
        "keyboard.legend.quote": "\" på ⇧2",
        "keyboard.legend.rightOfSemicolon": "til høyre for ;",
        "keyboard.macLayout": "macOS-tastaturoppsett",
        "keyboard.macLayoutNote": "Slik at macOS skriver det som er trykt på tastene",
        "keyboard.noMacLayout": "Det er ikke installert noe macOS-oppsett som tilsvarer «%1$@»: Legg det til i Systeminnstillinger → Tastatur → Inndatakilder.",
        "keyboard.remapApplied": "ISO-omtilordning brukt (til omstart).",
        "keyboard.remapIso": "Omtilordne ISO-tasten",
        "keyboard.remapsCleared": "hidutil-omtilordninger fjernet.",
        "keyboard.reportsLayout": "Tastaturet melder «%1$@». Gå tilbake til automatisk hvis valget ikke lenger trengs.",
        "keyboard.switchedTo": "Oppsettet ble endret til %1$@.",
        "keyboard.title": "Fysisk tastatur",
        "keyboard.titleNote": "Leses fra tastaturet, som i Base Camp: Tegningen, tastene og effektene tilpasses",
        "keyboard.unknown": "ukjent",
        "keyboard.use": "Bruk %1$@",
        "keyboard.verifiedNote1": "Formen og belysningen til hver tast følger tastaturets rutenett; bare UK-oppsettet er verifisert på et ekte tastatur.",
        "keyboard.verifiedNote2": "Tastetekstene kommer fra Base Camps tabeller, og formen følger LED-rutenettet; bare UK-oppsettet er verifisert på et ekte tastatur.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "overføringen til dreieknappen ble avbrutt — bruk «Lås opp tastaturet» (siden System) eller koble det til på nytt",
        "keyboardError.dialRefused": "dreieknappen avviste overføringen (ingenting ble skrevet)",
        "keyboardError.interrupted": "overføringen ble avbrutt — bruk «Lås opp tastaturet» (siden System) eller koble det til på nytt",
        "keyboardError.refused": "tastaturet avviste overføringen (ingenting ble skrevet) — prøv igjen; hvis det vedvarer, bruk «Lås opp tastaturet» (siden System)",
        "keyboardError.selectTarget": "tastaturet svarer ikke på tastevalget — bruk «Lås opp tastaturet» (siden System) eller koble det til på nytt",

        // MARK: layout
        "layout.french": "Fransk (AZERTY)",
        "layout.german": "Tysk (QWERTZ)",
        "layout.hebrew": "Hebraisk",
        "layout.italian": "Italiensk",
        "layout.korean": "Koreansk",
        "layout.nordic": "Nordisk",
        "layout.portuguese": "Portugisisk",
        "layout.spanish": "Spansk",
        "layout.uk": "Storbritannia (ISO)",
        "layout.us": "USA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Legg til en farge",
        "lighting.allHues": "Alle nyanser, generert av tastaturet.",
        "lighting.backgroundColour": "Bakgrunn",
        "lighting.brightness": "Lysstyrke",
        "lighting.byKeyboard": "Kjøres av tastaturet — fortsetter uten appen",
        "lighting.byMac": "Beregnes av Macen — hold appen åpen",
        "lighting.clearAll": "Fjern alt",
        "lighting.clockwise": "Med klokken",
        "lighting.colors": "Farger",
        "lighting.colour": "Farge",
        "lighting.colour1": "Farge 1",
        "lighting.colour2": "Farge 2",
        "lighting.colourCount.one": "%1$@ farge",
        "lighting.colourCount.other": "%1$@ farger",
        "lighting.counterclockwise": "Mot klokken",
        "lighting.direction": "Retning",
        "lighting.editEllipsis": "Rediger…",
        "lighting.fast": "Rask",
        "lighting.flameNote": "Fast flammeskala, fra glo til hvit.",
        "lighting.freeze": "Lås fast i tastaturet",
        "lighting.freezeNote": "Sender gjeldende bilde til Custom-plassen og lagrer det: Det blir værende uten appen.",
        "lighting.keyColour": "Tast",
        "lighting.ledsBlack": "Alle LED-ene er svarte mens effekten kjører.",
        "lighting.macNote": "Beregnet tast for tast med 30 bilder/s, med paletten din",
        "lighting.normal": "Normal",
        "lighting.offNote": "Bakgrunnsbelysningen og sidestripene er av. Velg en annen effekt for å slå dem på igjen.",
        "lighting.officialEffects": "Offisielle effekter",
        "lighting.officialNote": "Base Camps effekter, sendt nøyaktig som Windows-appen gjør",
        "lighting.paintHint": "Klikk eller dra over tastene på tastaturet ovenfor.",
        "lighting.paintKeys": "Mal tast for tast",
        "lighting.palette": "Palette",
        "lighting.paused": "Satt på pause",
        "lighting.reapply": "Bruk på nytt",
        "lighting.rightClickHint": "Høyreklikk på en fargeprøve for å fjerne den.",
        "lighting.rotation": "Rotasjonsretning",
        "lighting.runningOnKeyboard": "Kjører på tastaturet",
        "lighting.savedInProfile": "Lagret i tastaturets aktive profil",
        "lighting.slow": "Langsom",
        "lighting.speed": "Hastighet",
        "lighting.title": "Belysning",

        // MARK: live
        "live.keyboard": "Tastatur · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · på pause",
        "live.pause": "Pause",
        "live.start": "Start",

        // MARK: macfx
        "macfx.aurora": "Nordlys",
        "macfx.equalizer": "Equalizer",
        "macfx.fire": "Ild",
        "macfx.gradient": "Overgang",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Digital regn",
        "macfx.ripples": "Krusninger",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Ensfarget",
        "macfx.spectrum": "Spekter",
        "macfx.spiral": "Spiral",
        "macfx.stars": "Stjerner",
        "macfx.waves": "Bølger",

        // MARK: menu
        "menu.allowAccessibility": "Tillat Tilgjengelighet…",
        "menu.disconnected": "Tastaturet er frakoblet",
        "menu.firmwareBlocked": "Firmware støttes ikke — tastaturet blir latt være i fred",
        "menu.keyboardEffects": "Tastatureffekter",
        "menu.launchAtLogin": "Start ved pålogging",
        "menu.macEffects": "Mac-effekter",
        "menu.manageProfiles": "Administrer profiler…",
        "menu.newProfile": "Ny profil",
        "menu.open": "Åpne Everest…",
        "menu.pauseEffect": "Sett effekten på pause",
        "menu.profile": "Profil: %1$@",
        "menu.resumeEffect": "Gjenoppta effekten",

        // MARK: metric
        "metric.disk": "DISK",
        "metric.network": "NETTVERK",
        "metric.volume": "VOLUM",

        // MARK: mode
        "mode.clock": "Klokke",
        "mode.disk": "Disk",
        "mode.image": "Bilde",
        "mode.network": "Nettverk",
        "mode.volume": "Volum",

        // MARK: overview
        "overview.actionsActive": "Handlinger aktive",
        "overview.changeLighting": "Endre belysning",
        "overview.dialSubtitle": "Mediedokkens runde skjerm",
        "overview.keyboardEffect": "Tastatureffekt",
        "overview.macEffect": "Effekt beregnet av Macen",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Glo",
        "palette.forest": "Skog",
        "palette.ice": "Is",
        "palette.neon": "Neon",
        "palette.ocean": "Hav",
        "palette.sunset": "Solnedgang",
        "palette.vapor": "Damp",

        // MARK: preset
        "preset.bolt": "Lyn",
        "preset.calendar": "Kalender",
        "preset.captureScreen": "Ta skjermbilde",
        "preset.captureZone": "Ta bilde av område",
        "preset.category.apps": "Apper",
        "preset.category.decor": "Bare ikon",
        "preset.category.media": "Medier",
        "preset.coffee": "Kaffe",
        "preset.flame": "Flamme",
        "preset.game": "Kontroller",
        "preset.heart": "Hjerte",
        "preset.home": "Hjem",
        "preset.lock": "Lås",
        "preset.music": "Musikk",
        "preset.mute": "Lyd av",
        "preset.next": "Neste",
        "preset.playpause": "Spill av / Pause",
        "preset.previous": "Forrige",
        "preset.sleepDisplay": "Slå av skjermen",
        "preset.star": "Stjerne",
        "preset.volumeDown": "Volum −",
        "preset.volumeUp": "Volum +",

        // MARK: profile
        "profile.defaultName": "Profil %1$@",
        "profile.main": "Hoved",

        // MARK: profiles
        "profiles.addApp": "Legg til en app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Automatisk bytte",
        "profiles.autoSwitchHint": "Fungerer mens appen er åpen eller daemonen kjører. En profil valgt manuelt på dreieknappen erstattes ikke så lenge du blir i en app uten profil.",
        "profiles.autoSwitchNote": "Tastaturet bytter til en apps profil når den ligger fremst",
        "profiles.deleteHelp": "Slett denne profilen fra appen",
        "profiles.dialMode": "Dreieknapp: %1$@",
        "profiles.dialOnActivate": "Dreieknapp ved aktivering",
        "profiles.dialUnchanged": "Dreieknappen uendret",
        "profiles.dontChange": "Ikke endre",
        "profiles.enable": "Aktiver",
        "profiles.freeSlots": "%1$@ ledig(e) plass(er)",
        "profiles.hardwareNote": "Tastaturet lagrer fem profiler i minnet (dreieknappens Profile-meny). Hver har sin egen belysning, egne omtilordninger og egne D1–D4-bilder; appen legger til tastehandlingene, dreieknappens modus og de koblede appene. De tolv DisplayPad-tastene lagres også i hver profil.",
        "profiles.header": "PROFIL %1$@",
        "profiles.iconAndColour": "Ikon og farge",
        "profiles.keyboardLighting": "Tastaturbelysning",
        "profiles.keyboardProfiles": "TASTATURPROFILER",
        "profiles.keysNote": "Tastene D1–D4 og belysningen stilles inn på sine egne sider mens denne profilen er aktiv: De lagres i denne profilen.",
        "profiles.lightingFirmware": "Belysning: %1$@",
        "profiles.lightingMac": "Mac-belysning: %1$@",
        "profiles.linkedApps": "Koblede apper",
        "profiles.manage": "Administrer…",
        "profiles.namePlaceholder": "Koding, Musikk…",
        "profiles.noLinkedApp": "Ingen koblet app",
        "profiles.otherwise": "Ellers, gå tilbake til",
        "profiles.slot": "Plass %1$@",
        "profiles.slotOf": "Profil %1$@ av %2$@",

        // MARK: reset
        "reset.title": "Tilbakestill",

        // MARK: section
        "section.buttons.subtitle": "En macOS-handling på hver av de fire skjermtastene",
        "section.buttons.title": "Tastene D1–D4",
        "section.displays.subtitle": "Dreieknappens runde skjerm og det numeriske tastaturets skjermtaster",
        "section.displays.title": "Skjermer",
        "section.keyboard.subtitle": "Oppdaget tastaturoppsett og tilsvarende macOS-oppsett",
        "section.keyboard.title": "Oppsett",
        "section.lighting.subtitle": "Offisielle tastatureffekter og dynamiske effekter beregnet av Macen",
        "section.overview.subtitle": "Din Everest Max med et blikk",
        "section.overview.title": "Oversikt",
        "section.profiles.subtitle": "Fem profiler lagret i tastaturet, hver med egne taster, egen belysning og egne apper",
        "section.profiles.title": "Profiler",
        "section.system.subtitle": "Tastedaemon, overvåking og feilsøking",
        "section.system.title": "System",

        // MARK: settings
        "settings.language.automatic": "Automatisk (systemspråk)",
        "settings.language.note": "Språk for grensesnittet, menylinjemenyen og meldinger.",
        "settings.language.title": "Språk",

        // MARK: status
        "status.animationPaused": "Animasjonen er satt på pause — tastaturet beholder det siste bildet.",
        "status.appIconUnreadable": "Kunne ikke lese appens ikon.",
        "status.appNoId": "Denne appen har ingen identifikator: Den kan ikke kobles.",
        "status.changeFailed": "Kunne ikke endres: %1$@",
        "status.cleaning": "Rydder opp",
        "status.clockSynced": "Klokken er synkronisert med Macen.",
        "status.configSaved": "Innstillinger lagret.",
        "status.daemonOff": "Tastene D1–D4 er slått av.",
        "status.daemonOn": "Tastene D1–D4 aktive.",
        "status.daemonStartFailed": "Kunne ikke starte daemonen: %1$@",
        "status.dialImageSent": "Bildet ble sendt til dreieknappen.",
        "status.dialMode": "Dreieknapp: %1$@.",
        "status.displayLabel": "Skjerm",
        "status.effectApplied": "%1$@ brukt og lagret i profilen.",
        "status.effectRunningKeyboard": "Effekten «%1$@» kjører på tastaturet.",
        "status.factoryIconRestored": "Fabrikkikonet er gjenopprettet på %1$@.",
        "status.frozen": "Bildet er låst og lagret i tastaturets «Custom»-plass.",
        "status.iconDrawFailed": "Kunne ikke tegne ikonet.",
        "status.iconSent": "Ikonet ble sendt til %1$@ på %2$@ s.",
        "status.keyboardConnected": "Tastaturet er tilkoblet.",
        "status.keyboardGone": "Tastaturet er frakoblet — effekten gjenopptas når det kobles til igjen.",
        "status.layoutAuto": "Oppsett: automatisk gjenkjenning.",
        "status.layoutForced": "Oppsett tvunget: %1$@.",
        "status.leftoversCleared": "Gjenværende handlinger er slettet fra tastaturets minne.",
        "status.loginApproval": "Må godkjennes i Systeminnstillinger → Generelt → Påloggingsobjekter.",
        "status.previewOnly": "Fant ikke tastaturet — forhåndsvisningen er fortsatt tilgjengelig.",
        "status.profileActivated": "Profilen «%1$@» er aktivert.",
        "status.profileActivatedFrontApp": "Profilen «%1$@» er aktivert (appen ligger fremst).",
        "status.profileFromKeyboard": "Profilen «%1$@» er aktiv (valgt på tastaturet).",
        "status.profileRemoved": "Profilen er fjernet fra appen (tastaturet beholder innstillingene sine på plass %1$@).",
        "status.ready": "Klar",
        "status.recovering": "Gjenoppretting",
        "status.recoverySent": "Gjenopprettingssekvensen er sendt.",
        "status.saving": "Lagrer",
        "status.sendingImage": "Sender bildet…",
        "status.uploadBusy": "En overføring pågår på %1$@ — vent noen sekunder.",
        "status.uploadBusyAlready": "En overføring pågår allerede på %1$@ — vent noen sekunder.",
        "status.uploadFailed": "Overføringen mislyktes: %1$@",
        "status.uploadFailedKey": "%1$@: overføringen mislyktes — %2$@",
        "status.uploadStarted": "%1$@: sender bildet til tastaturet…",

        // MARK: system
        "system.askAgain": "Spør igjen",
        "system.autoDaemon": "Aktiver tastene D1–D4 automatisk",
        "system.autoDaemonNote": "Daemonen starter med appen, kobler seg til igjen av seg selv når tastaturet kobles til på nytt, og starter på nytt hvis den stopper.",
        "system.autostartHint": "Automatisk start ved pålogging: ./install-daemon.sh fra Terminal.",
        "system.background": "Everest jobber i bakgrunnen, fra menylinjen",
        "system.daemonSubtitle": "Kjører D1–D4-handlingene og sender verdier til dreieknappen",
        "system.daemonTitle": "Tastedaemon",
        "system.keepRunning": "La Everest kjøre når jeg lukker vinduet",
        "system.keepRunningNote": "Tastene D1–D4, profilene og effektene fortsetter å virke; ikonet blir i menylinjen. Avslutt: ikonmenyen eller ⌘Q.",
        "system.keyboardCard": "Tastatur",
        "system.keyboardCardNote": "Status rapportert av firmwaren",
        "system.launchAtLogin": "Start Everest ved pålogging",
        "system.launchAtLoginNote": "Starter diskret i menylinjen uten å åpne vinduet.",
        "system.launchedFrom": "Everest kjører fra %1$@. For en pålitelig start, kopier det til /Applications (./make-app.sh --install): Et eksternt volum er ikke alltid montert ved pålogging.",
        "system.lightProfile": "Lysprofil",
        "system.listening": "Lytter",
        "system.metricsEvery": "Daemonen sender verdiene hvert 0,5. sekund mens den kjører.",
        "system.modules": "Moduler",
        "system.monitoring": "Overvåking",
        "system.monitoringNote": "Systemverdier vist på dreieknappen",
        "system.noAccessibility": "Everest har ikke tillatelsen Tilgjengelighet",
        "system.noAccessibilityNote": "Uten den gjør handlingene «hurtigtast» og «tekst» ingenting (app-, kommando- og lenkehandlinger fungerer fortsatt). Hvis Everest allerede er avkrysset i listen, er oppføringen utdatert: Velg den, fjern den med «−», legg den til igjen med «+» (Everest.app), og start daemonen på nytt.",
        "system.openSettings": "Åpne innstillinger",
        "system.sendMetrics": "Send CPU, GPU, RAM, disk, nettverk og volum",
        "system.stoppedState": "Stoppet",
        "system.unlock": "Lås opp tastaturet",
        "system.unlockNote": "«Lås opp» sender SDK-tilbakestillingen hvis en bildeoverføring ble avbrutt. Hvis det ikke er nok, koble fra og til tastaturet igjen: Ingenting går tapt.",

        // MARK: upload
        "upload.phase.connect": "Kobler til tastaturet",
        "upload.phase.done": "Ferdig",
        "upload.phase.finish": "Avslutter",
        "upload.phase.prepare": "Tastaturet forbereder plassen",
        "upload.phase.send": "Sender bildet",

        "status.configReloaded": "Innstillingene ble endret utenfor appen og er lastet inn på nytt.",

        // MARK: pad
        "night.displays": "Sett også Mac-skjermene i dvale",
        "night.displaysNote": "Bare skjermene, ikke Macen. Hvis macOS ber om passord når skjermen slås av (innstillinger for Låst skjerm), låses økten om natten.",
        "action.night": "Nattmodus",
        "night.note": "Slår av tastaturlyset og DisplayPad og demper lyden; trykk igjen for å få alt tilbake som før.",
        "night.active": "Nattmodus på",
        "action.profile": "Profil",
        "profileAction.next": "Neste profil",
        "profileAction.previous": "Forrige profil",
        "profiles.newCopyPad": "Ny, med DisplayPad-tastene fra «%1$@»",
        "live.fiveHours": "5 timer",
        "codexbar.ok": "CodexBar-data: OK",
        "codexbar.denied": "Everest kan ikke lese dataene til CodexBar",
        "codexbar.deniedNote": "macOS beskytter andre appers data, og apper kan ikke legge seg selv til i «Full disktilgang». Dra Everest fra Finder-vinduet inn i listen (eller bruk +), slå det på, og avslutt og åpne Everest på nytt.",
        "codexbar.openSettings": "Åpne innstillinger",
        "live.week": "uke",
        "keyappearance.liveCodexBar": "Claude og Codex viser bruksgrensene dine slik CodexBar sist leste dem (oppdateres med noen minutters mellomrom): én tast for 5-timersvinduet, én for uken.",
        "pad.status.swapped": "%1$@ og %2$@ byttet.",
        "keyappearance.live": "Direkte",
        "keyappearance.liveAction": "Åpne også tilhørende app",
        "keyappearance.liveNote": "Tegnes på nytt når verdien endres (høyst én gang i sekundet) mens paden er tilkoblet. Tasten beholder handlingen sin.",
        "pad.keysActive": "P1–P12-taster aktive",
        "pad.overview.keys": "%1$@ av 12 taster satt opp",
        "pad.overview.firmware": "Fastvare %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "DisplayPad-fastvare %1$@ støttes ikke",
        "pad.unsupportedNote": "Everest skriver bare til fastvare 8, den testede versjonen, og lar denne paden være.",
        "pad.noAnswer": "DisplayPad svarer ikke",
        "pad.noAnswerNote": "Den er koblet til, men svarer ikke: vent noen sekunder, eller koble den direkte til Macen.",
        "section.displaypad.subtitle": "Tolv skjermtaster, hver med et bilde og en macOS-handling",
        "pad.connected": "DisplayPad tilkoblet",
        "pad.connectedNote": "Bilder sendes innen et sekund etter hver endring; paden beholder dem til den kobles fra.",
        "pad.notConnected": "DisplayPad ikke tilkoblet",
        "pad.notConnectedNote": "Koble den direkte til Macen: på noen USB-huber forblir skjermen svart.",
        "pad.brightness": "Lysstyrke",
        "pad.keys": "Taster",
        "pad.keysNote": "Klikk på en tast for å redigere den, eller dra den til en annen for å bytte dem. Bilder og handlinger lagres i profilen «%1$@».",
        "pad.clearKey": "Tøm",
        "pad.clearKeyHelp": "Fjerner bildet og handlingen til %1$@",
        "pad.noImage": "Ikke noe bilde",
        "pad.ownImageNote": "Det beskjæres i midten og skaleres til 102 × 102. Tastens handling endres ikke.",
        "pad.daemonStoppedNote": "DisplayPad-tastene virker bare mens den kjører.",
        "pad.status.sent": "%1$@: sendt til DisplayPad.",
        "pad.status.savedOffline": "%1$@: lagret — vises når DisplayPad kobles til.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
