// Interface strings — da. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let da: [String: String] = [
        // MARK: action
        "action.app": "App",
        "action.keypress": "Genvej",
        "action.none": "Ingen",
        "action.open": "Fil",
        "action.shell": "Kommando",
        "action.text": "Tekst",
        "action.textToType": "Tekst, der skal skrives",
        "action.url": "Link",

        // MARK: app
        "app.closeWindow": "Luk vindue",
        "app.copy": "Kopiér",
        "app.cut": "Klip",
        "app.edit": "Rediger",
        "app.hide": "Skjul Everest",
        "app.paste": "Sæt ind",
        "app.quit": "Afslut Everest",
        "app.selectAll": "Markér alt",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS-handlinger og indtastede genveje kræver tilladelsen Hjælpemidler (Indstillinger → Anonymitet og sikkerhed).",
        "buttons.actionRan": "Handlingen for %1$@ blev udført.",
        "buttons.appHint": "Åbner appen eller henter den frem",
        "buttons.clearLeftovers": "Ryd efterladte handlinger",
        "buttons.daemonStopped": "Daemonen er stoppet",
        "buttons.daemonStoppedNote": "Handlinger kører kun, mens den lytter efter tasterne D1–D4.",
        "buttons.factoryValues": "Fabriksindstillinger",
        "buttons.factoryValuesHelp": "Gendanner det oprindelige billede og den oprindelige handling for %1$@",
        "buttons.flashMemory": "Tastaturets hukommelse",
        "buttons.flashMemoryNote": "Base Camp kan efterlade handlinger i flashhukommelsen (f.eks. D4, der sender Esc)",
        "buttons.keyHeader": "TAST %1$@",
        "buttons.noAction": "Ingen handling — tasten ignoreres.",
        "buttons.noApp": "Ingen app valgt",
        "buttons.pickPresetAppImage": "Forudindstilling, app eller billede til %1$@",
        "buttons.presetsAndIcon": "Forudindstillinger og ikon…",

        // MARK: clock
        "clock.analog": "Analog",
        "clock.digital": "Digital",
        "clock.sync": "Synkronisér",

        // MARK: colormode
        "colormode.dual": "To farver",
        "colormode.quad": "4 farver",
        "colormode.rainbow": "Regnbue",
        "colormode.single": "Én farve",
        "colormode.withBackground": "Tast + baggrund",

        // MARK: common
        "common.active": "Aktiv",
        "common.add": "Ny",
        "common.choose": "Vælg…",
        "common.close": "Luk",
        "common.configure": "Konfigurer",
        "common.delete": "Slet",
        "common.edit": "Rediger",
        "common.name": "Navn",
        "common.other": "Andet…",
        "common.refresh": "Opdater",
        "common.remove": "Fjern",
        "common.start": "Start",
        "common.stop": "Stop",
        "common.test": "Test",

        // MARK: daemon
        "daemon.keysActive": "Tasterne D1–D4 aktive",
        "daemon.stopped": "Daemon stoppet",

        // MARK: device
        "device.blocked": "Firmware understøttes ikke",
        "device.connected": "Forbundet",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Afbrudt",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Komplet Everest Max",
        "device.keyboardMissing": "tastaturet er ikke tilgængeligt",
        "device.keyboardUnavailable": "Tastaturet er ikke tilgængeligt (ikke fundet, eller firmware understøttes ikke).",
        "device.notConnected": "Ikke forbundet",
        "device.refresh.help": "Opdater tastaturets status",
        "device.withDock": "Tastatur + mediedock",
        "device.withNumpad": "Tastatur + numerisk tastatur",

        // MARK: displays
        "displays.change": "Skift…",
        "displays.chooseImage": "Vælg et billede…",
        "displays.dial.subtitle": "Rund 240 × 204-skærm på mediedocken",
        "displays.display": "Visning",
        "displays.factoryIcon": "Fabriksikon",
        "displays.factoryLogo": "Fabrikslogo",
        "displays.imageCropped": "Billedet beskæres til 240 × 204.",
        "displays.imagesResized": "Billeder skaleres til 72 × 72.",
        "displays.keys.subtitle": "Fire 72 × 72-skærme over det numeriske tastatur",
        "displays.keys.title": "Skærmtaster",
        "displays.logoRestored": "Mountain-logoet er gendannet på drejeknappen.",
        "displays.metricsNote": "CPU, GPU, RAM, disk, netværk og lydstyrke viser de værdier, daemonen sender (siden System).",

        // MARK: factory
        "factory.activityMonitor": "Aktivitetsmonitor",
        "factory.sleep": "Dvale",

        // MARK: firmware
        "firmware.block.body": "Everest er kun testet med firmware %1$@. For at undgå enhver risiko for at gøre dit tastatur ubrugeligt sender det intet til det, før det kører den version: ingen belysning, ingen billeder, ingen handlinger.",
        "firmware.block.check": "Tjek igen",
        "firmware.block.detected": "Registreret firmware: %1$@",
        "firmware.block.how": "Mountain tilbyder kun firmwareopdateringen i sin officielle Base Camp-app til Windows. Slut tastaturet til en Windows-pc, installer Base Camp, opdater firmwaren, og slut derefter tastaturet til denne Mac igen: Everest registrerer det selv.",
        "firmware.block.howTitle": "Sådan opdaterer du tastaturet",
        "firmware.block.tested": "Testet firmware: %1$@",
        "firmware.block.title": "Firmware understøttes ikke",
        "firmware.block.unreadableBody": "Everest kan ikke kontrollere tastaturets firmwareversion og rører det derfor ikke. Tag stikket ud og sæt det i igen, og prøv derefter igen.",
        "firmware.block.unreadableTitle": "Firmware kan ikke læses",
        "firmware.block.why": "Everest opdaterer ikke selv firmwaren: Det er den samme slags handling, der kan gøre et tastatur ubrugeligt, og den kan ikke testes her.",
        "firmware.status.unreadable": "Tastaturet oplyste ikke sin firmware — det efterlades urørt.",
        "firmware.status.unsupported": "Firmware %1$@ understøttes ikke (testet: %2$@) — tastaturet efterlades urørt.",

        // MARK: fx
        "fx.breathing": "Åndedræt",
        "fx.breathing.desc": "Blid pulsering",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Faldende dråber",
        "fx.off": "Fra",
        "fx.off.desc": "Alt er slukket",
        "fx.reactive": "Reaktiv",
        "fx.reactive.desc": "Lyser op, når du skriver",
        "fx.static": "Statisk",
        "fx.static.desc": "Fast farve",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Drejer rundt om midten",
        "fx.wave": "Bølge",
        "fx.wave.desc": "Fejer hen over tastaturet",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Krusning fra tasten",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Anvend også forudindstillingens handling",
        "keyappearance.appHint": "Tasten åbner appen eller henter den frem, hvis den allerede er åben.",
        "keyappearance.apps": "Apps",
        "keyappearance.background": "Fortsæt i baggrunden",
        "keyappearance.busyOther": "En overførsel kører på %1$@ — vent, til den er færdig, før du ændrer denne tast.",
        "keyappearance.chooseFile": "Vælg en fil…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Åbner appen",
        "keyappearance.ownImage": "Dit eget billede",
        "keyappearance.ownImageNote": "Det beskæres i midten og skaleres til 72 × 72. Tastens handling ændres ikke.",
        "keyappearance.presets": "Forudindstillinger",
        "keyappearance.searchApp": "Søg efter en app",
        "keyappearance.step.prepare": "Forbereder",
        "keyappearance.step.send": "Sender",
        "keyappearance.subtitle": "Vælg, hvad skærmen viser, og hvad tasten gør",
        "keyappearance.title": "Tast %1$@",
        "keyappearance.transferNote": "En overførsel tager cirka 20 sekunder: Tastaturet forbereder pladsen (det sletter selv det gamle billede) og modtager derefter det nye i pakker på 64 byte. Tag ikke stikket ud.",

        // MARK: keyboard
        "keyboard.activeBadge": "AKTIV",
        "keyboard.ansiShape": "ANSI-form: bred Enter, \\ for enden af den øverste række",
        "keyboard.asPrinted": "som trykt",
        "keyboard.automatic": "Automatisk",
        "keyboard.chosen": "VALGT MANUELT",
        "keyboard.clearRemaps": "Ryd omtildelinger",
        "keyboard.detected": "REGISTRERET",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. Gælder til genstart. For en omtildeling gemt i tastaturet: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO-tast",
        "keyboard.isoMuteNote": "Hvis macOS behandler tastaturet som ANSI, gør tasten til venstre for Z ingenting",
        "keyboard.isoMuteTitle": "Reagerer ISO-tasten ikke?",
        "keyboard.isoShape": "ISO-form: høj Enter, ekstra tast til venstre for Z",
        "keyboard.legend.at": "@ på tasten '",
        "keyboard.legend.backslash": "\\ | til venstre for Z",
        "keyboard.legend.quote": "\" på ⇧2",
        "keyboard.legend.rightOfSemicolon": "til højre for ;",
        "keyboard.macLayout": "macOS-tastaturlayout",
        "keyboard.macLayoutNote": "Så macOS skriver det, der er trykt på tasterne",
        "keyboard.noMacLayout": "Der er ikke installeret noget macOS-layout, der svarer til “%1$@”: Tilføj det i Systemindstillinger → Tastatur → Inputkilder.",
        "keyboard.remapApplied": "ISO-omtildeling anvendt (indtil genstart).",
        "keyboard.remapIso": "Omtildel ISO-tasten",
        "keyboard.remapsCleared": "hidutil-omtildelinger ryddet.",
        "keyboard.reportsLayout": "Tastaturet melder “%1$@”. Skift tilbage til automatisk, hvis valget ikke længere er nødvendigt.",
        "keyboard.switchedTo": "Layout skiftet til %1$@.",
        "keyboard.title": "Fysisk tastatur",
        "keyboard.titleNote": "Læses fra tastaturet, ligesom i Base Camp: Tegningen, tasterne og effekterne tilpasses",
        "keyboard.unknown": "ukendt",
        "keyboard.use": "Brug %1$@",
        "keyboard.verifiedNote1": "Hver tasts form og belysning følger tastaturets gitter; kun UK-layoutet er verificeret på et rigtigt tastatur.",
        "keyboard.verifiedNote2": "Tasteteksterne kommer fra Base Camps tabeller, og formen følger LED-gitteret; kun UK-layoutet er verificeret på et rigtigt tastatur.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "overførslen til drejeknappen blev afbrudt — brug “Lås tastaturet op” (siden System), eller sæt det i igen",
        "keyboardError.dialRefused": "drejeknappen afviste overførslen (intet blev skrevet)",
        "keyboardError.interrupted": "overførslen blev afbrudt — brug “Lås tastaturet op” (siden System), eller sæt det i igen",
        "keyboardError.refused": "tastaturet afviste overførslen (intet blev skrevet) — prøv igen; hvis det fortsætter, brug “Lås tastaturet op” (siden System)",
        "keyboardError.selectTarget": "tastaturet svarer ikke på tastevalget — brug “Lås tastaturet op” (siden System), eller sæt det i igen",

        // MARK: layout
        "layout.french": "Fransk (AZERTY)",
        "layout.german": "Tysk (QWERTZ)",
        "layout.hebrew": "Hebraisk",
        "layout.italian": "Italiensk",
        "layout.korean": "Koreansk",
        "layout.nordic": "Nordisk",
        "layout.portuguese": "Portugisisk",
        "layout.spanish": "Spansk",
        "layout.uk": "Storbritannien (ISO)",
        "layout.us": "USA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Tilføj en farve",
        "lighting.allHues": "Alle nuancer, genereret af tastaturet.",
        "lighting.backgroundColour": "Baggrund",
        "lighting.brightness": "Lysstyrke",
        "lighting.byKeyboard": "Køres af tastaturet — fortsætter uden appen",
        "lighting.byMac": "Beregnes af Macen — hold appen åben",
        "lighting.clearAll": "Ryd alt",
        "lighting.clockwise": "Med uret",
        "lighting.colors": "Farver",
        "lighting.colour": "Farve",
        "lighting.colour1": "Farve 1",
        "lighting.colour2": "Farve 2",
        "lighting.colourCount.one": "%1$@ farve",
        "lighting.colourCount.other": "%1$@ farver",
        "lighting.counterclockwise": "Mod uret",
        "lighting.direction": "Retning",
        "lighting.editEllipsis": "Rediger…",
        "lighting.fast": "Hurtig",
        "lighting.flameNote": "Fast flammeskala, fra glød til hvid.",
        "lighting.freeze": "Lås fast i tastaturet",
        "lighting.freezeNote": "Sender det aktuelle billede til Custom-pladsen og gemmer det: Det bliver, selv uden appen.",
        "lighting.keyColour": "Tast",
        "lighting.ledsBlack": "Alle LED’er er sorte, mens effekten kører.",
        "lighting.macNote": "Beregnet tast for tast med 30 billeder/s, med din palet",
        "lighting.normal": "Normal",
        "lighting.offNote": "Baggrundsbelysningen og sidestriberne er slukket. Vælg en anden effekt for at tænde dem igen.",
        "lighting.officialEffects": "Officielle effekter",
        "lighting.officialNote": "Base Camps effekter, sendt præcis som Windows-appen gør",
        "lighting.paintHint": "Klik eller træk hen over tasterne på tastaturet ovenfor.",
        "lighting.paintKeys": "Mal tast for tast",
        "lighting.palette": "Palette",
        "lighting.paused": "På pause",
        "lighting.reapply": "Anvend igen",
        "lighting.rightClickHint": "Højreklik på en farveprøve for at fjerne den.",
        "lighting.rotation": "Rotationsretning",
        "lighting.runningOnKeyboard": "Kører på tastaturet",
        "lighting.savedInProfile": "Gemt i tastaturets aktive profil",
        "lighting.slow": "Langsom",
        "lighting.speed": "Hastighed",
        "lighting.title": "Belysning",

        // MARK: live
        "live.keyboard": "Tastatur · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · på pause",
        "live.pause": "Pause",
        "live.start": "Start",

        // MARK: macfx
        "macfx.aurora": "Nordlys",
        "macfx.equalizer": "Equalizer",
        "macfx.fire": "Ild",
        "macfx.gradient": "Overgang",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Digital regn",
        "macfx.ripples": "Krusninger",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Ensfarvet",
        "macfx.spectrum": "Spektrum",
        "macfx.spiral": "Spiral",
        "macfx.stars": "Stjerner",
        "macfx.waves": "Bølger",

        // MARK: menu
        "menu.allowAccessibility": "Tillad Hjælpemidler…",
        "menu.disconnected": "Tastaturet er afbrudt",
        "menu.firmwareBlocked": "Firmware understøttes ikke — tastaturet efterlades urørt",
        "menu.keyboardEffects": "Tastatureffekter",
        "menu.launchAtLogin": "Start ved login",
        "menu.macEffects": "Mac-effekter",
        "menu.manageProfiles": "Administrer profiler…",
        "menu.newProfile": "Ny profil",
        "menu.open": "Åbn Everest…",
        "menu.pauseEffect": "Sæt effekten på pause",
        "menu.profile": "Profil: %1$@",
        "menu.resumeEffect": "Genoptag effekten",

        // MARK: metric
        "metric.disk": "DISK",
        "metric.network": "NETVÆRK",
        "metric.volume": "LYDSTYRKE",

        // MARK: mode
        "mode.clock": "Ur",
        "mode.disk": "Disk",
        "mode.image": "Billede",
        "mode.network": "Netværk",
        "mode.volume": "Lydstyrke",

        // MARK: overview
        "overview.actionsActive": "Handlinger aktive",
        "overview.changeLighting": "Skift belysning",
        "overview.dialSubtitle": "Mediedockens runde skærm",
        "overview.keyboardEffect": "Tastatureffekt",
        "overview.macEffect": "Effekt beregnet af Macen",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Glød",
        "palette.forest": "Skov",
        "palette.ice": "Is",
        "palette.neon": "Neon",
        "palette.ocean": "Hav",
        "palette.sunset": "Solnedgang",
        "palette.vapor": "Damp",

        // MARK: preset
        "preset.bolt": "Lyn",
        "preset.calendar": "Kalender",
        "preset.captureScreen": "Tag skærmbillede",
        "preset.captureZone": "Tag billede af område",
        "preset.category.apps": "Apps",
        "preset.category.decor": "Kun ikon",
        "preset.category.media": "Medier",
        "preset.coffee": "Kaffe",
        "preset.flame": "Flamme",
        "preset.game": "Controller",
        "preset.heart": "Hjerte",
        "preset.home": "Hjem",
        "preset.lock": "Lås",
        "preset.music": "Musik",
        "preset.mute": "Lyd fra",
        "preset.next": "Næste",
        "preset.playpause": "Afspil / Pause",
        "preset.previous": "Forrige",
        "preset.sleepDisplay": "Sluk skærmen",
        "preset.star": "Stjerne",
        "preset.volumeDown": "Lydstyrke −",
        "preset.volumeUp": "Lydstyrke +",

        // MARK: profile
        "profile.defaultName": "Profil %1$@",
        "profile.main": "Hoved",

        // MARK: profiles
        "profiles.addApp": "Tilføj en app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Automatisk skift",
        "profiles.autoSwitchHint": "Virker, mens appen er åben, eller daemonen kører. En profil, der er valgt manuelt på drejeknappen, erstattes ikke, så længe du bliver i en app uden profil.",
        "profiles.autoSwitchNote": "Tastaturet skifter til en apps profil, når den er forrest",
        "profiles.deleteHelp": "Slet denne profil fra appen",
        "profiles.dialMode": "Drejeknap: %1$@",
        "profiles.dialOnActivate": "Drejeknap ved aktivering",
        "profiles.dialUnchanged": "Drejeknap uændret",
        "profiles.dontChange": "Skift ikke",
        "profiles.enable": "Aktivér",
        "profiles.freeSlots": "%1$@ ledig(e) plads(er)",
        "profiles.hardwareNote": "Tastaturet husker fem profiler (drejeknappens Profile-menu). Hver har sin egen belysning, sine egne omtildelinger og sine egne D1–D4-billeder; appen tilføjer tastehandlingerne, drejeknappens tilstand og de tilknyttede apps. DisplayPads tolv taster gemmes også i hver profil.",
        "profiles.header": "PROFIL %1$@",
        "profiles.iconAndColour": "Ikon og farve",
        "profiles.keyboardLighting": "Tastaturbelysning",
        "profiles.keyboardProfiles": "TASTATURPROFILER",
        "profiles.keysNote": "Tasterne D1–D4 og belysningen indstilles på deres egne sider, mens denne profil er aktiv: De gemmes i denne profil.",
        "profiles.lightingFirmware": "Belysning: %1$@",
        "profiles.lightingMac": "Mac-belysning: %1$@",
        "profiles.linkedApps": "Tilknyttede apps",
        "profiles.manage": "Administrer…",
        "profiles.namePlaceholder": "Kodning, Musik…",
        "profiles.noLinkedApp": "Ingen tilknyttet app",
        "profiles.otherwise": "Ellers gå tilbage til",
        "profiles.slot": "Plads %1$@",
        "profiles.slotOf": "Profil %1$@ af %2$@",

        // MARK: reset
        "reset.title": "Nulstil",

        // MARK: section
        "section.buttons.subtitle": "En macOS-handling på hver af de fire skærmtaster",
        "section.buttons.title": "Tasterne D1–D4",
        "section.displays.subtitle": "Drejeknappens runde skærm og det numeriske tastaturs skærmtaster",
        "section.displays.title": "Skærme",
        "section.keyboard.subtitle": "Registreret tastaturlayout og det tilsvarende macOS-layout",
        "section.keyboard.title": "Layout",
        "section.lighting.subtitle": "Officielle tastatureffekter og dynamiske effekter beregnet af Macen",
        "section.overview.subtitle": "Din Everest Max med et enkelt blik",
        "section.overview.title": "Oversigt",
        "section.profiles.subtitle": "Fem profiler gemt i tastaturet, hver med egne taster, egen belysning og egne apps",
        "section.profiles.title": "Profiler",
        "section.system.subtitle": "Tastedaemon, overvågning og fejlfinding",
        "section.system.title": "System",

        // MARK: settings
        "settings.language.automatic": "Automatisk (systemsprog)",
        "settings.language.note": "Sprog for grænsefladen, menulinjemenuen og beskeder.",
        "settings.language.title": "Sprog",

        // MARK: status
        "status.animationPaused": "Animation på pause — tastaturet beholder det sidste billede.",
        "status.appIconUnreadable": "Appens ikon kunne ikke læses.",
        "status.appNoId": "Denne app har ingen identifikator: Den kan ikke tilknyttes.",
        "status.changeFailed": "Kunne ikke ændres: %1$@",
        "status.cleaning": "Rydder op",
        "status.clockSynced": "Uret er synkroniseret med Macen.",
        "status.configSaved": "Indstillinger gemt.",
        "status.daemonOff": "Tasterne D1–D4 er slået fra.",
        "status.daemonOn": "Tasterne D1–D4 aktive.",
        "status.daemonStartFailed": "Daemonen kunne ikke startes: %1$@",
        "status.dialImageSent": "Billedet blev sendt til drejeknappen.",
        "status.dialMode": "Drejeknap: %1$@.",
        "status.displayLabel": "Skærm",
        "status.effectApplied": "%1$@ anvendt og gemt i profilen.",
        "status.effectRunningKeyboard": "Effekten “%1$@” kører på tastaturet.",
        "status.factoryIconRestored": "Fabriksikonet er gendannet på %1$@.",
        "status.frozen": "Billedet er låst og gemt i tastaturets “Custom”-plads.",
        "status.iconDrawFailed": "Ikonet kunne ikke tegnes.",
        "status.iconSent": "Ikonet blev sendt til %1$@ på %2$@ s.",
        "status.keyboardConnected": "Tastaturet er forbundet.",
        "status.keyboardGone": "Tastaturet er afbrudt — effekten genoptages, når det sluttes til igen.",
        "status.layoutAuto": "Layout: automatisk registrering.",
        "status.layoutForced": "Layout gennemtvunget: %1$@.",
        "status.leftoversCleared": "Efterladte handlinger er slettet fra tastaturets hukommelse.",
        "status.loginApproval": "Skal godkendes i Systemindstillinger → Generelt → Loginobjekter.",
        "status.previewOnly": "Tastaturet blev ikke fundet — forhåndsvisningen er stadig tilgængelig.",
        "status.profileActivated": "Profilen “%1$@” er aktiveret.",
        "status.profileActivatedFrontApp": "Profilen “%1$@” er aktiveret (appen er forrest).",
        "status.profileFromKeyboard": "Profilen “%1$@” er aktiv (valgt på tastaturet).",
        "status.profileRemoved": "Profilen er fjernet fra appen (tastaturet beholder sine indstillinger på plads %1$@).",
        "status.ready": "Klar",
        "status.recovering": "Gendannelse",
        "status.recoverySent": "Gendannelsessekvensen er sendt.",
        "status.saving": "Gemmer",
        "status.sendingImage": "Sender billedet…",
        "status.uploadBusy": "En overførsel kører på %1$@ — vent et par sekunder.",
        "status.uploadBusyAlready": "En overførsel kører allerede på %1$@ — vent et par sekunder.",
        "status.uploadFailed": "Overførslen mislykkedes: %1$@",
        "status.uploadFailedKey": "%1$@: overførslen mislykkedes — %2$@",
        "status.uploadStarted": "%1$@: sender billedet til tastaturet…",

        // MARK: system
        "system.askAgain": "Spørg igen",
        "system.autoDaemon": "Aktivér tasterne D1–D4 automatisk",
        "system.autoDaemonNote": "Daemonen starter med appen, forbinder sig selv igen, når tastaturet sluttes til igen, og genstarter, hvis den stopper.",
        "system.autostartHint": "Automatisk start ved login: ./install-daemon.sh fra Terminal.",
        "system.background": "Everest arbejder i baggrunden fra menulinjen",
        "system.daemonSubtitle": "Kører D1–D4-handlingerne og sender værdier til drejeknappen",
        "system.daemonTitle": "Tastedaemon",
        "system.keepRunning": "Hold Everest kørende, når jeg lukker vinduet",
        "system.keepRunningNote": "Tasterne D1–D4, profilerne og effekterne bliver ved med at virke; ikonet bliver i menulinjen. Afslut: ikonmenuen eller ⌘Q.",
        "system.keyboardCard": "Tastatur",
        "system.keyboardCardNote": "Status rapporteret af firmwaren",
        "system.launchAtLogin": "Start Everest ved login",
        "system.launchAtLoginNote": "Starter diskret i menulinjen uden at åbne vinduet.",
        "system.launchedFrom": "Everest kører fra %1$@. For en pålidelig start, kopiér det til /Applications (./make-app.sh --install): Et eksternt diskvolumen er ikke altid monteret ved login.",
        "system.lightProfile": "Lysprofil",
        "system.listening": "Lytter",
        "system.metricsEvery": "Daemonen sender værdierne hvert 0,5. sekund, mens den kører.",
        "system.modules": "Moduler",
        "system.monitoring": "Overvågning",
        "system.monitoringNote": "Systemværdier vist på drejeknappen",
        "system.noAccessibility": "Everest har ikke tilladelsen Hjælpemidler",
        "system.noAccessibilityNote": "Uden den gør handlingerne “genvej” og “tekst” ingenting (app-, kommando- og linkhandlinger virker stadig). Hvis Everest allerede er afkrydset på listen, er posten forældet: Markér den, fjern den med “−”, tilføj den igen med “+” (Everest.app), og genstart daemonen.",
        "system.openSettings": "Åbn indstillinger",
        "system.sendMetrics": "Send CPU, GPU, RAM, disk, netværk og lydstyrke",
        "system.stoppedState": "Stoppet",
        "system.unlock": "Lås tastaturet op",
        "system.unlockNote": "“Lås op” sender SDK-nulstillingen, hvis en billedoverførsel blev afbrudt. Hvis det ikke er nok, så tag stikket ud og sæt det i igen: Intet går tabt.",

        // MARK: upload
        "upload.phase.connect": "Forbinder til tastaturet",
        "upload.phase.done": "Færdig",
        "upload.phase.finish": "Afslutter",
        "upload.phase.prepare": "Tastaturet forbereder pladsen",
        "upload.phase.send": "Sender billedet",

        "status.configReloaded": "Indstillingerne blev ændret uden for appen og er indlæst igen.",

        // MARK: pad
        "mrr.connected": "Forbundet",
        "mrr.connect": "Forbind",
        "mrr.loading": "Læser dine tal…",
        "live.revenueToday": "Salg i dag",
        "live.revenue30Days": "Salg 30 dage",
        "live.commitsToday": "Commits i dag",
        "live.today": "i dag",
        "live.days30": "30 dage",
        "mrr.subtitle": "MRR, salg og commits på DisplayPad-tasterne",
        "mrr.disconnect": "Afbryd",
        "mrr.note": "Opret et personligt adgangstoken i MRRCalendar (Account › Integrations). Det gemmes i nøgleringen og læser kun dine tal.",
        "mrr.unauthorized": "Tokenet blev afvist: tjek det, eller opret et nyt.",
        "mrr.failed": "Kunne ikke nå MRRCalendar (%1$@).",
        "night.displays": "Sæt også Mac'ens skærme i dvale",
        "night.displaysNote": "Kun skærmene, ikke Mac'en. Hvis macOS kræver adgangskode, når skærmen slukkes (indstillinger for Låst skærm), låses sessionen om natten.",
        "action.night": "Nattilstand",
        "night.note": "Slukker tastaturlyset og DisplayPad og slår lyden fra; tryk igen for at få det hele tilbage som før.",
        "night.active": "Nattilstand til",
        "action.profile": "Profil",
        "profileAction.next": "Næste profil",
        "profileAction.previous": "Forrige profil",
        "profiles.newCopyPad": "Ny, med DisplayPad-tasterne fra »%1$@«",
        "live.fiveHours": "5 timer",
        "codexbar.ok": "CodexBar-data: OK",
        "codexbar.denied": "Everest kan ikke læse CodexBars data",
        "codexbar.deniedNote": "macOS beskytter andre apps' data, og apps kan ikke selv føje sig til »Fuld diskadgang«. Træk Everest fra Finder-vinduet ind på listen (eller brug +), slå det til, og afslut og åbn Everest igen.",
        "codexbar.openSettings": "Åbn indstillinger",
        "live.week": "uge",
        "keyappearance.liveCodexBar": "Claude og Codex viser dine forbrugsgrænser, som CodexBar sidst læste dem (opdateres med få minutters mellemrum): én tast for 5-timersvinduet, én for ugen.",
        "pad.status.swapped": "%1$@ og %2$@ byttet.",
        "keyappearance.live": "Live",
        "keyappearance.liveAction": "Åbn også den tilhørende app",
        "keyappearance.liveNote": "Tegnes igen, når værdien ændres (højst én gang i sekundet), mens paddet er tilsluttet. Tasten beholder sin handling.",
        "pad.keysActive": "P1–P12-taster aktive",
        "pad.overview.keys": "%1$@ af 12 taster sat op",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "DisplayPad-firmware %1$@ understøttes ikke",
        "pad.unsupportedNote": "Everest skriver kun til firmware 8, den testede version, og lader dette pad være.",
        "pad.noAnswer": "DisplayPad svarer ikke",
        "pad.noAnswerNote": "Det er tilsluttet, men svarer ikke: vent et par sekunder, eller tilslut det direkte til Mac'en.",
        "section.displaypad.subtitle": "Tolv skærmtaster, hver med et billede og en macOS-handling",
        "pad.connected": "DisplayPad tilsluttet",
        "pad.connectedNote": "Billeder sendes inden for et sekund efter hver ændring; paddet beholder dem, indtil det frakobles.",
        "pad.notConnected": "DisplayPad ikke tilsluttet",
        "pad.notConnectedNote": "Tilslut det direkte til Mac'en: på nogle USB-hubs forbliver skærmen sort.",
        "pad.brightness": "Lysstyrke",
        "pad.keys": "Taster",
        "pad.keysNote": "Klik på en tast for at redigere den, eller træk den hen på en anden for at bytte dem. Billeder og handlinger gemmes i profilen »%1$@«.",
        "pad.clearKey": "Ryd",
        "pad.clearKeyHelp": "Fjerner billedet og handlingen for %1$@",
        "pad.noImage": "Intet billede",
        "pad.ownImageNote": "Det beskæres i midten og skaleres til 102 × 102. Tastens handling ændres ikke.",
        "pad.daemonStoppedNote": "DisplayPad-tasterne virker kun, mens den kører.",
        "pad.status.sent": "%1$@: sendt til DisplayPad.",
        "pad.status.savedOffline": "%1$@: gemt — vises, når DisplayPad tilsluttes.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
