// Interface strings — ko. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let ko: [String: String] = [
        // MARK: action
        "action.app": "앱",
        "action.keypress": "단축키",
        "action.none": "없음",
        "action.open": "파일",
        "action.shell": "명령",
        "action.text": "텍스트",
        "action.textToType": "입력할 텍스트",
        "action.url": "링크",

        // MARK: app
        "app.closeWindow": "윈도우 닫기",
        "app.copy": "복사",
        "app.cut": "오려두기",
        "app.edit": "편집",
        "app.hide": "Everest 가리기",
        "app.paste": "붙여넣기",
        "app.quit": "Everest 종료",
        "app.selectAll": "모두 선택",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS 동작과 입력되는 단축키에는 손쉬운 사용 권한이 필요합니다 (설정 → 개인정보 보호 및 보안).",
        "buttons.actionRan": "%1$@의 동작을 실행했습니다.",
        "buttons.appHint": "앱을 열거나 앞으로 가져옵니다",
        "buttons.clearLeftovers": "남은 동작 지우기",
        "buttons.daemonStopped": "데몬이 중지되었습니다",
        "buttons.daemonStoppedNote": "동작은 데몬이 D1–D4 키를 감지하는 동안에만 실행됩니다.",
        "buttons.factoryValues": "초기 설정",
        "buttons.factoryValuesHelp": "%1$@의 원래 이미지와 동작을 복원합니다",
        "buttons.flashMemory": "키보드 메모리",
        "buttons.flashMemoryNote": "Base Camp가 플래시 메모리에 동작을 남길 수 있습니다 (예: D4가 Esc를 보냄)",
        "buttons.keyHeader": "%1$@ 키",
        "buttons.noAction": "동작 없음 — 키가 무시됩니다.",
        "buttons.noApp": "선택한 앱 없음",
        "buttons.pickPresetAppImage": "%1$@용 프리셋, 앱 또는 이미지",
        "buttons.presetsAndIcon": "프리셋 및 아이콘…",

        // MARK: clock
        "clock.analog": "아날로그",
        "clock.digital": "디지털",
        "clock.sync": "동기화",

        // MARK: colormode
        "colormode.dual": "두 가지 색",
        "colormode.quad": "4가지 색",
        "colormode.rainbow": "무지개",
        "colormode.single": "한 가지 색",
        "colormode.withBackground": "키 + 배경",

        // MARK: common
        "common.active": "활성",
        "common.add": "새로 만들기",
        "common.choose": "선택…",
        "common.close": "닫기",
        "common.configure": "설정",
        "common.delete": "삭제",
        "common.edit": "편집",
        "common.name": "이름",
        "common.other": "기타…",
        "common.refresh": "새로 고침",
        "common.remove": "제거",
        "common.start": "시작",
        "common.stop": "중지",
        "common.test": "테스트",

        // MARK: daemon
        "daemon.keysActive": "D1–D4 키 활성",
        "daemon.stopped": "데몬 중지됨",

        // MARK: device
        "device.blocked": "지원되지 않는 펌웨어",
        "device.connected": "연결됨",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "연결 끊김",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Everest Max 전체 구성",
        "device.keyboardMissing": "키보드를 사용할 수 없음",
        "device.keyboardUnavailable": "키보드를 사용할 수 없습니다 (찾을 수 없거나 지원되지 않는 펌웨어).",
        "device.notConnected": "연결되지 않음",
        "device.refresh.help": "키보드 상태 새로 고침",
        "device.withDock": "키보드 + 미디어 독",
        "device.withNumpad": "키보드 + 숫자 패드",

        // MARK: displays
        "displays.change": "변경…",
        "displays.chooseImage": "이미지 선택…",
        "displays.dial.subtitle": "미디어 독의 240 × 204 원형 화면",
        "displays.display": "표시",
        "displays.factoryIcon": "초기 아이콘",
        "displays.factoryLogo": "초기 로고",
        "displays.imageCropped": "이미지는 240 × 204로 잘립니다.",
        "displays.imagesResized": "이미지는 72 × 72로 크기가 조정됩니다.",
        "displays.keys.subtitle": "숫자 패드 위의 72 × 72 화면 4개",
        "displays.keys.title": "디스플레이 키",
        "displays.logoRestored": "다이얼에 Mountain 로고를 복원했습니다.",
        "displays.metricsNote": "CPU, GPU, RAM, 디스크, 네트워크, 볼륨에는 데몬이 보내는 값이 표시됩니다 (시스템 페이지).",

        // MARK: factory
        "factory.activityMonitor": "활성 상태 보기",
        "factory.sleep": "잠자기",

        // MARK: firmware
        "firmware.block.body": "Everest는 펌웨어 %1$@에서만 테스트되었습니다. 키보드를 사용할 수 없게 될 위험을 피하기 위해, 해당 버전이 아니면 조명, 이미지, 동작 등 아무것도 보내지 않습니다.",
        "firmware.block.check": "다시 확인",
        "firmware.block.detected": "감지된 펌웨어: %1$@",
        "firmware.block.how": "Mountain은 Windows용 공식 Base Camp 앱에서만 펌웨어 업데이트를 제공합니다. 키보드를 Windows PC에 연결하고 Base Camp를 설치해 펌웨어를 업데이트한 다음, 키보드를 다시 이 Mac에 연결하세요. Everest가 자동으로 감지합니다.",
        "firmware.block.howTitle": "키보드 업데이트 방법",
        "firmware.block.tested": "테스트된 펌웨어: %1$@",
        "firmware.block.title": "지원되지 않는 펌웨어",
        "firmware.block.unreadableBody": "Everest가 키보드의 펌웨어 버전을 확인할 수 없어 키보드에 손대지 않습니다. 키보드를 뽑았다가 다시 연결한 뒤 다시 시도하세요.",
        "firmware.block.unreadableTitle": "펌웨어를 읽을 수 없음",
        "firmware.block.why": "Everest는 펌웨어를 직접 업데이트하지 않습니다. 키보드를 사용할 수 없게 만들 수 있는 종류의 작업이며 여기서는 테스트할 수 없기 때문입니다.",
        "firmware.status.unreadable": "키보드가 펌웨어를 알려 주지 않았습니다 — 키보드는 그대로 둡니다.",
        "firmware.status.unsupported": "펌웨어 %1$@은(는) 지원되지 않습니다 (테스트됨: %2$@) — 키보드는 그대로 둡니다.",

        // MARK: fx
        "fx.breathing": "브리딩",
        "fx.breathing.desc": "부드러운 맥동",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "떨어지는 물방울",
        "fx.off": "끔",
        "fx.off.desc": "모두 꺼짐",
        "fx.reactive": "리액티브",
        "fx.reactive.desc": "입력하면 켜짐",
        "fx.static": "고정",
        "fx.static.desc": "단색",
        "fx.tornado": "토네이도",
        "fx.tornado.desc": "중심을 따라 회전",
        "fx.wave": "웨이브",
        "fx.wave.desc": "키보드를 가로질러 이동",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "키에서 퍼지는 파동",

        // MARK: keyappearance
        "keyappearance.alsoAction": "프리셋의 동작도 함께 적용",
        "keyappearance.appHint": "키를 누르면 앱을 열고, 이미 열려 있으면 앞으로 가져옵니다.",
        "keyappearance.apps": "앱",
        "keyappearance.background": "백그라운드에서 계속",
        "keyappearance.busyOther": "%1$@에서 전송이 진행 중입니다 — 이 키를 변경하려면 끝날 때까지 기다리세요.",
        "keyappearance.chooseFile": "파일 선택…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "앱 열기",
        "keyappearance.ownImage": "내 이미지",
        "keyappearance.ownImageNote": "가운데를 기준으로 잘라 72 × 72로 조정합니다. 키의 동작은 바뀌지 않습니다.",
        "keyappearance.presets": "프리셋",
        "keyappearance.searchApp": "앱 검색",
        "keyappearance.step.prepare": "준비",
        "keyappearance.step.send": "전송",
        "keyappearance.subtitle": "화면에 표시할 내용과 키의 동작을 선택하세요",
        "keyappearance.title": "%1$@ 키",
        "keyappearance.transferNote": "전송에는 약 20초가 걸립니다. 키보드가 슬롯을 준비한 뒤(이전 이미지는 키보드가 직접 지웁니다) 새 이미지를 64바이트 패킷으로 받습니다. 키보드를 뽑지 마세요.",

        // MARK: keyboard
        "keyboard.activeBadge": "사용 중",
        "keyboard.ansiShape": "ANSI 형태: 넓은 Enter, 맨 윗줄 끝의 \\",
        "keyboard.asPrinted": "인쇄된 대로",
        "keyboard.automatic": "자동",
        "keyboard.chosen": "직접 선택",
        "keyboard.clearRemaps": "리맵 지우기",
        "keyboard.detected": "감지됨",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. 다시 시작할 때까지 유지됩니다. 키보드에 저장되는 리맵: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO 키",
        "keyboard.isoMuteNote": "macOS가 키보드를 ANSI로 처리하면 Z 왼쪽 키가 아무것도 입력하지 않습니다",
        "keyboard.isoMuteTitle": "ISO 키가 반응하지 않나요?",
        "keyboard.isoShape": "ISO 형태: 높은 Enter, W/Z 왼쪽의 추가 키",
        "keyboard.legend.at": "' 키의 @",
        "keyboard.legend.backslash": "\\ | Z 왼쪽",
        "keyboard.legend.quote": "⇧2의 \"",
        "keyboard.legend.rightOfSemicolon": "; 오른쪽",
        "keyboard.macLayout": "macOS 자판 배열",
        "keyboard.macLayoutNote": "macOS가 키에 인쇄된 문자를 입력하도록 합니다",
        "keyboard.noMacLayout": "“%1$@”에 해당하는 macOS 자판 배열이 설치되어 있지 않습니다. 시스템 설정 → 키보드 → 입력 소스에서 추가하세요.",
        "keyboard.remapApplied": "ISO 리맵을 적용했습니다 (다시 시작할 때까지).",
        "keyboard.remapIso": "ISO 키 리맵",
        "keyboard.remapsCleared": "hidutil 리맵을 지웠습니다.",
        "keyboard.reportsLayout": "키보드가 “%1$@”(으)로 알려 줍니다. 이 선택이 더 이상 필요하지 않으면 자동으로 되돌리세요.",
        "keyboard.switchedTo": "자판 배열을 %1$@(으)로 전환했습니다.",
        "keyboard.title": "실제 키보드",
        "keyboard.titleNote": "Base Camp처럼 키보드에서 읽어 옵니다. 그림, 키, 효과가 이에 맞춰집니다",
        "keyboard.unknown": "알 수 없음",
        "keyboard.use": "%1$@ 사용",
        "keyboard.verifiedNote1": "각 키의 모양과 조명은 키보드의 격자를 따릅니다. 실제 키보드에서 확인된 것은 UK 배열뿐입니다.",
        "keyboard.verifiedNote2": "키 문자는 Base Camp의 표에서 가져오고 모양은 LED 격자를 따릅니다. 실제 키보드에서 확인된 것은 UK 배열뿐입니다.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "다이얼 전송이 중단되었습니다 — “키보드 잠금 해제”(시스템 페이지)를 사용하거나 다시 연결하세요",
        "keyboardError.dialRefused": "다이얼이 전송을 거부했습니다 (아무것도 기록되지 않음)",
        "keyboardError.interrupted": "전송이 중단되었습니다 — “키보드 잠금 해제”(시스템 페이지)를 사용하거나 다시 연결하세요",
        "keyboardError.refused": "키보드가 전송을 거부했습니다 (아무것도 기록되지 않음) — 다시 시도하세요. 계속되면 “키보드 잠금 해제”(시스템 페이지)를 사용하세요",
        "keyboardError.selectTarget": "키보드가 키 선택에 응답하지 않습니다 — “키보드 잠금 해제”(시스템 페이지)를 사용하거나 다시 연결하세요",

        // MARK: layout
        "layout.french": "프랑스어 (AZERTY)",
        "layout.german": "독일어 (QWERTZ)",
        "layout.hebrew": "히브리어",
        "layout.italian": "이탈리아어",
        "layout.korean": "한국어",
        "layout.nordic": "북유럽",
        "layout.portuguese": "포르투갈어",
        "layout.spanish": "스페인어",
        "layout.uk": "영국 (ISO)",
        "layout.us": "미국 (ANSI)",

        // MARK: lighting
        "lighting.addColour": "색 추가",
        "lighting.allHues": "키보드가 만들어 내는 모든 색조.",
        "lighting.backgroundColour": "배경",
        "lighting.brightness": "밝기",
        "lighting.byKeyboard": "키보드에서 실행 — 앱 없이도 계속됩니다",
        "lighting.byMac": "Mac에서 계산 — 앱을 열어 두세요",
        "lighting.clearAll": "모두 지우기",
        "lighting.clockwise": "시계 방향",
        "lighting.colors": "색상",
        "lighting.colour": "색",
        "lighting.colour1": "색 1",
        "lighting.colour2": "색 2",
        "lighting.colourCount.one": "색 %1$@개",
        "lighting.colourCount.other": "색 %1$@개",
        "lighting.counterclockwise": "반시계 방향",
        "lighting.direction": "방향",
        "lighting.editEllipsis": "편집…",
        "lighting.fast": "빠름",
        "lighting.flameNote": "불씨에서 흰색까지 이어지는 고정 불꽃 단계.",
        "lighting.freeze": "키보드에 고정",
        "lighting.freezeNote": "현재 프레임을 Custom 슬롯으로 보내 저장합니다. 앱 없이도 유지됩니다.",
        "lighting.keyColour": "키",
        "lighting.ledsBlack": "효과가 실행되는 동안 모든 LED는 꺼진 상태입니다.",
        "lighting.macNote": "키 하나하나를 초당 30프레임으로, 선택한 팔레트로 렌더링",
        "lighting.normal": "Normal",
        "lighting.offNote": "백라이트와 측면 스트립이 꺼져 있습니다. 다시 켜려면 다른 효과를 선택하세요.",
        "lighting.officialEffects": "공식 효과",
        "lighting.officialNote": "Windows 앱과 똑같이 전송되는 Base Camp의 효과",
        "lighting.paintHint": "위 키보드의 키를 클릭하거나 드래그하세요.",
        "lighting.paintKeys": "키별로 칠하기",
        "lighting.palette": "Palette",
        "lighting.paused": "일시 정지됨",
        "lighting.reapply": "다시 적용",
        "lighting.rightClickHint": "색 견본을 오른쪽 클릭하면 제거됩니다.",
        "lighting.rotation": "회전 방향",
        "lighting.runningOnKeyboard": "키보드에서 실행 중",
        "lighting.savedInProfile": "키보드의 활성 프로필에 저장됨",
        "lighting.slow": "느림",
        "lighting.speed": "속도",
        "lighting.title": "조명",

        // MARK: live
        "live.keyboard": "키보드 · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · 일시 정지",
        "live.pause": "일시 정지",
        "live.start": "시작",

        // MARK: macfx
        "macfx.aurora": "오로라",
        "macfx.equalizer": "이퀄라이저",
        "macfx.fire": "불",
        "macfx.gradient": "그라디언트",
        "macfx.plasma": "Plasma",
        "macfx.rain": "디지털 비",
        "macfx.ripples": "물결",
        "macfx.scanner": "스캐너",
        "macfx.solid": "단색",
        "macfx.spectrum": "스펙트럼",
        "macfx.spiral": "나선",
        "macfx.stars": "별",
        "macfx.waves": "파도",

        // MARK: menu
        "menu.allowAccessibility": "손쉬운 사용 허용…",
        "menu.disconnected": "키보드 연결 끊김",
        "menu.firmwareBlocked": "지원되지 않는 펌웨어 — 키보드 무시됨",
        "menu.keyboardEffects": "키보드 효과",
        "menu.launchAtLogin": "로그인 시 실행",
        "menu.macEffects": "Mac 효과",
        "menu.manageProfiles": "프로필 관리…",
        "menu.newProfile": "새 프로필",
        "menu.open": "Everest 열기…",
        "menu.pauseEffect": "효과 일시 정지",
        "menu.profile": "프로필: %1$@",
        "menu.resumeEffect": "효과 재개",

        // MARK: metric
        "metric.disk": "디스크",
        "metric.network": "네트워크",
        "metric.volume": "볼륨",

        // MARK: mode
        "mode.clock": "시계",
        "mode.disk": "디스크",
        "mode.image": "이미지",
        "mode.network": "네트워크",
        "mode.volume": "볼륨",

        // MARK: overview
        "overview.actionsActive": "동작 활성",
        "overview.changeLighting": "조명 변경",
        "overview.dialSubtitle": "미디어 독의 원형 화면",
        "overview.keyboardEffect": "키보드 효과",
        "overview.macEffect": "Mac에서 계산한 효과",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "불씨",
        "palette.forest": "숲",
        "palette.ice": "얼음",
        "palette.neon": "네온",
        "palette.ocean": "바다",
        "palette.sunset": "노을",
        "palette.vapor": "베이퍼",

        // MARK: preset
        "preset.bolt": "번개",
        "preset.calendar": "캘린더",
        "preset.captureScreen": "화면 캡처",
        "preset.captureZone": "영역 캡처",
        "preset.category.apps": "앱",
        "preset.category.decor": "아이콘만",
        "preset.category.media": "미디어",
        "preset.coffee": "커피",
        "preset.flame": "불꽃",
        "preset.game": "컨트롤러",
        "preset.heart": "하트",
        "preset.home": "홈",
        "preset.lock": "잠금",
        "preset.music": "음악",
        "preset.mute": "음소거",
        "preset.next": "다음",
        "preset.playpause": "재생 / 일시 정지",
        "preset.previous": "이전",
        "preset.sleepDisplay": "화면 끄기",
        "preset.star": "별",
        "preset.volumeDown": "볼륨 −",
        "preset.volumeUp": "볼륨 +",

        // MARK: profile
        "profile.defaultName": "프로필 %1$@",
        "profile.main": "기본",

        // MARK: profiles
        "profiles.addApp": "앱 추가 (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "자동 전환",
        "profiles.autoSwitchHint": "앱이 열려 있거나 데몬이 실행 중일 때 작동합니다. 다이얼에서 직접 고른 프로필은 프로필이 없는 앱에 머무르는 동안 바뀌지 않습니다.",
        "profiles.autoSwitchNote": "앱이 맨 앞에 오면 키보드가 그 앱의 프로필로 전환됩니다",
        "profiles.deleteHelp": "앱에서 이 프로필 삭제",
        "profiles.dialMode": "다이얼: %1$@",
        "profiles.dialOnActivate": "활성화 시 다이얼",
        "profiles.dialUnchanged": "다이얼 변경 없음",
        "profiles.dontChange": "변경하지 않음",
        "profiles.enable": "사용",
        "profiles.freeSlots": "빈 슬롯 %1$@개",
        "profiles.hardwareNote": "키보드는 프로필 5개를 메모리에 보관합니다 (다이얼의 Profile 메뉴). 각 프로필에는 고유한 조명, 리맵, D1–D4 이미지가 있으며, 앱은 키 동작, 다이얼 모드, 연결된 앱을 추가합니다.",
        "profiles.header": "프로필 %1$@",
        "profiles.iconAndColour": "아이콘 및 색상",
        "profiles.keyboardLighting": "키보드 조명",
        "profiles.keyboardProfiles": "키보드 프로필",
        "profiles.keysNote": "이 프로필이 활성인 동안 D1–D4 키와 조명은 각각의 페이지에서 설정하며, 이 프로필에 저장됩니다.",
        "profiles.lightingFirmware": "조명: %1$@",
        "profiles.lightingMac": "Mac 조명: %1$@",
        "profiles.linkedApps": "연결된 앱",
        "profiles.manage": "관리…",
        "profiles.namePlaceholder": "코딩, 음악…",
        "profiles.noLinkedApp": "연결된 앱 없음",
        "profiles.otherwise": "그렇지 않으면 다음으로 되돌리기",
        "profiles.slot": "슬롯 %1$@",
        "profiles.slotOfKeyboard": "키보드 슬롯 %1$@",

        // MARK: reset
        "reset.title": "초기화",

        // MARK: section
        "section.buttons.subtitle": "디스플레이 키 4개 각각에 macOS 동작 지정",
        "section.buttons.title": "D1–D4 키",
        "section.displays.subtitle": "다이얼의 원형 화면과 숫자 패드의 디스플레이 키",
        "section.displays.title": "디스플레이",
        "section.keyboard.subtitle": "감지된 키보드 배열과 일치하는 macOS 자판 배열",
        "section.keyboard.title": "배열",
        "section.lighting.subtitle": "공식 키보드 효과와 Mac에서 렌더링하는 동적 효과",
        "section.overview.subtitle": "내 Everest Max를 한눈에",
        "section.overview.title": "개요",
        "section.profiles.subtitle": "키보드에 저장된 프로필 5개, 각각 고유한 키, 조명, 앱 포함",
        "section.profiles.title": "프로필",
        "section.system.subtitle": "키 데몬, 모니터링 및 문제 해결",
        "section.system.title": "시스템",

        // MARK: settings
        "settings.language.automatic": "자동 (시스템 언어)",
        "settings.language.note": "인터페이스, 메뉴 막대 메뉴, 메시지의 언어입니다.",
        "settings.language.title": "언어",

        // MARK: status
        "status.animationPaused": "애니메이션 일시 정지 — 키보드는 마지막 프레임을 유지합니다.",
        "status.appIconUnreadable": "앱 아이콘을 읽을 수 없습니다.",
        "status.appNoId": "이 앱에는 식별자가 없어 연결할 수 없습니다.",
        "status.changeFailed": "변경할 수 없습니다: %1$@",
        "status.cleaning": "정리 중",
        "status.clockSynced": "시계를 Mac과 동기화했습니다.",
        "status.configSaved": "설정을 저장했습니다.",
        "status.daemonOff": "D1–D4 키를 껐습니다.",
        "status.daemonOn": "D1–D4 키 활성.",
        "status.daemonStartFailed": "데몬을 시작할 수 없습니다: %1$@",
        "status.dialImageSent": "다이얼로 이미지를 보냈습니다.",
        "status.dialMode": "다이얼: %1$@.",
        "status.displayLabel": "화면",
        "status.effectApplied": "%1$@ 효과를 적용하고 프로필에 저장했습니다.",
        "status.effectRunningKeyboard": "“%1$@” 효과가 키보드에서 실행 중입니다.",
        "status.factoryIconRestored": "%1$@의 초기 아이콘을 복원했습니다.",
        "status.frozen": "프레임을 고정해 키보드의 “Custom” 슬롯에 저장했습니다.",
        "status.iconDrawFailed": "아이콘을 그릴 수 없습니다.",
        "status.iconSent": "아이콘을 %2$@초 만에 %1$@로 보냈습니다.",
        "status.keyboardConnected": "키보드가 연결되었습니다.",
        "status.keyboardGone": "키보드 연결이 끊겼습니다 — 다시 연결하면 효과가 재개됩니다.",
        "status.layoutAuto": "배열: 자동 감지.",
        "status.layoutForced": "배열 고정: %1$@.",
        "status.leftoversCleared": "키보드 메모리에서 남은 동작을 지웠습니다.",
        "status.loginApproval": "시스템 설정 → 일반 → 로그인 항목에서 승인해야 합니다.",
        "status.previewOnly": "키보드를 찾을 수 없습니다 — 미리보기는 계속 사용할 수 있습니다.",
        "status.profileActivated": "“%1$@” 프로필을 활성화했습니다.",
        "status.profileActivatedFrontApp": "“%1$@” 프로필을 활성화했습니다 (앱이 맨 앞에 있음).",
        "status.profileFromKeyboard": "“%1$@” 프로필 활성 (키보드에서 선택).",
        "status.profileRemoved": "앱에서 프로필을 제거했습니다 (키보드는 슬롯 %1$@에 설정을 유지합니다).",
        "status.ready": "준비됨",
        "status.recovering": "복구",
        "status.recoverySent": "복구 시퀀스를 보냈습니다.",
        "status.saving": "저장 중",
        "status.sendingImage": "이미지 전송 중…",
        "status.uploadBusy": "%1$@에서 전송이 진행 중입니다 — 몇 초만 기다리세요.",
        "status.uploadBusyAlready": "%1$@에서 이미 전송이 진행 중입니다 — 몇 초만 기다리세요.",
        "status.uploadFailed": "전송 실패: %1$@",
        "status.uploadFailedKey": "%1$@: 전송 실패 — %2$@",
        "status.uploadStarted": "%1$@: 키보드로 이미지 전송 중…",

        // MARK: system
        "system.askAgain": "다시 요청",
        "system.autoDaemon": "D1–D4 키 자동 활성화",
        "system.autoDaemonNote": "데몬은 앱과 함께 시작되고, 키보드를 다시 연결하면 스스로 재연결하며, 멈추면 다시 시작됩니다.",
        "system.autostartHint": "로그인 시 자동 시작: 터미널에서 ./install-daemon.sh 실행.",
        "system.background": "Everest는 메뉴 막대에서 백그라운드로 작동합니다",
        "system.daemonSubtitle": "D1–D4 동작을 실행하고 다이얼에 값을 보냅니다",
        "system.daemonTitle": "키 데몬",
        "system.keepRunning": "윈도우를 닫아도 Everest 계속 실행",
        "system.keepRunningNote": "D1–D4 키, 프로필, 효과가 계속 작동하며 아이콘은 메뉴 막대에 남습니다. 종료: 아이콘 메뉴 또는 ⌘Q.",
        "system.keyboardCard": "키보드",
        "system.keyboardCardNote": "펌웨어가 보고한 상태",
        "system.launchAtLogin": "로그인 시 Everest 실행",
        "system.launchAtLoginNote": "윈도우를 열지 않고 메뉴 막대에서 조용히 시작합니다.",
        "system.launchedFrom": "Everest가 %1$@에서 실행 중입니다. 안정적으로 시작하려면 /Applications로 복사하세요 (./make-app.sh --install). 외장 볼륨은 로그인 시 항상 마운트되어 있지는 않습니다.",
        "system.lightProfile": "조명 프로필",
        "system.listening": "감지 중",
        "system.metricsEvery": "데몬은 실행 중 0.5초마다 값을 보냅니다.",
        "system.modules": "모듈",
        "system.monitoring": "모니터링",
        "system.monitoringNote": "다이얼에 표시되는 시스템 값",
        "system.noAccessibility": "Everest에 손쉬운 사용 권한이 없습니다",
        "system.noAccessibilityNote": "권한이 없으면 “단축키”와 “텍스트” 동작이 아무것도 하지 않습니다 (앱, 명령, 링크 동작은 작동합니다). 목록에서 Everest가 이미 체크되어 있다면 항목이 오래된 것입니다. 선택한 뒤 “−”로 제거하고 “+”로 다시 추가(Everest.app)한 다음 데몬을 다시 시작하세요.",
        "system.openSettings": "설정 열기",
        "system.sendMetrics": "CPU, GPU, RAM, 디스크, 네트워크, 볼륨 보내기",
        "system.stoppedState": "중지됨",
        "system.unlock": "키보드 잠금 해제",
        "system.unlockNote": "이미지 전송이 중단된 경우 “잠금 해제”가 SDK 리셋을 보냅니다. 그래도 해결되지 않으면 키보드를 뽑았다가 다시 연결하세요. 잃는 것은 없습니다.",

        // MARK: upload
        "upload.phase.connect": "키보드에 연결 중",
        "upload.phase.done": "완료",
        "upload.phase.finish": "마무리 중",
        "upload.phase.prepare": "키보드가 슬롯을 준비하는 중",
        "upload.phase.send": "이미지 전송 중",

        "status.configReloaded": "앱 밖에서 설정이 변경되어 다시 불러왔습니다.",

        // MARK: pad
        "keyappearance.live": "실시간",
        "keyappearance.liveAction": "해당 앱도 열기",
        "keyappearance.liveNote": "패드가 연결되어 있는 동안 값이 바뀔 때마다(최대 초당 1회) 다시 그립니다. 키의 동작은 유지됩니다.",
        "pad.keysActive": "P1–P12 키 활성",
        "pad.overview.keys": "12개 중 %1$@개 키 설정됨",
        "pad.overview.firmware": "펌웨어 %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "DisplayPad 펌웨어 %1$@은(는) 지원되지 않습니다",
        "pad.unsupportedNote": "Everest는 테스트된 버전인 펌웨어 8에만 쓰기를 하며, 이 패드는 건드리지 않습니다.",
        "pad.noAnswer": "DisplayPad가 응답하지 않음",
        "pad.noAnswerNote": "연결되어 있지만 응답하지 않습니다. 몇 초 기다리거나 Mac에 직접 연결하세요.",
        "section.displaypad.subtitle": "이미지와 macOS 동작을 지정할 수 있는 12개의 화면 키",
        "pad.connected": "DisplayPad 연결됨",
        "pad.connectedNote": "변경 후 1초 이내에 이미지가 전송되며, 패드는 분리될 때까지 이미지를 유지합니다.",
        "pad.notConnected": "DisplayPad 연결 안 됨",
        "pad.notConnectedNote": "Mac에 직접 연결하세요. 일부 USB 허브에서는 화면이 검게 유지됩니다.",
        "pad.brightness": "밝기",
        "pad.keys": "키",
        "pad.keysNote": "키를 클릭해 편집하세요. 이미지와 동작은 «%1$@» 프로필에 저장됩니다.",
        "pad.clearKey": "지우기",
        "pad.clearKeyHelp": "%1$@의 이미지와 동작을 제거합니다",
        "pad.noImage": "이미지 없음",
        "pad.ownImageNote": "가운데를 기준으로 잘라 102 × 102로 크기를 조정합니다. 키의 동작은 바뀌지 않습니다.",
        "pad.daemonStoppedNote": "DisplayPad 키는 실행 중일 때만 작동합니다.",
        "pad.status.sent": "%1$@: DisplayPad로 전송했습니다.",
        "pad.status.savedOffline": "%1$@: 저장됨 — DisplayPad를 연결하면 표시됩니다.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
