// Interface strings — fr. Generated from the spec once, now edited by hand.
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let fr: [String: String] = [
        // MARK: action
        "action.app": "Application",
        "action.keypress": "Raccourci",
        "action.none": "Aucune",
        "action.open": "Fichier",
        "action.shell": "Commande",
        "action.text": "Texte",
        "action.textToType": "Texte à taper",
        "action.url": "Lien",

        // MARK: app
        "app.closeWindow": "Fermer la fenêtre",
        "app.copy": "Copier",
        "app.cut": "Couper",
        "app.edit": "Édition",
        "app.hide": "Masquer Everest",
        "app.paste": "Coller",
        "app.quit": "Quitter Everest",
        "app.selectAll": "Tout sélectionner",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "Les actions macOS et les raccourcis tapés demandent l'autorisation Accessibilité (Réglages → Confidentialité et sécurité).",
        "buttons.actionRan": "Action de %1$@ exécutée.",
        "buttons.appHint": "Ouvre l'app ou la ramène au premier plan",
        "buttons.clearLeftovers": "Effacer les actions résiduelles",
        "buttons.daemonStopped": "Le daemon est arrêté",
        "buttons.daemonStoppedNote": "Les actions ne s'exécutent que lorsqu'il écoute les touches D1–D4.",
        "buttons.factoryValues": "Valeurs d'usine",
        "buttons.factoryValuesHelp": "Rétablit l'image et l'action d'origine de %1$@",
        "buttons.flashMemory": "Mémoire du clavier",
        "buttons.flashMemoryNote": "Base Camp peut laisser des actions dans la flash (ex. D4 qui envoie Échap)",
        "buttons.keyHeader": "TOUCHE %1$@",
        "buttons.noAction": "Aucune action — la touche est ignorée.",
        "buttons.noApp": "Aucune app choisie",
        "buttons.pickPresetAppImage": "Préréglage, app ou image pour %1$@",
        "buttons.presetsAndIcon": "Préréglages et icône…",

        // MARK: clock
        "clock.analog": "Analogique",
        "clock.digital": "Numérique",
        "clock.sync": "Synchroniser",

        // MARK: colormode
        "colormode.dual": "Deux couleurs",
        "colormode.quad": "4 couleurs",
        "colormode.rainbow": "Arc-en-ciel",
        "colormode.single": "Une couleur",
        "colormode.withBackground": "Touche + fond",

        // MARK: common
        "common.active": "Actif",
        "common.add": "Nouveau",
        "common.choose": "Choisir…",
        "common.close": "Fermer",
        "common.configure": "Configurer",
        "common.delete": "Supprimer",
        "common.edit": "Modifier",
        "common.name": "Nom",
        "common.other": "Autre…",
        "common.refresh": "Rafraîchir",
        "common.remove": "Retirer",
        "common.start": "Démarrer",
        "common.stop": "Arrêter",
        "common.test": "Tester",

        // MARK: daemon
        "daemon.keysActive": "Touches D1–D4 actives",
        "daemon.stopped": "Daemon arrêté",

        // MARK: device
        "device.blocked": "Firmware non pris en charge",
        "device.connected": "Connecté",
        "device.core": "Everest Core",
        "device.dial": "Molette",
        "device.disconnected": "Déconnecté",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Everest Max complet",
        "device.keyboardMissing": "clavier indisponible",
        "device.keyboardUnavailable": "Clavier indisponible (introuvable, ou firmware non pris en charge).",
        "device.notConnected": "Non connecté",
        "device.refresh.help": "Rafraîchir l'état du clavier",
        "device.withDock": "Clavier + dock média",
        "device.withNumpad": "Clavier + pavé numérique",

        // MARK: displays
        "displays.change": "Changer…",
        "displays.chooseImage": "Choisir une image…",
        "displays.dial.subtitle": "Écran rond 240 × 204 du dock média",
        "displays.display": "Affichage",
        "displays.factoryIcon": "Icône d'usine",
        "displays.factoryLogo": "Logo d'usine",
        "displays.imageCropped": "L'image est recadrée en 240 × 204.",
        "displays.imagesResized": "Les images sont redimensionnées en 72 × 72.",
        "displays.keys.subtitle": "Quatre écrans 72 × 72 au-dessus du pavé numérique",
        "displays.keys.title": "Touches-écrans",
        "displays.logoRestored": "Logo Mountain restauré sur la molette.",
        "displays.metricsNote": "CPU, GPU, RAM, disque, réseau et volume affichent les valeurs envoyées par le daemon (page Système).",

        // MARK: factory
        "factory.activityMonitor": "Moniteur d'activité",
        "factory.sleep": "Veille",

        // MARK: firmware
        "firmware.block.body": "Everest n'a été testé qu'avec le firmware %1$@. Pour ne pas risquer de rendre ton clavier inutilisable, il ne lui envoie rien tant que ce n'est pas cette version : ni éclairage, ni images, ni actions.",
        "firmware.block.check": "Vérifier à nouveau",
        "firmware.block.detected": "Firmware détecté : %1$@",
        "firmware.block.how": "Mountain ne propose la mise à jour du firmware que dans son application officielle Base Camp pour Windows. Branche le clavier sur un PC Windows, installe Base Camp, mets le firmware à jour, puis rebranche le clavier sur ce Mac : Everest le détecte tout seul.",
        "firmware.block.howTitle": "Comment mettre le clavier à jour",
        "firmware.block.tested": "Firmware testé : %1$@",
        "firmware.block.title": "Firmware non pris en charge",
        "firmware.block.unreadableBody": "Everest ne peut pas vérifier la version du firmware du clavier, donc il n'y touche pas. Débranche et rebranche le clavier, puis réessaie.",
        "firmware.block.unreadableTitle": "Firmware illisible",
        "firmware.block.why": "Everest ne met pas le firmware à jour lui-même : c'est la même opération que celle qui peut rendre un clavier inutilisable, et elle ne peut pas être testée ici.",
        "firmware.status.unreadable": "Le clavier n'a pas indiqué son firmware — il n'est pas modifié.",
        "firmware.status.unsupported": "Firmware %1$@ non pris en charge (testé : %2$@) — le clavier n'est pas modifié.",

        // MARK: fx
        "fx.breathing": "Respiration",
        "fx.breathing.desc": "Pulsation douce",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Gouttes qui tombent",
        "fx.off": "Éteint",
        "fx.off.desc": "Tout est éteint",
        "fx.reactive": "Réactif",
        "fx.reactive.desc": "S'allume à la frappe",
        "fx.static": "Statique",
        "fx.static.desc": "Couleur fixe",
        "fx.tornado": "Tornade",
        "fx.tornado.desc": "Tourne autour du centre",
        "fx.wave": "Vague",
        "fx.wave.desc": "Traverse le clavier",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Onde depuis la touche",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Appliquer aussi l'action du préréglage",
        "keyappearance.appHint": "La touche ouvre l'app, ou la ramène au premier plan si elle est déjà ouverte.",
        "keyappearance.apps": "Applications",
        "keyappearance.background": "Continuer en arrière-plan",
        "keyappearance.busyOther": "Envoi en cours sur %1$@ — attends qu'il se termine pour modifier cette touche.",
        "keyappearance.chooseFile": "Choisir un fichier…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Ouvre l'app",
        "keyappearance.ownImage": "Ta propre image",
        "keyappearance.ownImageNote": "Elle est recadrée au centre et redimensionnée en 72 × 72. L'action de la touche ne change pas.",
        "keyappearance.presets": "Préréglages",
        "keyappearance.searchApp": "Rechercher une app",
        "keyappearance.step.prepare": "Préparation",
        "keyappearance.step.send": "Envoi",
        "keyappearance.subtitle": "Choisis ce que l'écran affiche et ce que fait la touche",
        "keyappearance.title": "Touche %1$@",
        "keyappearance.transferNote": "Un envoi prend environ 20 secondes : le clavier prépare l'emplacement (il efface lui-même l'ancienne image), puis reçoit la nouvelle par paquets de 64 octets. Ne débranche pas le clavier.",

        // MARK: keyboard
        "keyboard.activeBadge": "ACTIVE",
        "keyboard.ansiShape": "Forme ANSI : Entrée large, \\ au bout de la rangée du haut",
        "keyboard.asPrinted": "comme imprimé",
        "keyboard.automatic": "Automatique",
        "keyboard.chosen": "CHOISIE À LA MAIN",
        "keyboard.clearRemaps": "Effacer les remaps",
        "keyboard.detected": "DÉTECTÉE",
        "keyboard.hidutilNote": "hidutil : usage 0x64 → 0x31. Dure jusqu'au redémarrage. Pour un remap stocké dans le clavier : everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "touche ISO",
        "keyboard.isoMuteNote": "Si macOS traite le clavier en ANSI, la touche à gauche de Z ne produit rien",
        "keyboard.isoMuteTitle": "Touche ISO muette ?",
        "keyboard.isoShape": "Forme ISO : Entrée haute, touche en plus à gauche de W/Z",
        "keyboard.legend.at": "@ sur la touche '",
        "keyboard.legend.backslash": "\\ | à gauche de Z",
        "keyboard.legend.quote": "\" sur ⇧2",
        "keyboard.legend.rightOfSemicolon": "à droite de ;",
        "keyboard.macLayout": "Disposition macOS",
        "keyboard.macLayoutNote": "Pour que macOS écrive ce qui est imprimé sur les touches",
        "keyboard.noMacLayout": "Aucune disposition macOS correspondant à « %1$@ » n'est installée : ajoute-la dans Réglages Système → Clavier → Sources de saisie.",
        "keyboard.remapApplied": "Remap ISO appliqué (jusqu'au redémarrage).",
        "keyboard.remapIso": "Remapper la touche ISO",
        "keyboard.remapsCleared": "Remaps hidutil effacés.",
        "keyboard.reportsLayout": "Le clavier annonce « %1$@ ». Repasse en automatique si ce choix n'est plus nécessaire.",
        "keyboard.switchedTo": "Disposition basculée sur %1$@.",
        "keyboard.title": "Clavier physique",
        "keyboard.titleNote": "Lu dans le clavier, comme Base Camp : le dessin, les touches et les effets s'y adaptent",
        "keyboard.unknown": "inconnue",
        "keyboard.use": "Utiliser %1$@",
        "keyboard.verifiedNote1": "La forme et l'éclairage de chaque touche suivent la grille du clavier ; seule la disposition UK a été vérifiée sur un vrai clavier.",
        "keyboard.verifiedNote2": "Les légendes viennent des tables de Base Camp et la forme suit la grille des LED ; seule la disposition UK a été vérifiée sur un vrai clavier.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "transfert vers le dial interrompu — utilise « Débloquer le clavier » (page Système) ou rebranche-le",
        "keyboardError.dialRefused": "le dial a refusé l'envoi (rien n'a été écrit)",
        "keyboardError.interrupted": "transfert interrompu — utilise « Débloquer le clavier » (page Système) ou rebranche-le",
        "keyboardError.refused": "le clavier a refusé l'envoi (rien n'a été écrit) — réessaie ; s'il persiste, utilise « Débloquer le clavier » (page Système)",
        "keyboardError.selectTarget": "le clavier ne répond pas à la sélection des touches — utilise « Débloquer le clavier » (page Système) ou rebranche-le",

        // MARK: layout
        "layout.french": "Français (AZERTY)",
        "layout.german": "Allemand (QWERTZ)",
        "layout.hebrew": "Hébreu",
        "layout.italian": "Italien",
        "layout.korean": "Coréen",
        "layout.nordic": "Nordique",
        "layout.portuguese": "Portugais",
        "layout.spanish": "Espagnol",
        "layout.uk": "Royaume-Uni (ISO)",
        "layout.us": "US (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Ajouter une couleur",
        "lighting.allHues": "Toutes les teintes, générées par le clavier.",
        "lighting.backgroundColour": "Fond",
        "lighting.brightness": "Luminosité",
        "lighting.byKeyboard": "Exécuté par le clavier — continue sans l'app",
        "lighting.byMac": "Calculé par le Mac — garde l'app ouverte",
        "lighting.clearAll": "Tout effacer",
        "lighting.clockwise": "Horaire",
        "lighting.colors": "Couleurs",
        "lighting.colour": "Couleur",
        "lighting.colour1": "Couleur 1",
        "lighting.colour2": "Couleur 2",
        "lighting.colourCount.one": "%1$@ couleur",
        "lighting.colourCount.other": "%1$@ couleurs",
        "lighting.counterclockwise": "Anti-horaire",
        "lighting.direction": "Direction",
        "lighting.editEllipsis": "Modifier…",
        "lighting.fast": "Rapide",
        "lighting.flameNote": "Rampe de flamme fixe, de la braise au blanc.",
        "lighting.freeze": "Figer dans le clavier",
        "lighting.freezeNote": "Envoie l'image actuelle dans le slot Custom et l'enregistre : elle reste sans l'app.",
        "lighting.keyColour": "Touche",
        "lighting.ledsBlack": "Toutes les LED sont noires tant que l'effet tourne.",
        "lighting.macNote": "Rendus touche par touche à 30 images/s, avec ta palette",
        "lighting.normal": "Normal",
        "lighting.offNote": "Le rétroéclairage et les bandes latérales sont éteints. Choisis un autre effet pour les rallumer.",
        "lighting.officialEffects": "Effets officiels",
        "lighting.officialNote": "Les effets de Base Camp, envoyés exactement comme l'app Windows",
        "lighting.paintHint": "Clique ou glisse sur les touches du clavier ci-dessus.",
        "lighting.paintKeys": "Peindre touche par touche",
        "lighting.palette": "Palette",
        "lighting.paused": "En pause",
        "lighting.reapply": "Réappliquer",
        "lighting.rightClickHint": "Clic droit sur une pastille pour la supprimer.",
        "lighting.rotation": "Sens de rotation",
        "lighting.runningOnKeyboard": "En cours sur le clavier",
        "lighting.savedInProfile": "Enregistré dans le profil actif du clavier",
        "lighting.slow": "Lent",
        "lighting.speed": "Vitesse",
        "lighting.title": "Éclairage",

        // MARK: live
        "live.keyboard": "Clavier · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · en pause",
        "live.pause": "Pause",
        "live.start": "Lancer",

        // MARK: macfx
        "macfx.aurora": "Aurore",
        "macfx.equalizer": "Égaliseur",
        "macfx.fire": "Feu",
        "macfx.gradient": "Dégradé",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Pluie numérique",
        "macfx.ripples": "Ondes",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Couleur unie",
        "macfx.spectrum": "Spectre",
        "macfx.spiral": "Spirale",
        "macfx.stars": "Étoiles",
        "macfx.waves": "Vagues",

        // MARK: menu
        "menu.allowAccessibility": "Autoriser l'accessibilité…",
        "menu.disconnected": "Clavier déconnecté",
        "menu.firmwareBlocked": "Firmware non pris en charge — clavier ignoré",
        "menu.keyboardEffects": "Effets du clavier",
        "menu.launchAtLogin": "Lancer au démarrage",
        "menu.macEffects": "Effets Mac",
        "menu.manageProfiles": "Gérer les profils…",
        "menu.newProfile": "Nouveau profil",
        "menu.open": "Ouvrir Everest…",
        "menu.pauseEffect": "Mettre l'effet en pause",
        "menu.profile": "Profil : %1$@",
        "menu.resumeEffect": "Reprendre l'effet",

        // MARK: metric
        "metric.disk": "DISQUE",
        "metric.network": "RÉSEAU",
        "metric.volume": "VOLUME",

        // MARK: mode
        "mode.clock": "Horloge",
        "mode.disk": "Disque",
        "mode.image": "Image",
        "mode.network": "Réseau",
        "mode.volume": "Volume",

        // MARK: overview
        "overview.actionsActive": "Actions actives",
        "overview.changeLighting": "Changer l'éclairage",
        "overview.dialSubtitle": "Écran rond du dock média",
        "overview.keyboardEffect": "Effet du clavier",
        "overview.macEffect": "Effet calculé par le Mac",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Braise",
        "palette.forest": "Forêt",
        "palette.ice": "Glace",
        "palette.neon": "Néon",
        "palette.ocean": "Océan",
        "palette.sunset": "Couchant",
        "palette.vapor": "Vapeur",

        // MARK: preset
        "preset.bolt": "Éclair",
        "preset.calendar": "Calendrier",
        "preset.captureScreen": "Capture écran",
        "preset.captureZone": "Capture zone",
        "preset.category.apps": "Apps",
        "preset.category.decor": "Icône seule",
        "preset.category.media": "Média",
        "preset.coffee": "Café",
        "preset.flame": "Flamme",
        "preset.game": "Manette",
        "preset.heart": "Cœur",
        "preset.home": "Maison",
        "preset.lock": "Verrouiller",
        "preset.music": "Musique",
        "preset.mute": "Muet",
        "preset.next": "Suivant",
        "preset.playpause": "Lecture / Pause",
        "preset.previous": "Précédent",
        "preset.sleepDisplay": "Éteindre l'écran",
        "preset.star": "Étoile",
        "preset.volumeDown": "Volume −",
        "preset.volumeUp": "Volume +",

        // MARK: profile
        "profile.defaultName": "Profil %1$@",
        "profile.main": "Principal",

        // MARK: profiles
        "profiles.addApp": "Ajouter une app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Changement automatique",
        "profiles.autoSwitchHint": "Fonctionne quand l'app est ouverte ou que le daemon tourne. Un profil choisi à la main sur la molette n'est pas remplacé tant que tu restes dans une app sans profil.",
        "profiles.autoSwitchNote": "Le clavier passe sur le profil d'une app quand elle est au premier plan",
        "profiles.deleteHelp": "Supprimer ce profil de l'app",
        "profiles.dialMode": "Molette : %1$@",
        "profiles.dialOnActivate": "Molette à l'activation",
        "profiles.dialUnchanged": "Molette inchangée",
        "profiles.dontChange": "Ne pas changer",
        "profiles.enable": "Activer",
        "profiles.freeSlots": "%1$@ emplacement(s) libre(s)",
        "profiles.hardwareNote": "Le clavier garde cinq profils en mémoire (menu Profile de la molette). Chacun a son éclairage, ses remaps et ses images D1–D4 ; l'app y ajoute les actions des touches, le mode de la molette et les apps liées. Les douze touches du DisplayPad sont elles aussi enregistrées dans chaque profil.",
        "profiles.header": "PROFIL %1$@",
        "profiles.iconAndColour": "Icône et couleur",
        "profiles.keyboardLighting": "Éclairage du clavier",
        "profiles.keyboardProfiles": "PROFILS DU CLAVIER",
        "profiles.keysNote": "Les touches D1–D4 et l'éclairage se règlent dans leurs pages pendant que ce profil est actif : ils sont enregistrés dans ce profil.",
        "profiles.lightingFirmware": "Éclairage : %1$@",
        "profiles.lightingMac": "Éclairage Mac : %1$@",
        "profiles.linkedApps": "Apps liées",
        "profiles.manage": "Gérer…",
        "profiles.namePlaceholder": "Coding, Musique…",
        "profiles.noLinkedApp": "Aucune app liée",
        "profiles.otherwise": "Sinon, revenir sur",
        "profiles.slot": "Emplacement %1$@",
        "profiles.slotOf": "Profil %1$@ sur %2$@",

        // MARK: reset
        "reset.title": "Réinitialisation",

        // MARK: section
        "section.buttons.subtitle": "Une action macOS sur chacune des quatre touches-écrans",
        "section.buttons.title": "Touches D1–D4",
        "section.displays.subtitle": "Écran rond de la molette et touches-écrans du pavé numérique",
        "section.displays.title": "Écrans",
        "section.keyboard.subtitle": "Disposition du clavier détectée et disposition macOS correspondante",
        "section.keyboard.title": "Disposition",
        "section.lighting.subtitle": "Effets officiels du clavier et effets dynamiques calculés par le Mac",
        "section.overview.subtitle": "Ton Everest Max en un coup d'œil",
        "section.overview.title": "Aperçu",
        "section.profiles.subtitle": "Cinq profils dans le clavier, chacun avec ses touches, son éclairage et ses apps",
        "section.profiles.title": "Profils",
        "section.system.subtitle": "Daemon des boutons, monitoring et dépannage",
        "section.system.title": "Système",

        // MARK: settings
        "settings.language.automatic": "Automatique (langue du système)",
        "settings.language.note": "Langue de l'interface, du menu de la barre de menus et des messages.",
        "settings.language.title": "Langue",

        // MARK: status
        "status.animationPaused": "Animation en pause — le clavier garde la dernière image.",
        "status.appIconUnreadable": "Impossible de lire l'icône de l'app.",
        "status.appNoId": "Cette app n'a pas d'identifiant : impossible de la lier.",
        "status.changeFailed": "Impossible de modifier : %1$@",
        "status.cleaning": "Nettoyage",
        "status.clockSynced": "Horloge synchronisée avec le Mac.",
        "status.configSaved": "Configuration enregistrée.",
        "status.daemonOff": "Touches D1–D4 désactivées.",
        "status.daemonOn": "Touches D1–D4 actives.",
        "status.daemonStartFailed": "Impossible de démarrer le daemon : %1$@",
        "status.dialImageSent": "Image envoyée sur la molette.",
        "status.dialMode": "Molette : %1$@.",
        "status.displayLabel": "Écran",
        "status.effectApplied": "%1$@ appliqué et enregistré dans le profil.",
        "status.effectRunningKeyboard": "Effet « %1$@ » en cours sur le clavier.",
        "status.factoryIconRestored": "Icône d'usine restaurée sur %1$@.",
        "status.frozen": "Image figée et enregistrée dans le slot « Custom » du clavier.",
        "status.iconDrawFailed": "Impossible de dessiner l'icône.",
        "status.iconSent": "Icône envoyée sur %1$@ en %2$@ s.",
        "status.keyboardConnected": "Clavier connecté.",
        "status.keyboardGone": "Clavier déconnecté — l'effet reprendra au rebranchement.",
        "status.layoutAuto": "Disposition : détection automatique.",
        "status.layoutForced": "Disposition forcée : %1$@.",
        "status.leftoversCleared": "Actions résiduelles effacées de la mémoire du clavier.",
        "status.loginApproval": "À autoriser dans Réglages Système → Général → Ouverture.",
        "status.previewOnly": "Clavier introuvable — l'aperçu reste disponible.",
        "status.profileActivated": "Profil « %1$@ » activé.",
        "status.profileActivatedFrontApp": "Profil « %1$@ » activé (app au premier plan).",
        "status.profileFromKeyboard": "Profil « %1$@ » actif (choisi sur le clavier).",
        "status.profileRemoved": "Profil supprimé de l'app (le clavier garde ses réglages dans l'emplacement %1$@).",
        "status.ready": "Prêt",
        "status.recovering": "Récupération",
        "status.recoverySent": "Séquence de récupération envoyée.",
        "status.saving": "Enregistrement",
        "status.sendingImage": "Envoi de l'image…",
        "status.uploadBusy": "Un envoi est en cours sur %1$@ — patiente quelques secondes.",
        "status.uploadBusyAlready": "Un envoi est déjà en cours sur %1$@ — patiente quelques secondes.",
        "status.uploadFailed": "Échec de l'envoi : %1$@",
        "status.uploadFailedKey": "%1$@ : échec de l'envoi — %2$@",
        "status.uploadStarted": "%1$@ : envoi de l'image au clavier…",

        // MARK: system
        "system.askAgain": "Redemander",
        "system.autoDaemon": "Activer les touches D1–D4 automatiquement",
        "system.autoDaemonNote": "Le daemon démarre avec l'app, se reconnecte tout seul quand le clavier est rebranché et redémarre s'il s'arrête.",
        "system.autostartHint": "Démarrage automatique à l'ouverture de session : ./install-daemon.sh depuis ton Terminal.",
        "system.background": "Everest travaille en arrière-plan, depuis la barre de menus",
        "system.daemonSubtitle": "Exécute les actions de D1–D4 et pousse les valeurs vers la molette",
        "system.daemonTitle": "Daemon des touches",
        "system.keepRunning": "Garder Everest actif quand je ferme la fenêtre",
        "system.keepRunningNote": "Les touches D1–D4, les profils et les effets continuent de fonctionner ; l'icône reste dans la barre de menus. Quitter : menu de l'icône ou ⌘Q.",
        "system.keyboardCard": "Clavier",
        "system.keyboardCardNote": "État remonté par le firmware",
        "system.launchAtLogin": "Lancer Everest à l'ouverture de session",
        "system.launchAtLoginNote": "Démarre discrètement dans la barre de menus, sans ouvrir la fenêtre.",
        "system.launchedFrom": "Everest est lancé depuis %1$@. Pour un démarrage fiable, copie-le dans /Applications (./make-app.sh --install) : un volume externe n'est pas toujours monté à l'ouverture de session.",
        "system.lightProfile": "Profil lumière",
        "system.listening": "En écoute",
        "system.metricsEvery": "Le daemon envoie les valeurs toutes les 0,5 s pendant qu'il tourne.",
        "system.modules": "Modules",
        "system.monitoring": "Monitoring",
        "system.monitoringNote": "Valeurs système affichées sur la molette",
        "system.noAccessibility": "Everest n'a pas l'autorisation Accessibilité",
        "system.noAccessibilityNote": "Sans elle, les actions « raccourci » et « texte » ne font rien (les actions app, commande et lien fonctionnent). Si Everest est déjà coché dans la liste, l'entrée est périmée : sélectionne-la, retire-la avec « − », puis ajoute-la de nouveau avec « + » (Everest.app), et redémarre le daemon.",
        "system.openSettings": "Ouvrir les réglages",
        "system.sendMetrics": "Envoyer CPU, GPU, RAM, disque, réseau et volume",
        "system.stoppedState": "Arrêté",
        "system.unlock": "Débloquer le clavier",
        "system.unlockNote": "« Débloquer » envoie la réinitialisation du SDK si un transfert d'image a été interrompu. Si ça ne suffit pas, débranche et rebranche le clavier : rien n'est perdu.",

        // MARK: upload
        "upload.phase.connect": "Connexion au clavier",
        "upload.phase.done": "Terminé",
        "upload.phase.finish": "Finalisation",
        "upload.phase.prepare": "Le clavier prépare l'emplacement",
        "upload.phase.send": "Envoi de l'image",

        "status.configReloaded": "Les réglages ont été modifiés en dehors de l'app et ont été rechargés.",

        // MARK: pad
        "action.profile": "Profil",
        "profileAction.next": "Profil suivant",
        "profileAction.previous": "Profil précédent",
        "profiles.newCopyPad": "Nouveau, avec les touches DisplayPad de « %1$@ »",
        "pad.status.swapped": "%1$@ et %2$@ échangées.",
        "keyappearance.live": "En direct",
        "keyappearance.liveAction": "Ouvrir aussi l'app correspondante",
        "keyappearance.liveNote": "Redessiné dès que la valeur change (au plus une fois par seconde) tant que le pad est branché. La touche garde son action.",
        "pad.keysActive": "Touches P1–P12 actives",
        "pad.overview.keys": "%1$@ touches sur 12 configurées",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "Le firmware %1$@ du DisplayPad n'est pas pris en charge",
        "pad.unsupportedNote": "Everest n'écrit que sur le firmware 8, la version testée, et laisse ce pad tranquille.",
        "pad.noAnswer": "Le DisplayPad ne répond pas",
        "pad.noAnswerNote": "Il est branché mais ne répond pas : attendez quelques secondes, ou branchez-le directement sur le Mac.",
        "section.displaypad.subtitle": "Douze touches-écrans, chacune avec une image et une action macOS",
        "pad.connected": "DisplayPad connecté",
        "pad.connectedNote": "Les images sont envoyées moins d'une seconde après chaque changement ; le pad les garde jusqu'à ce qu'on le débranche.",
        "pad.notConnected": "DisplayPad non connecté",
        "pad.notConnectedNote": "Branchez-le directement sur le Mac : sur certains hubs USB, son écran reste noir.",
        "pad.brightness": "Luminosité",
        "pad.keys": "Touches",
        "pad.keysNote": "Cliquez sur une touche pour la modifier, ou glissez-la sur une autre pour les échanger. Images et actions sont enregistrées dans le profil « %1$@ ».",
        "pad.clearKey": "Effacer",
        "pad.clearKeyHelp": "Retire l'image et l'action de %1$@",
        "pad.noImage": "Aucune image",
        "pad.ownImageNote": "Elle est recadrée au centre et redimensionnée en 102 × 102. L'action de la touche ne change pas.",
        "pad.daemonStoppedNote": "Les touches du DisplayPad ne fonctionnent que lorsqu'il tourne.",
        "pad.status.sent": "%1$@ : envoyé au DisplayPad.",
        "pad.status.savedOffline": "%1$@ : enregistré — affiché quand le DisplayPad sera branché.",
        "pad.status.failed": "DisplayPad : %1$@",
    ]
}
