// Interface strings — fi. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let fi: [String: String] = [
        // MARK: action
        "action.app": "Sovellus",
        "action.keypress": "Pikanäppäin",
        "action.none": "Ei mitään",
        "action.open": "Tiedosto",
        "action.shell": "Komento",
        "action.text": "Teksti",
        "action.textToType": "Kirjoitettava teksti",
        "action.url": "Linkki",

        // MARK: app
        "app.closeWindow": "Sulje ikkuna",
        "app.copy": "Kopioi",
        "app.cut": "Leikkaa",
        "app.edit": "Muokkaa",
        "app.hide": "Piilota Everest",
        "app.paste": "Liitä",
        "app.quit": "Lopeta Everest",
        "app.selectAll": "Valitse kaikki",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "macOS-toiminnot ja kirjoitetut pikanäppäimet vaativat Käytön apu -oikeuden (Asetukset → Tietosuoja ja turvallisuus).",
        "buttons.actionRan": "D%1$@:n toiminto suoritettu.",
        "buttons.appHint": "Avaa sovelluksen tai tuo sen etualalle",
        "buttons.clearLeftovers": "Tyhjennä jäljelle jääneet toiminnot",
        "buttons.daemonStopped": "Daemon on pysäytetty",
        "buttons.daemonStoppedNote": "Toiminnot suoritetaan vain, kun se kuuntelee D1–D4-näppäimiä.",
        "buttons.factoryValues": "Tehdasasetukset",
        "buttons.factoryValuesHelp": "Palauttaa D%1$@:n alkuperäisen kuvan ja toiminnon",
        "buttons.flashMemory": "Näppäimistön muisti",
        "buttons.flashMemoryNote": "Base Camp voi jättää toimintoja flash-muistiin (esim. D4 lähettää Esc)",
        "buttons.keyHeader": "NÄPPÄIN D%1$@",
        "buttons.noAction": "Ei toimintoa — näppäin ohitetaan.",
        "buttons.noApp": "Sovellusta ei valittu",
        "buttons.pickPresetAppImage": "Esiasetus, sovellus tai kuva näppäimelle D%1$@",
        "buttons.presetsAndIcon": "Esiasetukset ja kuvake…",

        // MARK: clock
        "clock.analog": "Analoginen",
        "clock.digital": "Digital",
        "clock.sync": "Synkronoi",

        // MARK: colormode
        "colormode.dual": "Kaksi väriä",
        "colormode.quad": "4 väriä",
        "colormode.rainbow": "Sateenkaari",
        "colormode.single": "Yksi väri",
        "colormode.withBackground": "Näppäin + tausta",

        // MARK: common
        "common.active": "Aktiivinen",
        "common.add": "Uusi",
        "common.choose": "Valitse…",
        "common.close": "Sulje",
        "common.configure": "Määritä",
        "common.delete": "Poista",
        "common.edit": "Muokkaa",
        "common.name": "Nimi",
        "common.other": "Muu…",
        "common.refresh": "Päivitä",
        "common.remove": "Poista",
        "common.start": "Käynnistä",
        "common.stop": "Pysäytä",
        "common.test": "Testaa",

        // MARK: daemon
        "daemon.keysActive": "D1–D4-näppäimet käytössä",
        "daemon.stopped": "Daemon pysäytetty",

        // MARK: device
        "device.blocked": "Laiteohjelmistoa ei tueta",
        "device.connected": "Yhdistetty",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Yhteys katkaistu",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Täydellinen Everest Max",
        "device.keyboardMissing": "näppäimistö ei ole käytettävissä",
        "device.keyboardUnavailable": "Näppäimistö ei ole käytettävissä (ei löytynyt tai laiteohjelmistoa ei tueta).",
        "device.notConnected": "Ei yhdistetty",
        "device.refresh.help": "Päivitä näppäimistön tila",
        "device.withDock": "Näppäimistö + mediatelakka",
        "device.withNumpad": "Näppäimistö + numeronäppäimistö",

        // MARK: displays
        "displays.change": "Vaihda…",
        "displays.chooseImage": "Valitse kuva…",
        "displays.dial.subtitle": "Pyöreä 240 × 204 -näyttö mediatelakassa",
        "displays.display": "Näyttö",
        "displays.factoryIcon": "Tehdaskuvake",
        "displays.factoryLogo": "Tehdaslogo",
        "displays.imageCropped": "Kuva rajataan kokoon 240 × 204.",
        "displays.imagesResized": "Kuvat skaalataan kokoon 72 × 72.",
        "displays.keys.subtitle": "Neljä 72 × 72 -näyttöä numeronäppäimistön yläpuolella",
        "displays.keys.title": "Näyttönäppäimet",
        "displays.logoRestored": "Mountain-logo palautettu valitsimeen.",
        "displays.metricsNote": "CPU, GPU, RAM, levy, verkko ja äänenvoimakkuus näyttävät daemonin lähettämät arvot (Järjestelmä-sivu).",

        // MARK: factory
        "factory.activityMonitor": "Toimintamonitori",
        "factory.sleep": "Lepotila",

        // MARK: firmware
        "firmware.block.body": "Everest on testattu vain laiteohjelmistolla %1$@. Jotta näppäimistö ei missään tapauksessa muuttuisi käyttökelvottomaksi, se ei lähetä sille mitään ennen kuin versio on tämä: ei valaistusta, ei kuvia, ei toimintoja.",
        "firmware.block.check": "Tarkista uudelleen",
        "firmware.block.detected": "Havaittu laiteohjelmisto: %1$@",
        "firmware.block.how": "Mountain tarjoaa laiteohjelmistopäivityksen vain virallisessa Windows-sovelluksessaan Base Camp. Liitä näppäimistö Windows-tietokoneeseen, asenna Base Camp, päivitä laiteohjelmisto ja liitä näppäimistö sitten takaisin tähän Maciin: Everest havaitsee sen itse.",
        "firmware.block.howTitle": "Näppäimistön päivittäminen",
        "firmware.block.tested": "Testattu laiteohjelmisto: %1$@",
        "firmware.block.title": "Laiteohjelmistoa ei tueta",
        "firmware.block.unreadableBody": "Everest ei pysty tarkistamaan näppäimistön laiteohjelmistoversiota, joten se ei koske näppäimistöön. Irrota ja liitä näppäimistö uudelleen ja yritä sitten uudelleen.",
        "firmware.block.unreadableTitle": "Laiteohjelmistoa ei voi lukea",
        "firmware.block.why": "Everest ei päivitä laiteohjelmistoa itse: se on samanlainen toimenpide, joka voi tehdä näppäimistöstä käyttökelvottoman, eikä sitä voi testata tässä.",
        "firmware.status.unreadable": "Näppäimistö ei ilmoittanut laiteohjelmistoaan — sitä ei muuteta.",
        "firmware.status.unsupported": "Laiteohjelmistoa %1$@ ei tueta (testattu: %2$@) — näppäimistöä ei muuteta.",

        // MARK: fx
        "fx.breathing": "Hengitys",
        "fx.breathing.desc": "Pehmeä sykintä",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Putoavat pisarat",
        "fx.off": "Pois",
        "fx.off.desc": "Kaikki on sammutettu",
        "fx.reactive": "Reagoiva",
        "fx.reactive.desc": "Syttyy kirjoittaessa",
        "fx.static": "Staattinen",
        "fx.static.desc": "Kiinteä väri",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Pyörii keskipisteen ympäri",
        "fx.wave": "Aalto",
        "fx.wave.desc": "Pyyhkäisee näppäimistön yli",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Aaltoilu näppäimestä",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Käytä myös esiasetuksen toimintoa",
        "keyappearance.appHint": "Näppäin avaa sovelluksen tai tuo sen etualalle, jos se on jo auki.",
        "keyappearance.apps": "Sovellukset",
        "keyappearance.background": "Jatka taustalla",
        "keyappearance.busyOther": "Siirto on käynnissä näppäimellä D%1$@ — odota sen päättymistä ennen kuin muutat tätä näppäintä.",
        "keyappearance.chooseFile": "Valitse tiedosto…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Avaa sovelluksen",
        "keyappearance.ownImage": "Oma kuvasi",
        "keyappearance.ownImageNote": "Se rajataan keskeltä ja skaalataan kokoon 72 × 72. Näppäimen toiminto ei muutu.",
        "keyappearance.presets": "Esiasetukset",
        "keyappearance.searchApp": "Hae sovellusta",
        "keyappearance.step.prepare": "Valmistelu",
        "keyappearance.step.send": "Lähetys",
        "keyappearance.subtitle": "Valitse, mitä näyttö näyttää ja mitä näppäin tekee",
        "keyappearance.title": "Näppäin D%1$@",
        "keyappearance.transferNote": "Siirto kestää noin 20 sekuntia: näppäimistö valmistelee paikan (se poistaa vanhan kuvan itse) ja vastaanottaa sitten uuden 64 tavun paketeissa. Älä irrota näppäimistöä.",

        // MARK: keyboard
        "keyboard.activeBadge": "KÄYTÖSSÄ",
        "keyboard.ansiShape": "ANSI-muoto: leveä Enter, \\ ylimmän rivin lopussa",
        "keyboard.asPrinted": "painetun mukaan",
        "keyboard.automatic": "Automaattinen",
        "keyboard.chosen": "VALITTU KÄSIN",
        "keyboard.clearRemaps": "Tyhjennä uudelleenmäärittelyt",
        "keyboard.detected": "HAVAITTU",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. Kestää uudelleenkäynnistykseen asti. Näppäimistöön tallennettu uudelleenmäärittely: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "ISO-näppäin",
        "keyboard.isoMuteNote": "Jos macOS käsittelee näppäimistöä ANSI-näppäimistönä, Z:n vasemmalla puolella oleva näppäin ei tee mitään",
        "keyboard.isoMuteTitle": "Eikö ISO-näppäin reagoi?",
        "keyboard.isoShape": "ISO-muoto: korkea Enter, ylimääräinen näppäin Z:n vasemmalla puolella",
        "keyboard.legend.at": "@ näppäimellä '",
        "keyboard.legend.backslash": "\\ | Z:n vasemmalla puolella",
        "keyboard.legend.quote": "\" näppäimellä ⇧2",
        "keyboard.legend.rightOfSemicolon": ";:n oikealla puolella",
        "keyboard.macLayout": "macOS-näppäinasettelu",
        "keyboard.macLayoutNote": "Jotta macOS kirjoittaa sen, mikä näppäimiin on painettu",
        "keyboard.noMacLayout": "Kohtaa “%1$@” vastaavaa macOS-asettelua ei ole asennettu: lisää se kohdassa Järjestelmäasetukset → Näppäimistö → Syöttölähteet.",
        "keyboard.remapApplied": "ISO-uudelleenmäärittely otettu käyttöön (uudelleenkäynnistykseen asti).",
        "keyboard.remapIso": "Määritä ISO-näppäin uudelleen",
        "keyboard.remapsCleared": "hidutil-uudelleenmäärittelyt tyhjennetty.",
        "keyboard.reportsLayout": "Näppäimistö ilmoittaa asetteluksi “%1$@”. Palaa automaattiseen, jos tätä valintaa ei enää tarvita.",
        "keyboard.switchedTo": "Asetteluksi vaihdettu %1$@.",
        "keyboard.title": "Fyysinen näppäimistö",
        "keyboard.titleNote": "Luetaan näppäimistöltä kuten Base Campissa: piirros, näppäimet ja tehosteet mukautuvat siihen",
        "keyboard.unknown": "tuntematon",
        "keyboard.use": "Käytä %1$@",
        "keyboard.verifiedNote1": "Kunkin näppäimen muoto ja valaistus seuraavat näppäimistön ruudukkoa; vain UK-asettelu on varmistettu oikealla näppäimistöllä.",
        "keyboard.verifiedNote2": "Kirjaimet tulevat Base Campin tauluista ja muoto seuraa LED-ruudukkoa; vain UK-asettelu on varmistettu oikealla näppäimistöllä.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "valitsimen siirto keskeytyi — käytä toimintoa “Vapauta näppäimistö” (Järjestelmä-sivu) tai liitä se uudelleen",
        "keyboardError.dialRefused": "valitsin hylkäsi siirron (mitään ei kirjoitettu)",
        "keyboardError.interrupted": "siirto keskeytyi — käytä toimintoa “Vapauta näppäimistö” (Järjestelmä-sivu) tai liitä se uudelleen",
        "keyboardError.refused": "näppäimistö hylkäsi siirron (mitään ei kirjoitettu) — yritä uudelleen; jos ongelma jatkuu, käytä toimintoa “Vapauta näppäimistö” (Järjestelmä-sivu)",
        "keyboardError.selectTarget": "näppäimistö ei vastaa näppäinvalintaan — käytä toimintoa “Vapauta näppäimistö” (Järjestelmä-sivu) tai liitä se uudelleen",

        // MARK: layout
        "layout.french": "Ranska (AZERTY)",
        "layout.german": "Saksa (QWERTZ)",
        "layout.hebrew": "Heprea",
        "layout.italian": "Italia",
        "layout.korean": "Korea",
        "layout.nordic": "Pohjoismainen",
        "layout.portuguese": "Portugali",
        "layout.spanish": "Espanja",
        "layout.uk": "Iso-Britannia (ISO)",
        "layout.us": "USA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Lisää väri",
        "lighting.allHues": "Kaikki sävyt, näppäimistön tuottamat.",
        "lighting.backgroundColour": "Tausta",
        "lighting.brightness": "Kirkkaus",
        "lighting.byKeyboard": "Näppäimistön suorittama — jatkuu ilman sovellusta",
        "lighting.byMac": "Macin laskema — pidä sovellus auki",
        "lighting.clearAll": "Tyhjennä kaikki",
        "lighting.clockwise": "Myötäpäivään",
        "lighting.colors": "Värit",
        "lighting.colour": "Väri",
        "lighting.colour1": "Väri 1",
        "lighting.colour2": "Väri 2",
        "lighting.colourCount.one": "%1$@ väri",
        "lighting.colourCount.other": "%1$@ väriä",
        "lighting.counterclockwise": "Vastapäivään",
        "lighting.direction": "Suunta",
        "lighting.editEllipsis": "Muokkaa…",
        "lighting.fast": "Nopea",
        "lighting.flameNote": "Kiinteä liekkiasteikko hiilloksesta valkoiseen.",
        "lighting.freeze": "Lukitse näppäimistöön",
        "lighting.freezeNote": "Lähettää nykyisen ruudun Custom-paikkaan ja tallentaa sen: se säilyy ilman sovellusta.",
        "lighting.keyColour": "Näppäin",
        "lighting.ledsBlack": "Kaikki LEDit ovat mustia tehosteen ollessa käynnissä.",
        "lighting.macNote": "Laskettu näppäin kerrallaan 30 ruutua/s, omalla paletillasi",
        "lighting.normal": "Normal",
        "lighting.offNote": "Taustavalo ja sivuvalot on sammutettu. Valitse toinen tehoste sytyttääksesi ne uudelleen.",
        "lighting.officialEffects": "Viralliset tehosteet",
        "lighting.officialNote": "Base Campin tehosteet lähetettynä täsmälleen kuten Windows-sovellus",
        "lighting.paintHint": "Napsauta tai vedä yllä olevan näppäimistön näppäinten päällä.",
        "lighting.paintKeys": "Maalaa näppäin kerrallaan",
        "lighting.palette": "Palette",
        "lighting.paused": "Tauolla",
        "lighting.reapply": "Käytä uudelleen",
        "lighting.rightClickHint": "Poista värinäyte napsauttamalla sitä hiiren kakkospainikkeella.",
        "lighting.rotation": "Pyörimissuunta",
        "lighting.runningOnKeyboard": "Käynnissä näppäimistöllä",
        "lighting.savedInProfile": "Tallennettu näppäimistön aktiiviseen profiiliin",
        "lighting.slow": "Hidas",
        "lighting.speed": "Nopeus",
        "lighting.title": "Valaistus",

        // MARK: live
        "live.keyboard": "Näppäimistö · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · tauolla",
        "live.pause": "Tauko",
        "live.start": "Käynnistä",

        // MARK: macfx
        "macfx.aurora": "Revontulet",
        "macfx.equalizer": "Taajuuskorjain",
        "macfx.fire": "Tuli",
        "macfx.gradient": "Liukuväri",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Digitaalinen sade",
        "macfx.ripples": "Väreet",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Yksivärinen",
        "macfx.spectrum": "Spektri",
        "macfx.spiral": "Spiraali",
        "macfx.stars": "Tähdet",
        "macfx.waves": "Aallot",

        // MARK: menu
        "menu.allowAccessibility": "Salli Käytön apu…",
        "menu.disconnected": "Näppäimistö irrotettu",
        "menu.firmwareBlocked": "Laiteohjelmistoa ei tueta — näppäimistöä ei käytetä",
        "menu.keyboardEffects": "Näppäimistön tehosteet",
        "menu.launchAtLogin": "Käynnistä kirjautuessa",
        "menu.macEffects": "Macin tehosteet",
        "menu.manageProfiles": "Hallitse profiileja…",
        "menu.newProfile": "Uusi profiili",
        "menu.open": "Avaa Everest…",
        "menu.pauseEffect": "Keskeytä tehoste",
        "menu.profile": "Profiili: %1$@",
        "menu.resumeEffect": "Jatka tehostetta",

        // MARK: metric
        "metric.disk": "LEVY",
        "metric.network": "VERKKO",
        "metric.volume": "ÄÄNENVOIMAKKUUS",

        // MARK: mode
        "mode.clock": "Kello",
        "mode.disk": "Levy",
        "mode.image": "Kuva",
        "mode.network": "Verkko",
        "mode.volume": "Äänenvoimakkuus",

        // MARK: overview
        "overview.actionsActive": "Toiminnot käytössä",
        "overview.changeLighting": "Vaihda valaistus",
        "overview.dialSubtitle": "Mediatelakan pyöreä näyttö",
        "overview.keyboardEffect": "Näppäimistön tehoste",
        "overview.macEffect": "Macin laskema tehoste",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Hiillos",
        "palette.forest": "Metsä",
        "palette.ice": "Jää",
        "palette.neon": "Neon",
        "palette.ocean": "Valtameri",
        "palette.sunset": "Auringonlasku",
        "palette.vapor": "Höyry",

        // MARK: preset
        "preset.bolt": "Salama",
        "preset.calendar": "Kalenteri",
        "preset.captureScreen": "Kuvakaappaus",
        "preset.captureZone": "Alueen kaappaus",
        "preset.category.apps": "Sovellukset",
        "preset.category.decor": "Vain kuvake",
        "preset.category.media": "Media",
        "preset.coffee": "Kahvi",
        "preset.flame": "Liekki",
        "preset.game": "Ohjain",
        "preset.heart": "Sydän",
        "preset.home": "Koti",
        "preset.lock": "Lukitse",
        "preset.music": "Musiikki",
        "preset.mute": "Mykistä",
        "preset.next": "Seuraava",
        "preset.playpause": "Toista / Tauko",
        "preset.previous": "Edellinen",
        "preset.sleepDisplay": "Sammuta näyttö",
        "preset.star": "Tähti",
        "preset.volumeDown": "Äänenvoimakkuus −",
        "preset.volumeUp": "Äänenvoimakkuus +",

        // MARK: profile
        "profile.defaultName": "Profiili %1$@",
        "profile.main": "Pää",

        // MARK: profiles
        "profiles.addApp": "Lisää sovellus (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Automaattinen vaihto",
        "profiles.autoSwitchHint": "Toimii, kun sovellus on auki tai daemon on käynnissä. Valitsimella käsin valittua profiilia ei korvata, kun pysyt sovelluksessa, jolla ei ole profiilia.",
        "profiles.autoSwitchNote": "Näppäimistö vaihtaa sovelluksen profiiliin, kun sovellus on etualalla",
        "profiles.deleteHelp": "Poista tämä profiili sovelluksesta",
        "profiles.dialMode": "Valitsin: %1$@",
        "profiles.dialOnActivate": "Valitsin aktivoitaessa",
        "profiles.dialUnchanged": "Valitsin ennallaan",
        "profiles.dontChange": "Älä muuta",
        "profiles.enable": "Ota käyttöön",
        "profiles.freeSlots": "%1$@ vapaata paikkaa",
        "profiles.hardwareNote": "Näppäimistö säilyttää viittä profiilia muistissa (valitsimen Profile-valikko). Jokaisella on oma valaistuksensa, omat uudelleenmäärittelynsä ja omat D1–D4-kuvansa; sovellus lisää näppäintoiminnot, valitsimen tilan ja linkitetyt sovellukset.",
        "profiles.header": "PROFIILI %1$@",
        "profiles.iconAndColour": "Kuvake ja väri",
        "profiles.keyboardLighting": "Näppäimistön valaistus",
        "profiles.keyboardProfiles": "NÄPPÄIMISTÖN PROFIILIT",
        "profiles.keysNote": "D1–D4-näppäimet ja valaistus asetetaan omilla sivuillaan, kun tämä profiili on aktiivinen: ne tallennetaan tähän profiiliin.",
        "profiles.lightingFirmware": "Valaistus: %1$@",
        "profiles.lightingMac": "Macin valaistus: %1$@",
        "profiles.linkedApps": "Linkitetyt sovellukset",
        "profiles.manage": "Hallitse…",
        "profiles.namePlaceholder": "Koodaus, Musiikki…",
        "profiles.noLinkedApp": "Ei linkitettyä sovellusta",
        "profiles.otherwise": "Muuten palaa profiiliin",
        "profiles.slot": "Paikka %1$@",
        "profiles.slotOfKeyboard": "Näppäimistön paikka %1$@",

        // MARK: reset
        "reset.title": "Palauta",

        // MARK: section
        "section.buttons.subtitle": "macOS-toiminto kullekin neljästä näyttönäppäimestä",
        "section.buttons.title": "D1–D4-näppäimet",
        "section.displays.subtitle": "Valitsimen pyöreä näyttö ja numeronäppäimistön näyttönäppäimet",
        "section.displays.title": "Näytöt",
        "section.keyboard.subtitle": "Havaittu näppäimistöasettelu ja vastaava macOS-asettelu",
        "section.keyboard.title": "Asettelu",
        "section.lighting.subtitle": "Viralliset näppäimistön tehosteet ja Macin laskemat dynaamiset tehosteet",
        "section.overview.subtitle": "Everest Maxisi yhdellä silmäyksellä",
        "section.overview.title": "Yleiskatsaus",
        "section.profiles.subtitle": "Viisi näppäimistöön tallennettua profiilia, joilla kullakin on omat näppäimensä, valaistuksensa ja sovelluksensa",
        "section.profiles.title": "Profiilit",
        "section.system.subtitle": "Näppäindaemon, valvonta ja vianmääritys",
        "section.system.title": "Järjestelmä",

        // MARK: settings
        "settings.language.automatic": "Automaattinen (järjestelmän kieli)",
        "settings.language.note": "Käyttöliittymän, valikkopalkin valikon ja ilmoitusten kieli.",
        "settings.language.title": "Kieli",

        // MARK: status
        "status.animationPaused": "Animaatio tauolla — näppäimistö säilyttää viimeisen ruudun.",
        "status.appIconUnreadable": "Sovelluksen kuvaketta ei voitu lukea.",
        "status.appNoId": "Tällä sovelluksella ei ole tunnistetta: sitä ei voi linkittää.",
        "status.changeFailed": "Muutos ei onnistunut: %1$@",
        "status.cleaning": "Siivotaan",
        "status.clockSynced": "Kello synkronoitu Macin kanssa.",
        "status.configSaved": "Asetukset tallennettu.",
        "status.daemonOff": "D1–D4-näppäimet pois käytöstä.",
        "status.daemonOn": "D1–D4-näppäimet käytössä.",
        "status.daemonStartFailed": "Daemonia ei voitu käynnistää: %1$@",
        "status.dialImageSent": "Kuva lähetetty valitsimeen.",
        "status.dialMode": "Valitsin: %1$@.",
        "status.displayLabel": "Näyttö",
        "status.effectApplied": "%1$@ otettu käyttöön ja tallennettu profiiliin.",
        "status.effectRunningKeyboard": "Tehoste “%1$@” on käynnissä näppäimistöllä.",
        "status.factoryIconRestored": "Tehdaskuvake palautettu näppäimelle D%1$@.",
        "status.frozen": "Ruutu lukittu ja tallennettu näppäimistön “Custom”-paikkaan.",
        "status.iconDrawFailed": "Kuvaketta ei voitu piirtää.",
        "status.iconSent": "Kuvake lähetetty näppäimelle D%1$@ ajassa %2$@ s.",
        "status.keyboardConnected": "Näppäimistö yhdistetty.",
        "status.keyboardGone": "Näppäimistö irrotettu — tehoste jatkuu, kun se liitetään takaisin.",
        "status.layoutAuto": "Asettelu: automaattinen tunnistus.",
        "status.layoutForced": "Asettelu pakotettu: %1$@.",
        "status.leftoversCleared": "Jäljelle jääneet toiminnot poistettu näppäimistön muistista.",
        "status.loginApproval": "Hyväksyttävä kohdassa Järjestelmäasetukset → Yleiset → Kirjautumiskohteet.",
        "status.previewOnly": "Näppäimistöä ei löytynyt — esikatselu on edelleen käytettävissä.",
        "status.profileActivated": "Profiili “%1$@” aktivoitu.",
        "status.profileActivatedFrontApp": "Profiili “%1$@” aktivoitu (sovellus etualalla).",
        "status.profileFromKeyboard": "Profiili “%1$@” aktiivinen (valittu näppäimistöltä).",
        "status.profileRemoved": "Profiili poistettu sovelluksesta (näppäimistö säilyttää asetuksensa paikassa %1$@).",
        "status.ready": "Valmis",
        "status.recovering": "Palautus",
        "status.recoverySent": "Palautusjakso lähetetty.",
        "status.saving": "Tallennetaan",
        "status.sendingImage": "Lähetetään kuvaa…",
        "status.uploadBusy": "Siirto on käynnissä näppäimellä D%1$@ — odota muutama sekunti.",
        "status.uploadBusyAlready": "Siirto on jo käynnissä näppäimellä D%1$@ — odota muutama sekunti.",
        "status.uploadFailed": "Siirto epäonnistui: %1$@",
        "status.uploadFailedKey": "D%1$@: siirto epäonnistui — %2$@",
        "status.uploadStarted": "D%1$@: lähetetään kuvaa näppäimistöön…",

        // MARK: system
        "system.askAgain": "Kysy uudelleen",
        "system.autoDaemon": "Ota D1–D4-näppäimet käyttöön automaattisesti",
        "system.autoDaemonNote": "Daemon käynnistyy sovelluksen mukana, yhdistyy itse uudelleen, kun näppäimistö liitetään takaisin, ja käynnistyy uudelleen, jos se pysähtyy.",
        "system.autostartHint": "Automaattinen käynnistys kirjautuessa: ./install-daemon.sh Terminalista.",
        "system.background": "Everest toimii taustalla valikkopalkista käsin",
        "system.daemonSubtitle": "Suorittaa D1–D4-toiminnot ja lähettää arvoja valitsimeen",
        "system.daemonTitle": "Näppäindaemon",
        "system.keepRunning": "Pidä Everest käynnissä, kun suljen ikkunan",
        "system.keepRunningNote": "D1–D4-näppäimet, profiilit ja tehosteet toimivat edelleen; kuvake pysyy valikkopalkissa. Lopetus: kuvakkeen valikko tai ⌘Q.",
        "system.keyboardCard": "Näppäimistö",
        "system.keyboardCardNote": "Laiteohjelmiston ilmoittama tila",
        "system.launchAtLogin": "Käynnistä Everest kirjautuessa",
        "system.launchAtLoginNote": "Käynnistyy huomaamattomasti valikkopalkkiin avaamatta ikkunaa.",
        "system.launchedFrom": "Everest on käynnissä sijainnista %1$@. Luotettavaa käynnistystä varten kopioi se kansioon /Applications (./make-app.sh --install): ulkoista levyä ei aina ole liitetty kirjautuessa.",
        "system.lightProfile": "Valoprofiili",
        "system.listening": "Kuuntelee",
        "system.metricsEvery": "Daemon lähettää arvot 0,5 s välein käynnissä ollessaan.",
        "system.modules": "Moduulit",
        "system.monitoring": "Valvonta",
        "system.monitoringNote": "Valitsimessa näytettävät järjestelmäarvot",
        "system.noAccessibility": "Everestillä ei ole Käytön apu -oikeutta",
        "system.noAccessibilityNote": "Ilman sitä “pikanäppäin”- ja “teksti”-toiminnot eivät tee mitään (sovellus-, komento- ja linkkitoiminnot toimivat). Jos Everest on jo rastitettu luettelossa, merkintä on vanhentunut: valitse se, poista se painikkeella “−”, lisää se uudelleen painikkeella “+” (Everest.app) ja käynnistä daemon uudelleen.",
        "system.openSettings": "Avaa asetukset",
        "system.sendMetrics": "Lähetä CPU, GPU, RAM, levy, verkko ja äänenvoimakkuus",
        "system.stoppedState": "Pysäytetty",
        "system.unlock": "Vapauta näppäimistö",
        "system.unlockNote": "“Vapauta” lähettää SDK-nollauksen, jos kuvansiirto keskeytyi. Jos se ei riitä, irrota ja liitä näppäimistö uudelleen: mitään ei menetetä.",

        // MARK: upload
        "upload.phase.connect": "Yhdistetään näppäimistöön",
        "upload.phase.done": "Valmis",
        "upload.phase.finish": "Viimeistellään",
        "upload.phase.prepare": "Näppäimistö valmistelee paikkaa",
        "upload.phase.send": "Lähetetään kuvaa",
    ]
}
