// Interface strings — it. Keys missing here were left as in English on purpose (names, symbols).
// Placeholders are positional (%1$@, %2$@…) so translations can reorder them.

extension L10n {
    static let it: [String: String] = [
        // MARK: action
        "action.app": "App",
        "action.keypress": "Scorciatoia",
        "action.none": "Nessuna",
        "action.open": "File",
        "action.shell": "Comando",
        "action.text": "Testo",
        "action.textToType": "Testo da digitare",
        "action.url": "Link",

        // MARK: app
        "app.closeWindow": "Chiudi finestra",
        "app.copy": "Copia",
        "app.cut": "Taglia",
        "app.edit": "Modifica",
        "app.hide": "Nascondi Everest",
        "app.paste": "Incolla",
        "app.quit": "Esci da Everest",
        "app.selectAll": "Seleziona tutto",
        "app.tagline": "Max · macOS",

        // MARK: buttons
        "buttons.accessibilityNote": "Le azioni di macOS e le scorciatoie digitate richiedono il permesso Accessibilità (Impostazioni → Privacy e sicurezza).",
        "buttons.actionRan": "Azione di %1$@ eseguita.",
        "buttons.appHint": "Apre l'app o la porta in primo piano",
        "buttons.clearLeftovers": "Cancella le azioni residue",
        "buttons.daemonStopped": "Il daemon è fermo",
        "buttons.daemonStoppedNote": "Le azioni vengono eseguite solo mentre ascolta i tasti D1–D4.",
        "buttons.factoryValues": "Impostazioni di fabbrica",
        "buttons.factoryValuesHelp": "Ripristina l'immagine e l'azione originali di %1$@",
        "buttons.flashMemory": "Memoria della tastiera",
        "buttons.flashMemoryNote": "Base Camp può lasciare azioni nella memoria flash (es. D4 che invia Esc)",
        "buttons.keyHeader": "TASTO %1$@",
        "buttons.noAction": "Nessuna azione — il tasto viene ignorato.",
        "buttons.noApp": "Nessuna app scelta",
        "buttons.pickPresetAppImage": "Preset, app o immagine per %1$@",
        "buttons.presetsAndIcon": "Preset e icona…",

        // MARK: clock
        "clock.analog": "Analogico",
        "clock.digital": "Digital",
        "clock.sync": "Sincronizza",

        // MARK: colormode
        "colormode.dual": "Due colori",
        "colormode.quad": "4 colori",
        "colormode.rainbow": "Arcobaleno",
        "colormode.single": "Un colore",
        "colormode.withBackground": "Tasto + sfondo",

        // MARK: common
        "common.active": "Attivo",
        "common.add": "Nuovo",
        "common.choose": "Scegli…",
        "common.close": "Chiudi",
        "common.configure": "Configura",
        "common.delete": "Elimina",
        "common.edit": "Modifica",
        "common.name": "Nome",
        "common.other": "Altro…",
        "common.refresh": "Aggiorna",
        "common.remove": "Rimuovi",
        "common.start": "Avvia",
        "common.stop": "Ferma",
        "common.test": "Prova",

        // MARK: daemon
        "daemon.keysActive": "Tasti D1–D4 attivi",
        "daemon.stopped": "Daemon fermo",

        // MARK: device
        "device.blocked": "Firmware non supportato",
        "device.connected": "Connesso",
        "device.core": "Everest Core",
        "device.dial": "Dial",
        "device.disconnected": "Disconnesso",
        "device.everestMax": "Everest Max",
        "device.firmware": "Firmware",
        "device.full": "Everest Max completo",
        "device.keyboardMissing": "tastiera non disponibile",
        "device.keyboardUnavailable": "Tastiera non disponibile (non trovata, oppure firmware non supportato).",
        "device.notConnected": "Non connesso",
        "device.refresh.help": "Aggiorna lo stato della tastiera",
        "device.withDock": "Tastiera + dock multimediale",
        "device.withNumpad": "Tastiera + tastierino numerico",

        // MARK: displays
        "displays.change": "Cambia…",
        "displays.chooseImage": "Scegli un'immagine…",
        "displays.dial.subtitle": "Schermo rotondo 240 × 204 del dock multimediale",
        "displays.display": "Visualizzazione",
        "displays.factoryIcon": "Icona di fabbrica",
        "displays.factoryLogo": "Logo di fabbrica",
        "displays.imageCropped": "L'immagine viene ritagliata a 240 × 204.",
        "displays.imagesResized": "Le immagini vengono ridimensionate a 72 × 72.",
        "displays.keys.subtitle": "Quattro schermi 72 × 72 sopra il tastierino numerico",
        "displays.keys.title": "Tasti con schermo",
        "displays.logoRestored": "Logo Mountain ripristinato sul dial.",
        "displays.metricsNote": "CPU, GPU, RAM, disco, rete e volume mostrano i valori inviati dal daemon (pagina Sistema).",

        // MARK: factory
        "factory.activityMonitor": "Monitoraggio Attività",
        "factory.sleep": "Stop",

        // MARK: firmware
        "firmware.block.body": "Everest è stato testato solo con il firmware %1$@. Per evitare qualsiasi rischio di rendere inutilizzabile la tastiera, non le invia nulla finché non ha quella versione: niente illuminazione, niente immagini, niente azioni.",
        "firmware.block.check": "Controlla di nuovo",
        "firmware.block.detected": "Firmware rilevato: %1$@",
        "firmware.block.how": "Mountain offre l'aggiornamento del firmware solo nella sua applicazione ufficiale Base Camp per Windows. Collega la tastiera a un PC Windows, installa Base Camp, aggiorna il firmware, poi ricollega la tastiera a questo Mac: Everest la rileva da solo.",
        "firmware.block.howTitle": "Come aggiornare la tastiera",
        "firmware.block.tested": "Firmware testato: %1$@",
        "firmware.block.title": "Firmware non supportato",
        "firmware.block.unreadableBody": "Everest non riesce a verificare la versione del firmware della tastiera, quindi non la tocca. Scollega e ricollega la tastiera, poi riprova.",
        "firmware.block.unreadableTitle": "Firmware illeggibile",
        "firmware.block.why": "Everest non aggiorna il firmware da solo: è lo stesso tipo di operazione che può rendere inutilizzabile una tastiera e qui non può essere testata.",
        "firmware.status.unreadable": "La tastiera non ha comunicato il proprio firmware — non viene modificata.",
        "firmware.status.unsupported": "Il firmware %1$@ non è supportato (testato: %2$@) — la tastiera non viene modificata.",

        // MARK: fx
        "fx.breathing": "Respiro",
        "fx.breathing.desc": "Pulsazione dolce",
        "fx.matrix": "Matrix",
        "fx.matrix.desc": "Gocce che cadono",
        "fx.off": "Spento",
        "fx.off.desc": "Tutto spento",
        "fx.reactive": "Reattivo",
        "fx.reactive.desc": "Si accende mentre digiti",
        "fx.static": "Statico",
        "fx.static.desc": "Colore fisso",
        "fx.tornado": "Tornado",
        "fx.tornado.desc": "Gira attorno al centro",
        "fx.wave": "Onda",
        "fx.wave.desc": "Attraversa la tastiera",
        "fx.yeti": "Yeti",
        "fx.yeti.desc": "Onda a partire dal tasto",

        // MARK: keyappearance
        "keyappearance.alsoAction": "Applica anche l'azione del preset",
        "keyappearance.appHint": "Il tasto apre l'app, o la porta in primo piano se è già aperta.",
        "keyappearance.apps": "App",
        "keyappearance.background": "Continua in background",
        "keyappearance.busyOther": "Un trasferimento è in corso su %1$@ — aspetta che finisca prima di modificare questo tasto.",
        "keyappearance.chooseFile": "Scegli un file…",
        "keyappearance.imageFormats": "PNG, JPEG, GIF, HEIC…",
        "keyappearance.opensApp": "Apre l'app",
        "keyappearance.ownImage": "La tua immagine",
        "keyappearance.ownImageNote": "Viene ritagliata al centro e ridimensionata a 72 × 72. L'azione del tasto non cambia.",
        "keyappearance.presets": "Preset",
        "keyappearance.searchApp": "Cerca un'app",
        "keyappearance.step.prepare": "Preparazione",
        "keyappearance.step.send": "Invio",
        "keyappearance.subtitle": "Scegli cosa mostra lo schermo e cosa fa il tasto",
        "keyappearance.title": "Tasto %1$@",
        "keyappearance.transferNote": "Un trasferimento richiede circa 20 secondi: la tastiera prepara lo slot (cancella da sola la vecchia immagine), poi riceve la nuova in pacchetti da 64 byte. Non scollegare la tastiera.",

        // MARK: keyboard
        "keyboard.activeBadge": "ATTIVO",
        "keyboard.ansiShape": "Forma ANSI: Invio largo, \\ in fondo alla riga superiore",
        "keyboard.asPrinted": "come stampato",
        "keyboard.automatic": "Automatico",
        "keyboard.chosen": "SCELTO A MANO",
        "keyboard.clearRemaps": "Cancella i remap",
        "keyboard.detected": "RILEVATO",
        "keyboard.hidutilNote": "hidutil: usage 0x64 → 0x31. Dura fino al riavvio. Per un remap memorizzato nella tastiera: everest remap-key iso backslash",
        "keyboard.isoKeyLabel": "tasto ISO",
        "keyboard.isoMuteNote": "Se macOS tratta la tastiera come ANSI, il tasto a sinistra di Z non produce nulla",
        "keyboard.isoMuteTitle": "Il tasto ISO non risponde?",
        "keyboard.isoShape": "Forma ISO: Invio alto, tasto in più a sinistra di Z",
        "keyboard.legend.at": "@ sul tasto '",
        "keyboard.legend.backslash": "\\ | a sinistra di Z",
        "keyboard.legend.quote": "\" su ⇧2",
        "keyboard.legend.rightOfSemicolon": "a destra di ;",
        "keyboard.macLayout": "Layout di macOS",
        "keyboard.macLayoutNote": "Perché macOS scriva ciò che è stampato sui tasti",
        "keyboard.noMacLayout": "Nessun layout di macOS corrispondente a «%1$@» è installato: aggiungilo in Impostazioni di Sistema → Tastiera → Sorgenti di input.",
        "keyboard.remapApplied": "Remap ISO applicato (fino al riavvio).",
        "keyboard.remapIso": "Rimappa il tasto ISO",
        "keyboard.remapsCleared": "Remap di hidutil cancellati.",
        "keyboard.reportsLayout": "La tastiera indica «%1$@». Torna ad Automatico se questa scelta non serve più.",
        "keyboard.switchedTo": "Layout cambiato in %1$@.",
        "keyboard.title": "Tastiera fisica",
        "keyboard.titleNote": "Letto dalla tastiera, come Base Camp: il disegno, i tasti e gli effetti si adattano",
        "keyboard.unknown": "sconosciuto",
        "keyboard.use": "Usa %1$@",
        "keyboard.verifiedNote1": "La forma e l'illuminazione di ogni tasto seguono la griglia della tastiera; solo il layout UK è stato verificato su una tastiera reale.",
        "keyboard.verifiedNote2": "Le legende provengono dalle tabelle di Base Camp e la forma segue la griglia dei LED; solo il layout UK è stato verificato su una tastiera reale.",

        // MARK: keyboardError
        "keyboardError.dialIncomplete": "trasferimento al dial interrotto — usa «Sblocca la tastiera» (pagina Sistema) oppure ricollegala",
        "keyboardError.dialRefused": "il dial ha rifiutato il trasferimento (non è stato scritto nulla)",
        "keyboardError.interrupted": "trasferimento interrotto — usa «Sblocca la tastiera» (pagina Sistema) oppure ricollegala",
        "keyboardError.refused": "la tastiera ha rifiutato il trasferimento (non è stato scritto nulla) — riprova; se persiste, usa «Sblocca la tastiera» (pagina Sistema)",
        "keyboardError.selectTarget": "la tastiera non risponde alla selezione dei tasti — usa «Sblocca la tastiera» (pagina Sistema) oppure ricollegala",

        // MARK: layout
        "layout.french": "Francese (AZERTY)",
        "layout.german": "Tedesco (QWERTZ)",
        "layout.hebrew": "Ebraico",
        "layout.italian": "Italiano",
        "layout.korean": "Coreano",
        "layout.nordic": "Nordico",
        "layout.portuguese": "Portoghese",
        "layout.spanish": "Spagnolo",
        "layout.uk": "Regno Unito (ISO)",
        "layout.us": "USA (ANSI)",

        // MARK: lighting
        "lighting.addColour": "Aggiungi un colore",
        "lighting.allHues": "Tutte le tinte, generate dalla tastiera.",
        "lighting.backgroundColour": "Sfondo",
        "lighting.brightness": "Luminosità",
        "lighting.byKeyboard": "Eseguito dalla tastiera — continua senza l'app",
        "lighting.byMac": "Calcolato dal Mac — tieni aperta l'app",
        "lighting.clearAll": "Cancella tutto",
        "lighting.clockwise": "Orario",
        "lighting.colors": "Colori",
        "lighting.colour": "Colore",
        "lighting.colour1": "Colore 1",
        "lighting.colour2": "Colore 2",
        "lighting.colourCount.one": "%1$@ colore",
        "lighting.colourCount.other": "%1$@ colori",
        "lighting.counterclockwise": "Antiorario",
        "lighting.direction": "Direzione",
        "lighting.editEllipsis": "Modifica…",
        "lighting.fast": "Veloce",
        "lighting.flameNote": "Rampa di fiamma fissa, dalla brace al bianco.",
        "lighting.freeze": "Fissa nella tastiera",
        "lighting.freezeNote": "Invia il fotogramma attuale allo slot Custom e lo salva: resta anche senza l'app.",
        "lighting.keyColour": "Tasto",
        "lighting.ledsBlack": "Tutti i LED restano neri mentre l'effetto è in esecuzione.",
        "lighting.macNote": "Calcolati tasto per tasto a 30 fotogrammi/s, con la tua palette",
        "lighting.normal": "Normal",
        "lighting.offNote": "La retroilluminazione e le strisce laterali sono spente. Scegli un altro effetto per riaccenderle.",
        "lighting.officialEffects": "Effetti ufficiali",
        "lighting.officialNote": "Gli effetti di Base Camp, inviati esattamente come fa l'app per Windows",
        "lighting.paintHint": "Clicca o trascina sui tasti della tastiera qui sopra.",
        "lighting.paintKeys": "Dipingi tasto per tasto",
        "lighting.palette": "Palette",
        "lighting.paused": "In pausa",
        "lighting.reapply": "Applica di nuovo",
        "lighting.rightClickHint": "Clic destro su un campione per rimuoverlo.",
        "lighting.rotation": "Senso di rotazione",
        "lighting.runningOnKeyboard": "In esecuzione sulla tastiera",
        "lighting.savedInProfile": "Salvato nel profilo attivo della tastiera",
        "lighting.slow": "Lento",
        "lighting.speed": "Velocità",
        "lighting.title": "Illuminazione",

        // MARK: live
        "live.keyboard": "Tastiera · %1$@",
        "live.mac": "Mac · %1$@",
        "live.macPaused": "Mac · in pausa",
        "live.pause": "Pausa",
        "live.start": "Avvia",

        // MARK: macfx
        "macfx.aurora": "Aurora",
        "macfx.equalizer": "Equalizer",
        "macfx.fire": "Fuoco",
        "macfx.gradient": "Sfumatura",
        "macfx.plasma": "Plasma",
        "macfx.rain": "Pioggia digitale",
        "macfx.ripples": "Increspature",
        "macfx.scanner": "Scanner",
        "macfx.solid": "Tinta unita",
        "macfx.spectrum": "Spettro",
        "macfx.spiral": "Spirale",
        "macfx.stars": "Stelle",
        "macfx.waves": "Onde",

        // MARK: menu
        "menu.allowAccessibility": "Consenti Accessibilità…",
        "menu.disconnected": "Tastiera disconnessa",
        "menu.firmwareBlocked": "Firmware non supportato — tastiera ignorata",
        "menu.keyboardEffects": "Effetti della tastiera",
        "menu.launchAtLogin": "Avvia al login",
        "menu.macEffects": "Effetti del Mac",
        "menu.manageProfiles": "Gestisci profili…",
        "menu.newProfile": "Nuovo profilo",
        "menu.open": "Apri Everest…",
        "menu.pauseEffect": "Metti in pausa l'effetto",
        "menu.profile": "Profilo: %1$@",
        "menu.resumeEffect": "Riprendi l'effetto",

        // MARK: metric
        "metric.disk": "DISCO",
        "metric.network": "RETE",
        "metric.volume": "VOLUME",

        // MARK: mode
        "mode.clock": "Orologio",
        "mode.disk": "Disco",
        "mode.image": "Immagine",
        "mode.network": "Rete",
        "mode.volume": "Volume",

        // MARK: overview
        "overview.actionsActive": "Azioni attive",
        "overview.changeLighting": "Cambia illuminazione",
        "overview.dialSubtitle": "Schermo rotondo del dock multimediale",
        "overview.keyboardEffect": "Effetto della tastiera",
        "overview.macEffect": "Effetto calcolato dal Mac",

        // MARK: palette
        "palette.cyberpunk": "Cyberpunk",
        "palette.ember": "Brace",
        "palette.forest": "Foresta",
        "palette.ice": "Ghiaccio",
        "palette.neon": "Neon",
        "palette.ocean": "Oceano",
        "palette.sunset": "Tramonto",
        "palette.vapor": "Vapore",

        // MARK: preset
        "preset.bolt": "Fulmine",
        "preset.calendar": "Calendario",
        "preset.captureScreen": "Cattura schermo",
        "preset.captureZone": "Cattura area",
        "preset.category.apps": "App",
        "preset.category.decor": "Solo icona",
        "preset.category.media": "Media",
        "preset.coffee": "Caffè",
        "preset.flame": "Fiamma",
        "preset.game": "Controller",
        "preset.heart": "Cuore",
        "preset.home": "Casa",
        "preset.lock": "Blocca",
        "preset.music": "Musica",
        "preset.mute": "Muto",
        "preset.next": "Successivo",
        "preset.playpause": "Riproduci / Pausa",
        "preset.previous": "Precedente",
        "preset.sleepDisplay": "Spegni lo schermo",
        "preset.star": "Stella",
        "preset.volumeDown": "Volume −",
        "preset.volumeUp": "Volume +",

        // MARK: profile
        "profile.defaultName": "Profilo %1$@",
        "profile.main": "Principale",

        // MARK: profiles
        "profiles.addApp": "Aggiungi un'app (Logic Pro, Xcode…)",
        "profiles.autoSwitch": "Cambio automatico",
        "profiles.autoSwitchHint": "Funziona mentre l'app è aperta o il daemon è in esecuzione. Un profilo scelto a mano sul dial non viene sostituito finché resti in un'app senza profilo.",
        "profiles.autoSwitchNote": "La tastiera passa al profilo di un'app quando questa è in primo piano",
        "profiles.deleteHelp": "Elimina questo profilo dall'app",
        "profiles.dialMode": "Dial: %1$@",
        "profiles.dialOnActivate": "Dial all'attivazione",
        "profiles.dialUnchanged": "Dial invariato",
        "profiles.dontChange": "Non cambiare",
        "profiles.enable": "Attiva",
        "profiles.freeSlots": "%1$@ slot libero/i",
        "profiles.hardwareNote": "La tastiera conserva cinque profili in memoria (menu Profile del dial). Ognuno ha la propria illuminazione, i propri remap e le proprie immagini D1–D4; l'app aggiunge le azioni dei tasti, la modalità del dial e le app collegate. Anche i dodici tasti del DisplayPad sono salvati in ogni profilo.",
        "profiles.header": "PROFILO %1$@",
        "profiles.iconAndColour": "Icona e colore",
        "profiles.keyboardLighting": "Illuminazione della tastiera",
        "profiles.keyboardProfiles": "PROFILI DELLA TASTIERA",
        "profiles.keysNote": "I tasti D1–D4 e l'illuminazione si impostano nelle rispettive pagine mentre questo profilo è attivo: vengono salvati in questo profilo.",
        "profiles.lightingFirmware": "Illuminazione: %1$@",
        "profiles.lightingMac": "Illuminazione del Mac: %1$@",
        "profiles.linkedApps": "App collegate",
        "profiles.manage": "Gestisci…",
        "profiles.namePlaceholder": "Coding, Musica…",
        "profiles.noLinkedApp": "Nessuna app collegata",
        "profiles.otherwise": "Altrimenti, torna a",
        "profiles.slot": "Slot %1$@",
        "profiles.slotOf": "Profilo %1$@ di %2$@",

        // MARK: reset
        "reset.title": "Ripristino",

        // MARK: section
        "section.buttons.subtitle": "Un'azione di macOS su ciascuno dei quattro tasti con schermo",
        "section.buttons.title": "Tasti D1–D4",
        "section.displays.subtitle": "Lo schermo rotondo del dial e i tasti con schermo del tastierino numerico",
        "section.displays.title": "Schermi",
        "section.keyboard.subtitle": "Layout della tastiera rilevato e layout di macOS corrispondente",
        "section.keyboard.title": "Layout",
        "section.lighting.subtitle": "Effetti ufficiali della tastiera ed effetti dinamici calcolati dal Mac",
        "section.overview.subtitle": "Il tuo Everest Max a colpo d'occhio",
        "section.overview.title": "Panoramica",
        "section.profiles.subtitle": "Cinque profili memorizzati nella tastiera, ciascuno con i propri tasti, illuminazione e app",
        "section.profiles.title": "Profili",
        "section.system.subtitle": "Daemon dei tasti, monitoraggio e risoluzione dei problemi",
        "section.system.title": "Sistema",

        // MARK: settings
        "settings.language.automatic": "Automatica (lingua del sistema)",
        "settings.language.note": "Lingua dell'interfaccia, del menu nella barra dei menu e dei messaggi.",
        "settings.language.title": "Lingua",

        // MARK: status
        "status.animationPaused": "Animazione in pausa — la tastiera conserva l'ultimo fotogramma.",
        "status.appIconUnreadable": "Impossibile leggere l'icona dell'app.",
        "status.appNoId": "Questa app non ha un identificatore: non può essere collegata.",
        "status.changeFailed": "Impossibile modificare: %1$@",
        "status.cleaning": "Pulizia",
        "status.clockSynced": "Orologio sincronizzato con il Mac.",
        "status.configSaved": "Impostazioni salvate.",
        "status.daemonOff": "Tasti D1–D4 disattivati.",
        "status.daemonOn": "Tasti D1–D4 attivi.",
        "status.daemonStartFailed": "Impossibile avviare il daemon: %1$@",
        "status.dialImageSent": "Immagine inviata al dial.",
        "status.dialMode": "Dial: %1$@.",
        "status.displayLabel": "Schermo",
        "status.effectApplied": "%1$@ applicato e salvato nel profilo.",
        "status.effectRunningKeyboard": "L'effetto «%1$@» è in esecuzione sulla tastiera.",
        "status.factoryIconRestored": "Icona di fabbrica ripristinata su %1$@.",
        "status.frozen": "Fotogramma fissato e salvato nello slot «Custom» della tastiera.",
        "status.iconDrawFailed": "Impossibile disegnare l'icona.",
        "status.iconSent": "Icona inviata a %1$@ in %2$@ s.",
        "status.keyboardConnected": "Tastiera connessa.",
        "status.keyboardGone": "Tastiera disconnessa — l'effetto riprenderà al ricollegamento.",
        "status.layoutAuto": "Layout: rilevamento automatico.",
        "status.layoutForced": "Layout forzato: %1$@.",
        "status.leftoversCleared": "Azioni residue cancellate dalla memoria della tastiera.",
        "status.loginApproval": "Da approvare in Impostazioni di Sistema → Generali → Elementi login.",
        "status.previewOnly": "Tastiera non trovata — l'anteprima resta disponibile.",
        "status.profileActivated": "Profilo «%1$@» attivato.",
        "status.profileActivatedFrontApp": "Profilo «%1$@» attivato (app in primo piano).",
        "status.profileFromKeyboard": "Profilo «%1$@» attivo (scelto sulla tastiera).",
        "status.profileRemoved": "Profilo rimosso dall'app (la tastiera conserva le sue impostazioni nello slot %1$@).",
        "status.ready": "Pronto",
        "status.recovering": "Recupero",
        "status.recoverySent": "Sequenza di recupero inviata.",
        "status.saving": "Salvataggio",
        "status.sendingImage": "Invio dell'immagine…",
        "status.uploadBusy": "Un trasferimento è in corso su %1$@ — aspetta qualche secondo.",
        "status.uploadBusyAlready": "Un trasferimento è già in corso su %1$@ — aspetta qualche secondo.",
        "status.uploadFailed": "Trasferimento non riuscito: %1$@",
        "status.uploadFailedKey": "%1$@: trasferimento non riuscito — %2$@",
        "status.uploadStarted": "%1$@: invio dell'immagine alla tastiera…",

        // MARK: system
        "system.askAgain": "Chiedi di nuovo",
        "system.autoDaemon": "Attiva automaticamente i tasti D1–D4",
        "system.autoDaemonNote": "Il daemon si avvia con l'app, si riconnette da solo quando la tastiera viene ricollegata e riparte se si ferma.",
        "system.autostartHint": "Avvio automatico al login: ./install-daemon.sh dal Terminale.",
        "system.background": "Everest lavora in background, dalla barra dei menu",
        "system.daemonSubtitle": "Esegue le azioni di D1–D4 e invia i valori al dial",
        "system.daemonTitle": "Daemon dei tasti",
        "system.keepRunning": "Mantieni Everest attivo quando chiudo la finestra",
        "system.keepRunningNote": "I tasti D1–D4, i profili e gli effetti continuano a funzionare; l'icona resta nella barra dei menu. Per uscire: menu dell'icona o ⌘Q.",
        "system.keyboardCard": "Tastiera",
        "system.keyboardCardNote": "Stato riportato dal firmware",
        "system.launchAtLogin": "Avvia Everest al login",
        "system.launchAtLoginNote": "Si avvia in modo discreto nella barra dei menu, senza aprire la finestra.",
        "system.launchedFrom": "Everest è in esecuzione da %1$@. Per un avvio affidabile, copialo in /Applications (./make-app.sh --install): un volume esterno non è sempre montato al login.",
        "system.lightProfile": "Profilo luce",
        "system.listening": "In ascolto",
        "system.metricsEvery": "Il daemon invia i valori ogni 0,5 s mentre è in esecuzione.",
        "system.modules": "Moduli",
        "system.monitoring": "Monitoraggio",
        "system.monitoringNote": "Valori di sistema mostrati sul dial",
        "system.noAccessibility": "Everest non ha il permesso Accessibilità",
        "system.noAccessibilityNote": "Senza, le azioni «scorciatoia» e «testo» non fanno nulla (le azioni app, comando e link funzionano). Se Everest è già spuntato nell'elenco, la voce è obsoleta: selezionala, rimuovila con «−», poi aggiungila di nuovo con «+» (Everest.app) e riavvia il daemon.",
        "system.openSettings": "Apri Impostazioni",
        "system.sendMetrics": "Invia CPU, GPU, RAM, disco, rete e volume",
        "system.stoppedState": "Fermo",
        "system.unlock": "Sblocca la tastiera",
        "system.unlockNote": "«Sblocca» invia il reset dell'SDK se un trasferimento di immagine è stato interrotto. Se non basta, scollega e ricollega la tastiera: non si perde nulla.",

        // MARK: upload
        "upload.phase.connect": "Connessione alla tastiera",
        "upload.phase.done": "Fatto",
        "upload.phase.finish": "Finalizzazione",
        "upload.phase.prepare": "La tastiera sta preparando lo slot",
        "upload.phase.send": "Invio dell'immagine",

        "status.configReloaded": "Le impostazioni sono state modificate fuori dall'app e sono state ricaricate.",

        // MARK: pad
        "live.revenueToday": "Vendite di oggi",
        "live.revenue30Days": "Vendite 30 giorni",
        "live.commitsToday": "Commit di oggi",
        "live.today": "oggi",
        "live.days30": "30 giorni",
        "mrr.subtitle": "MRR, vendite e commit sui tasti del DisplayPad",
        "mrr.tokenSaved": "Token salvato — incollane uno nuovo per sostituirlo",
        "mrr.saveTest": "Salva e prova",
        "mrr.disconnect": "Disconnetti",
        "mrr.server": "Server",
        "mrr.testing": "Verifica…",
        "mrr.note": "Crea un token di accesso personale in MRRCalendar (Account › Integrations). Resta nel tuo portachiavi e legge solo i tuoi numeri.",
        "mrr.ok": "Connesso: MRR %1$@, %2$@ commit oggi.",
        "mrr.unauthorized": "Il token è stato rifiutato: controllalo o creane uno nuovo.",
        "mrr.failed": "Impossibile raggiungere MRRCalendar (%1$@).",
        "night.displays": "Metti in stop anche gli schermi del Mac",
        "night.displaysNote": "Solo gli schermi, non il Mac. Se macOS chiede la password quando lo schermo si spegne (impostazioni Blocco schermo), la sessione resta bloccata durante la notte.",
        "action.night": "Modalità notte",
        "night.note": "Spegne l'illuminazione della tastiera e il DisplayPad e silenzia l'audio; premi di nuovo per ripristinare tutto.",
        "night.active": "Modalità notte attiva",
        "action.profile": "Profilo",
        "profileAction.next": "Profilo successivo",
        "profileAction.previous": "Profilo precedente",
        "profiles.newCopyPad": "Nuovo, con i tasti DisplayPad di «%1$@»",
        "live.fiveHours": "5 ore",
        "codexbar.ok": "Dati di CodexBar: OK",
        "codexbar.denied": "Everest non può leggere i dati di CodexBar",
        "codexbar.deniedNote": "macOS protegge i dati delle altre app e un'app non può aggiungersi da sola ad «Accesso completo al disco». Trascina Everest dalla finestra del Finder nell'elenco (o usa +), attivalo, poi chiudi e riapri Everest.",
        "codexbar.openSettings": "Apri impostazioni",
        "live.week": "settimana",
        "keyappearance.liveCodexBar": "Claude e Codex mostrano i tuoi limiti d'uso come li ha letti CodexBar (li aggiorna ogni pochi minuti): un tasto per la finestra di 5 ore, uno per la settimana.",
        "pad.status.swapped": "%1$@ e %2$@ scambiati.",
        "keyappearance.live": "Dal vivo",
        "keyappearance.liveAction": "Apri anche l'app corrispondente",
        "keyappearance.liveNote": "Ridisegnato quando il valore cambia (al massimo una volta al secondo) finché il pad è collegato. Il tasto mantiene la sua azione.",
        "pad.keysActive": "Tasti P1–P12 attivi",
        "pad.overview.keys": "%1$@ tasti su 12 configurati",
        "pad.overview.firmware": "Firmware %1$@",
        "section.displaypad.title": "DisplayPad",
        "pad.unsupported": "Il firmware %1$@ del DisplayPad non è supportato",
        "pad.unsupportedNote": "Everest scrive solo sul firmware 8, la versione testata, e lascia stare questo pad.",
        "pad.noAnswer": "Il DisplayPad non risponde",
        "pad.noAnswerNote": "È collegato ma non risponde: attendi qualche secondo o collegalo direttamente al Mac.",
        "section.displaypad.subtitle": "Dodici tasti con schermo, ognuno con un'immagine e un'azione macOS",
        "pad.connected": "DisplayPad connesso",
        "pad.connectedNote": "Le immagini vengono inviate entro un secondo da ogni modifica; il pad le conserva finché non viene scollegato.",
        "pad.notConnected": "DisplayPad non connesso",
        "pad.notConnectedNote": "Collegalo direttamente al Mac: con alcuni hub USB lo schermo resta nero.",
        "pad.brightness": "Luminosità",
        "pad.keys": "Tasti",
        "pad.keysNote": "Fai clic su un tasto per modificarlo, o trascinalo su un altro per scambiarli. Immagini e azioni sono salvate nel profilo «%1$@».",
        "pad.clearKey": "Cancella",
        "pad.clearKeyHelp": "Rimuove l'immagine e l'azione di %1$@",
        "pad.noImage": "Nessuna immagine",
        "pad.ownImageNote": "Viene ritagliata al centro e ridimensionata a 102 × 102. L'azione del tasto non cambia.",
        "pad.daemonStoppedNote": "I tasti del DisplayPad funzionano solo mentre è attivo.",
        "pad.status.sent": "%1$@: inviato al DisplayPad.",
        "pad.status.savedOffline": "%1$@: salvato — verrà mostrato quando il DisplayPad sarà collegato.",
        "pad.status.failed": "DisplayPad: %1$@",
    ]
}
